### ISSUE TITLE
Memory leak warning with more than 9 tabs

### ISSUE THREAD

**Issue by bridiver** [brave/browser-laptop#101]
Steps to reproduce:
1. Create 10 tabs
```
(node) warning: possible EventEmitter memory leak detected. 11 crashed listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:239:17)
    at EventEmitter.once (events.js:265:8)
    at createGuest (/Users/bjohnson/Documents/brave/browser-electron/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/guest-view-manager.js:51:16)
    at EventEmitter.<anonymous> (/Users/bjohnson/Documents/brave/browser-electron/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/guest-view-manager.js:167:66)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at EventEmitter.<anonymous> (/Users/bjohnson/Documents/brave/browser-electron/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:91:27)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

**Comment by rorycurtis** [comment]
I'm running Brave on OSX El Capitan (10.11.3). The browser was running fine for a few days but after leaving it running with multiple tabs open (8-10) the memory (32 GB) and cpu were completely maxed out. Killing the Brave process sorted it.

Let me know if there's any logs I can provide to help you track it down.

**Comment by luixxiul** [comment]
Still reproducible?

CC: @bbondy

**Comment by bbondy** [comment]
fairly sure this is fixed, closing.
