### ISSUE TITLE
Error generating docs for file windowActions.js

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10209]
**Describe the issue you encountered:**

````
brave-mbp:browser-laptop Suguru$ git commit --amend -S
Error generating docs for file windowActions.js SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at jsdocParser._onComplete (/Users/Suguru/browser-laptop/node_modules/jsdoc3-parser/index.js:79:19)
    at ChildProcess.exithandler (child_process.js:262:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at jsdocParser._onComplete (/Users/Suguru/browser-laptop/node_modules/jsdoc3-parser/index.js:79:19)
    at ChildProcess.exithandler (child_process.js:262:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
/Users/Suguru/browser-laptop/node_modules/jsdox/jsdox.js:300
            throw err;
            ^

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at jsdocParser._onComplete (/Users/Suguru/browser-laptop/node_modules/jsdoc3-parser/index.js:79:19)
    at ChildProcess.exithandler (child_process.js:262:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12)
pre-commit: 
pre-commit: We've failed to pass the specified git pre-commit hooks as the `docs`
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit: 
pre-commit:   git commit -n (or --no-verify)
pre-commit: 
pre-commit: This is ill-advised since the commit is broken.
pre-commit: 
````

- Platform (Win7, 8, 10? macOS? Linux distro?): 

- Brave Version (revision SHA): master branch

- Steps to reproduce: `git commit`
    
- Actual result: See above

- Expected result: the error should not happen

- Any related issues:

**Comment by luixxiul** [comment]
This can no longer be reproduced. closing.
