### ISSUE TITLE
downloadItem tests are failing

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#10223]
**Describe the issue you encountered:**
Tests are failing. This tests started failing after this PR was merged #9864 

https://travis-ci.org/brave/browser-laptop/jobs/258747356#L3835
```
  1) downloadItem test check if you can cancel download:
     Promise was rejected with the following reason: timeout
  Error
  2) downloadItem test check if you can re-download:
     Error: Promise was rejected with the following reason: timeout
      at elements("[data-test-id="redownloadButton"]") - brave.js:428:21
  3) downloadItem test check if you can remove item from the list:
     Error: Promise was rejected with the following reason: timeout
      at elements("[data-test-id="redownloadButton"]") - brave.js:428:21
  4) downloadItem test check if you can delete downloaded item:
     Error: Promise was rejected with the following reason: timeout
      at elements("[data-test-id="redownloadButton"]") - brave.js:428:21
```

**Comment by luixxiul** [comment]
It looks like because `[data-test-id="redownloadButton"]` etc is not specified for the buttons such as https://github.com/brave/browser-laptop/blob/dec236fdf5b512a957d39425c523cb7520bf557c/app/renderer/components/download/downloadItem.js#L193

**Comment by NejcZdovc** [comment]
also when you cancel a download item I get this error
```
TypeError: Cannot read property 'getTotalBytes' of undefined
at module.exports.updateElectronDownloadItem (/browser-laptop/app/browser/electronDownloadItem.js:35:46)
at updateDownloadState (/browser-laptop/app/filtering.js:500:3)
at DownloadItem.<anonymous> (/browser-laptop/app/filtering.js:566:7)
    at emitTwo (events.js:106:13)
    at DownloadItem.emit (events.js:194:7)
    at module.exports.cancelDownload (/browser-laptop/app/browser/electronDownloadItem.js:54:54)
    at downloadsReducer (/browser-laptop/app/browser/reducers/downloadsReducer.js:49:11)
    at reducers.reduce (/browser-laptop/js/stores/appStore.js:379:24)
    at Array.reduce (<anonymous>)
        at applyReducers (/browser-laptop/js/stores/appStore.js:377:68)
```

**Comment by NejcZdovc** [comment]
ok will take a quick look into both of this problems

**Comment by NejcZdovc** [comment]
ok bug found, will create a PR
