### ISSUE TITLE
Fresh installation on Fedora 26 and Brave doesn't initialize 

### ISSUE THREAD

**Issue by eduardocerqueira** [brave/browser-laptop#10280]
- Did you search for similar issues before submitting this one?
Yes and I didn't find any one similar

- Describe the issue you encountered:
I followed the installation steps from https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md#fedora-x86_64
the process ran smooth without error. When I try to start up BRAVE it starts several process and generate the final error: Process failed to load within 60 seconds

- Platform (Win7, 8, 10? macOS? Linux distro?):

Linux Fedora 26

- Brave Version (revision SHA):

- Steps to reproduce:
    1. follow https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md#fedora-x86_64

sudo dnf config-manager --add-repo https://s3-us-west-2.amazonaws.com/brave-rpm-release/x86_64/
sudo rpm --import https://s3-us-west-2.amazonaws.com/brave-rpm-release/keys.asc
sudo dnf install brave

    2. open a terminal and type: brave
    3. open a second terminal and type: ps aux |grep brave
    
- Actual result:

```[ecerquei@dev paws]$ brave 
Crash reporting enabled
An uncaught exception occurred in the main process Uncaught Exception:
Error: libgnome-keyring.so.0: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:182:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /usr/share/brave/resources/app.asar/node_modules/keytar/lib/keytar.js:4:12
    at /usr/share/brave/resources/app.asar/node_modules/keytar/lib/keytar.js:58:4
Waiting 60 seconds for process to load
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'getIn' of null
    at registerComponents (/usr/share/brave/resources/app.asar/app/extensions.js:535:28)
    at Object.module.exports.init (/usr/share/brave/resources/app.asar/app/extensions.js:540:3)
    at perWindowStateLoaded (/usr/share/brave/resources/app.asar/app/index.js:181:16)
    at Immediate.setImmediate (/usr/share/brave/resources/app.asar/app/index.js:171:24)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate (timers.js:617:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Waiting 60 seconds for process to load
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'get' of null
    at Object.getExtensions (/usr/share/brave/resources/app.asar/app/common/state/extensionState.js:16:17)
    at ComponentUpdater.componentUpdater.on (/usr/share/brave/resources/app.asar/app/extensions.js:350:39)
    at emitTwo (events.js:106:13)
    at ComponentUpdater.emit (events.js:194:7)
Waiting 60 seconds for process to load
Action called before state was initialized: extension-installed
Action called before state was initialized: extension-enabled
Action called before state was initialized: extension-installed
Action called before state was initialized: extension-enabled
Action called before state was initialized: extension-installed
Action called before state was initialized: extension-enabled
Process failed to load within 60 seconds
Process failed to load within 60 seconds
Process failed to load within 60 seconds
```

and several process running:

```[ecerquei@dev paws]$ ps aux |grep brave
ecerquei 21380  5.4  0.6 2742620 135148 tty2   Sl+  16:39   0:01 /usr/share/brave/brave --
ecerquei 21390  0.0  0.1 438584 26312 tty2     S+   16:39   0:00 /usr/share/brave/brave --type=zygote
ecerquei 21393  0.0  0.0 438584  5040 tty2     S+   16:39   0:00 /usr/share/brave/brave --type=zygote
ecerquei 21420  0.2  0.1 490412 37896 tty2     Sl+  16:39   0:00 /usr/share/brave/brave --type=gpu-process --supports-dual-gpus=false --gpu-driver-bug-workarounds=1,7,24,64,77 --disable-gl-extensions=GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent --gpu-vendor-id=0x8086 --gpu-device-id=0x1916 --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --service-request-channel-token=B0AE131CA604534DB093E684C5065D41
ecerquei 21423  0.0  0.0 474016  8500 tty2     S+   16:39   0:00 /usr/share/brave/brave --type=gpu-broker
ecerquei 21582  0.1  0.3 809908 62748 tty2     Sl+  16:39   0:00 /usr/share/brave/brave --type=renderer --service-pipe-token=1947BF036A970E53F05D3CD82BB39407 --lang=en_US --extension-process --disable-client-side-phishing-detection --enable-pinch --num-raster-threads=2 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;0,16,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;1,16,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;2,16,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;3,16,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553;4,16,3553 --disable-accelerated-video-decode --service-request-channel-token=1947BF036A970E53F05D3CD82BB39407 --renderer-client-id=3 --shared-files=v8_natives_data:100,v8_snapshot_data:101
ecerquei 21587  0.5  0.3 818720 67528 tty2     Sl+  16:39   0:00 /usr/share/brave/brave --type=renderer --service-pipe-token=42892B3C11F1BA56398EA9A82B8FFA02 --lang=en_US --extension-process --disable-client-side-phishing-detection --enable-pinch --num-raster-threads=2 --enable-main-frame-before-activation --content-image-texture-target=0,0,3553;0,1,3553;0,2,3553;0,3,3553;0,4,3553;0,5,3553;0,6,3553;0,7,3553;0,8,3553;0,9,3553;0,10,3553;0,11,3553;0,12,3553;0,13,3553;0,14,3553;0,15,3553;0,16,3553;1,0,3553;1,1,3553;1,2,3553;1,3,3553;1,4,3553;1,5,3553;1,6,3553;1,7,3553;1,8,3553;1,9,3553;1,10,3553;1,11,3553;1,12,3553;1,13,3553;1,14,3553;1,15,3553;1,16,3553;2,0,3553;2,1,3553;2,2,3553;2,3,3553;2,4,3553;2,5,3553;2,6,3553;2,7,3553;2,8,3553;2,9,3553;2,10,3553;2,11,3553;2,12,3553;2,13,3553;2,14,3553;2,15,3553;2,16,3553;3,0,3553;3,1,3553;3,2,3553;3,3,3553;3,4,3553;3,5,3553;3,6,3553;3,7,3553;3,8,3553;3,9,3553;3,10,3553;3,11,3553;3,12,3553;3,13,3553;3,14,3553;3,15,3553;3,16,3553;4,0,3553;4,1,3553;4,2,3553;4,3,3553;4,4,3553;4,5,3553;4,6,3553;4,7,3553;4,8,3553;4,9,3553;4,10,3553;4,11,3553;4,12,3553;4,13,3553;4,14,3553;4,15,3553;4,16,3553 --disable-accelerated-video-decode --service-request-channel-token=42892B3C11F1BA56398EA9A82B8FFA02 --renderer-client-id=4 --shared-files=v8_natives_data:100,v8_snapshot_data:101
ecerquei 21631  0.0  0.0 119448   968 pts/1    S+   16:39   0:00 grep --color=auto brave
```

- Expected result:
see brave browser

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
I think it is latest

- Can this issue be consistently reproduced?
I think so

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
@posix4e would you mind checking this out? thanks!

**Comment by posix4e** [comment]
@eduardocerqueira Can you install libgnome-keyring.so.0 via libgnome-keyring. If it works  I'll add it to the package

**Comment by Jazqa** [comment]
@posix4e, I tried Brave today on Fedora and it would not start until I installed libgnome-keyring. After installing libgnome-keyring, everything worked wonderfully. It should be installed with the package.

**Comment by bsclifton** [comment]
@posix4e is the fix for this as easy as updating the RPM spec file?

**Comment by kuboosoft** [comment]
@eduardocerqueira @bsclifton @posix4e  all! [UnitedRPMs](https://unitedrpms.github.io/) has [Brave browser](https://unitedrpms.sourceforge.io/x86_64/repoview/brave.html) in its repository updated and working perfectly, also flash works fine...
