### ISSUE TITLE
unable to save state after shutdown

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#10332]
str:

1. clear session
2. open brave
3. go to twitter.com
4. shutdown
5. re-open brave
6. new tab page is shown, should be twitter (saved state)

also have the following err:

```
Error saving app state:  TypeError: Cannot read property 'filter' of undefined
    at payload.perWindowState.forEach (/Users/cezaraugusto/dev/browser-laptop/app/sessionStore.js:72:46)
    at Array.forEach (<anonymous>)
    at Promise (/Users/cezaraugusto/dev/browser-laptop/app/sessionStore.js:71:30)
    at Promise (<anonymous>)
    at Object.module.exports.saveAppState (/Users/cezaraugusto/dev/browser-laptop/app/sessionStore.js:65:10)
    at saveAppState (/Users/cezaraugusto/dev/browser-laptop/app/sessionStoreShutdown.js:88:23)
    at Timeout.setTimeout (/Users/cezaraugusto/dev/browser-laptop/app/sessionStoreShutdown.js:154:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

cc @bbondy

**Comment by bsclifton** [comment]
Closing as this was a mistake on my part- this issue was fixed by updating Muon in browser-laptop 0.19.x and newer versions to 4.4.6 😄
