### ISSUE TITLE
Error: Cannot find module '../../app/ledger', './stores/appStore'

### ISSUE THREAD

**Issue by kenorb** [brave/browser-laptop#10494]
Brave: 0.18.22 
rev: d850e287ace296e2c62e28ba2979cf172e41cc45 
Muon: 4.3.9 
libchromiumcontent: 60.0.3112.90 
V8: 6.0.286.52 
Node.js: 7.9.0 
Update Channel: dev 
OS Platform: macOS 
OS Release: 16.0.0 
OS Architecture: x64

- Steps to reproduce:
    1. Run from Terminal: `/Applications/Brave.app/Contents/MacOS/Brave`
    
- Actual result:

Brave is ran, but with the following errors on the console:

```
$ /Applications/Brave.app/Contents/MacOS/Brave
Crash reporting enabled
An uncaught exception occurred in the main process Uncaught Exception:
Error: Cannot find module '../../app/ledger'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Applications/Brave.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at handleAppAction (/Applications/Brave.app/Contents/Resources/app.asar/js/stores/appStore.js:391:14)
    at callbacks.forEach (/Applications/Brave.app/Contents/Resources/app.asar/js/dispatcher/appDispatcher.js:97:7)
    at Array.forEach (<anonymous>)
    at AppDispatcher.dispatchToOwnRegisteredCallbacks (/Applications/Brave.app/Contents/Resources/app.asar/js/dispatcher/appDispatcher.js:96:20)
    at AppDispatcher.dispatchInternal (/Applications/Brave.app/Contents/Resources/app.asar/js/dispatcher/appDispatcher.js:122:10)
Waiting 60 seconds for process to load
An uncaught exception occurred in the main process Uncaught Exception:
Error: Cannot find module './stores/appStore'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Applications/Brave.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at resolveValue (/Applications/Brave.app/Contents/Resources/app.asar/js/settings.js:56:9)
    at module.exports.getSetting (/Applications/Brave.app/Contents/Resources/app.asar/js/settings.js:70:19)
    at Object.module.exports.init (/Applications/Brave.app/Contents/Resources/app.asar/app/extensions.js:468:7)
    at perWindowStateLoaded (/Applications/Brave.app/Contents/Resources/app.asar/app/index.js:180:16)
    at Immediate.setImmediate (/Applications/Brave.app/Contents/Resources/app.asar/app/index.js:170:24)
Waiting 60 seconds for process to load

```

- Is this an issue in the currently released version?
Yes.
- Can this issue be consistently reproduced?
Yes.

- Extra QA steps (for macOS):
    1. Run from Terminal: `/Applications/Brave.app/Contents/MacOS/Brave`
    2.
    3.

- Any related issues:

 * #7911

**Comment by NejcZdovc** [comment]
@srirambv @LaurenWags @kjozwiak did anyone experience this problem in 0.18.22?

**Comment by kjozwiak** [comment]
> @brave/qa did anyone experience this problem in 0.18.22?

I managed to reproduce the above exception pretty easily with both 0.18.14 and 0.18.22 builds. Because this is something that a typical user wouldn't do on a regular basis, I'm going moving this out of the `0.18.x Hotfix` milestone for now pending triage.

Using the STR from the original comment, reproduced the issue using the following builds:

> Brave 0.18.14 rev ad92d029e184c4cff01b2e9f4916725ba675e3c8
> Muon 4.3.6
> libchromiumcontent	60.0.3112.78

> Brave 0.18.22 | rev d850e287ace296e2c62e28ba2979cf172e41cc45
> Muon 4.3.9
> libchromiumcontent 60.0.3112.90

**Comment by NejcZdovc** [comment]
@kjozwiak thank you for checking it out

**Comment by kjozwiak** [comment]
I ran into the above error today while using `0.19.121` when going through https://github.com/brave/browser-laptop/milestone/91... I basically had 2-3 windows opened with about 10 tabs in each window. When I closed Brave, I received the following error via the terminal:

```
An uncaught exception occurred in the main process Uncaught Exception:
Error: Cannot find module '../../../js/stores/appStore'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/usr/lib/brave/resources/electron.asar/common/reset-search-paths.js:41:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (/usr/lib/brave/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at debounce (/usr/lib/brave/resources/app.asar/app/browser/api/topSites.js:83:16)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by NejcZdovc** [comment]
removing ledger label, since last report is triggered from the top sites
