### ISSUE TITLE
Closing re-attached about tab next to another about tab causes Uncaught Exception

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#10538]
Describe the issue you encountered: Closing re-attached about tab next to another about tab causes Uncaught Exception

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian

- Brave Version (revision SHA): 0.18.23

- Steps to reproduce:
    1. Clear the browser's profile
    2. Start the browser 
    3. Open `about:preferences` in a new tab next to `Welcome` tab
    4. Detach the preference tab
    5. Re-attach the preference tab
    6. Click the close button on the tab
    
- Actual result: the tab is not closed and other tabs cannot be closed as well. the browser also cannot be closed.

  ````
  An uncaught exception occurred in the main process Uncaught Exception:
  AssertionError: Could not find tab for 21
      at Object.getTabPropertyByTabId (/usr/lib/brave/resources/app.asar/app/common/state/tabState.js:464:12)
      at Object.getWindowId (/usr/lib/brave/resources/app.asar/app/common/state/tabState.js:470:21)
      at tabsReducer (/usr/lib/brave/resources/app.asar/app/browser/reducers/tabsReducer.js:182:39)
      at reducers.reduce (/usr/lib/brave/resources/app.asar/js/stores/appStore.js:382:24)
      at Array.reduce (<anonymous>)
      at applyReducers (/usr/lib/brave/resources/app.asar/js/stores/appStore.js:380:68)
      at handleAppAction (/usr/lib/brave/resources/app.asar/js/stores/appStore.js:423:14)
      at callbacks.forEach (/usr/lib/brave/resources/app.asar/js/dispatcher/appDispatcher.js:97:7)
      at Array.forEach (<anonymous>)
      at AppDispatcher.dispatchToOwnRegisteredCallbacks 
  (/usr/lib/brave/resources/app.asar/js/dispatcher/appDispatcher.js:96:20)
  ````

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by luixxiul** [comment]
Duping to #9722
