### ISSUE TITLE
Fix webdriver tests on Windows

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#10618]
webdriver tests are currently failing on Windows

For example, running `npm run test -- --grep="tab tests"` yields:
```
  > brave@0.20.0 test C:\GitHub\browser-laptop
> cross-env NODE_ENV=test mocha "test/**/*Test.js" "--grep=tab tests"



  about:newtab tests
    with NEWTAB_MODE === HOMEPAGE
      1) "before all" hook
      2) "after all" hook
    with NEWTAB_MODE === NEW_TAB_PAGE
      when displaying stats
        - shows # trackers blocked
        - shows # ads blocked
      with the top sites tile area
        - shows a preloaded list of sites if session has no entries yet
        - shows sites that have been visited
        - lets you pin a tile (and shows the pinned icon afterwards)
        - doesn't show about pages on topSites grid
        - shows favicon image for topSites
        - replace topSites favicon images with a letter when no icon is found

  tab tests
    back forward actions
{ Error: ENOENT: no such file or directory, scandir 'C:\Users\brian\AppData\Local\Temp\brave-test\1503350449307238'
    at Object.fs.readdirSync (fs.js:914:18)
    at rmDir (C:/GitHub/browser-laptop/test/lib/brave.js:34:20)
    at Context.cleanup (C:/GitHub/browser-laptop/test/lib/brave.js:1121:26)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\brian\\AppData\\Local\\Temp\\brave-test\\1503350449307238' }
      3) "before each" hook for "sets correct title"
      4) "after each" hook for "sets correct title"
    new tab signal
{ Error: ENOENT: no such file or directory, scandir 'C:\Users\brian\AppData\Local\Temp\brave-test\1503350459589820'
    at Object.fs.readdirSync (fs.js:914:18)
    at rmDir (C:/GitHub/browser-laptop/test/lib/brave.js:34:20)
    at Context.cleanup (C:/GitHub/browser-laptop/test/lib/brave.js:1121:26)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\brian\\AppData\\Local\\Temp\\brave-test\\1503350459589820' }
```
(message cut here- there's a lot more logs which look the same)

**Comment by NejcZdovc** [comment]
there is something wrong with chrome driver

```
  1) about:newtab tests with NEWTAB_MODE === HOMEPAGE "before all" hook:
     Error: ChromeDriver did not start within 5000ms
      at C:\Users\Bravex64\Desktop\browser-laptop\node_modules\spectron\lib\chrome-driver.js:63:25
      at Request._callback (C:\Users\Bravex64\Desktop\browser-laptop\node_modules\spectron\lib\chrome-driver.js:120:23)
      at self.callback (C:\Users\Bravex64\Desktop\browser-laptop\node_modules\request\request.js:188:22)
      at Request.onRequestError (C:\Users\Bravex64\Desktop\browser-laptop\node_modules\request\request.js:884:8)
      at Socket.socketErrorListener (_http_client.js:358:9)
      at emitErrorNT (net.js:1280:8)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  2) about:newtab tests with NEWTAB_MODE === HOMEPAGE "after all" hook:
     TypeError: Cannot read property 'waitForBrowserWindow' of undefined
      at promises.push.callback (C:/Users/Bravex64/Desktop/browser-laptop/test/lib/brave.js:1130:7)
      at C:\Users\Bravex64\Desktop\browser-laptop\node_modules\async\internal\parallel.js:31:39
      at replenish (C:\Users\Bravex64\Desktop\browser-laptop\node_modules\async\internal\eachOfLimit.js:64:17)
      at C:\Users\Bravex64\Desktop\browser-laptop\node_modules\async\internal\eachOfLimit.js:68:9
      at eachOfLimit (C:\Users\Bravex64\Desktop\browser-laptop\node_modules\async\eachOfLimit.js:39:36)
      at C:\Users\Bravex64\Desktop\browser-laptop\node_modules\async\internal\doLimit.js:9:16
      at _parallel (C:\Users\Bravex64\Desktop\browser-laptop\node_modules\async\internal\parallel.js:30:5)
      at series (C:\Users\Bravex64\Desktop\browser-laptop\node_modules\async\series.js:83:26)
      at Promise (C:/Users/Bravex64/Desktop/browser-laptop/test/lib/brave.js:1139:7)
      at Context.stopApp (C:/Users/Bravex64/Desktop/browser-laptop/test/lib/brave.js:1138:12)
      at Context.<anonymous> (C:/Users/Bravex64/Desktop/browser-laptop/test/lib/brave.js:167:30)
      at callFn (C:\Users\Bravex64\Desktop\browser-laptop\node_modules\mocha\lib\runnable.js:326:21)
      at Hook.Runnable.run (C:\Users\Bravex64\Desktop\browser-laptop\node_modules\mocha\lib\runnable.js:319:7)
      at Hook.Runnable.run (C:\Users\Bravex64\Desktop\browser-laptop\node_modules\co-mocha\lib\co-mocha.js:43:16)
      at next (C:\Users\Bravex64\Desktop\browser-laptop\node_modules\mocha\lib\runner.js:298:10)
      at Immediate.<anonymous> (C:\Users\Bravex64\Desktop\browser-laptop\node_modules\mocha\lib\runner.js:320:5)
```
