### ISSUE TITLE
macOS signing issue when running buildInstaller.py

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#10798]
When trying to package Brave on macOS (building a DMG), we get the following:
> 00:13:28 WARNING:root:Brave-darwin-x64/Brave.app/Contents/Frameworks/Brave Framework.framework/Brave Framework has a signature section.
> 00:13:28 CI detected, so artifacts will be published if draft release exists
> 00:13:28 Using res/builderConfig.json configuration file
> 00:13:28 Signing app (identity: Developer ID Application: Brave Software, Inc. (KL8N8XSYF4))
> 00:13:28 Error: Command failed: codesign --verify --deep --verbose=2 --strict /Users/jenkins/workspace/browser-laptop-build-macos/Brave-darwin-x64/Brave.app
> 00:13:28 --prepared:/Users/jenkins/workspace/browser-laptop-build-macos/Brave-darwin-x64/Brave.app/Contents/Frameworks/Brave Helper EH.app
> 00:13:28 --validated:/Users/jenkins/workspace/browser-laptop-build-macos/Brave-darwin-x64/Brave.app/Contents/Frameworks/Brave Helper EH.app
> 00:13:28 --prepared:/Users/jenkins/workspace/browser-laptop-build-macos/Brave-darwin-x64/Brave.app/Contents/Frameworks/Brave Helper NP.app
> 00:13:28 --validated:/Users/jenkins/workspace/browser-laptop-build-macos/Brave-darwin-x64/Brave.app/Contents/Frameworks/Brave Helper NP.app
> 00:13:28 --prepared:/Users/jenkins/workspace/browser-laptop-build-macos/Brave-darwin-x64/Brave.app/Contents/Frameworks/Brave Helper.app
> 00:13:28 --validated:/Users/jenkins/workspace/browser-laptop-build-macos/Brave-darwin-x64/Brave.app/Contents/Frameworks/Brave Helper.app
> 00:13:28 --prepared:/Users/jenkins/workspace/browser-laptop-build-macos/Brave-darwin-x64/Brave.app/Contents/Frameworks/Widevine Resources.bundle
> 00:13:28 --prepared:/Users/jenkins/workspace/browser-laptop-build-macos/Brave-darwin-x64/Brave.app/Contents/Frameworks/Brave Framework.framework
> 00:13:28 --prepared:/Users/jenkins/workspace/browser-laptop-build-macos/Brave-darwin-x64/Brave.app/Contents/Frameworks/Brave Framework.framework/Helpers/crashpad_handler
> 00:13:28 --validated:/Users/jenkins/workspace/browser-laptop-build-macos/Brave-darwin-x64/Brave.app/Contents/Frameworks/Brave Framework.framework/Helpers/crashpad_handler
> 00:13:28 --validated:/Users/jenkins/workspace/browser-laptop-build-macos/Brave-darwin-x64/Brave.app/Contents/Frameworks/Brave Framework.framework
> 00:13:28 /Users/jenkins/workspace/browser-laptop-build-macos/Brave-darwin-x64/Brave.app: a sealed resource is missing or invalid
> 00:13:28 In subcomponent: /Users/jenkins/workspace/browser-laptop-build-macos/Brave-darwin-x64/Brave.app/Contents/Frameworks/Widevine Resources.bundle
> 00:13:28 
> 00:13:28     at ChildProcess.exithandler (child_process.js:205:12)
> 00:13:28     at emitTwo (events.js:106:13)
> 00:13:28     at ChildProcess.emit (events.js:194:7)
> 00:13:28     at maybeClose (internal/child_process.js:899:16)
> 00:13:28     at Socket.<anonymous> (internal/child_process.js:342:11)
> 00:13:28     at emitOne (events.js:96:13)
> 00:13:28     at Socket.emit (events.js:191:7)
> 00:13:28     at Pipe._handle.close [as _onclose] (net.js:511:12)
> 00:13:28 From previous event:
> 00:13:28     at MacPackager.sign (/Users/jenkins/workspace/browser-laptop-build-macos/node_modules/electron-builder/out/macPackager.js:282:11)
> 00:13:28     at /Users/jenkins/workspace/browser-laptop-build-macos/node_modules/electron-builder/src/macPackager.ts:85:26
> 00:13:28     at runCallback (timers.js:672:20)
> 00:13:28     at tryOnImmediate (timers.js:645:5)
> 00:13:28     at processImmediate [as _immediateCallback] (timers.js:617:5)
> 00:13:28 From previous event:
> 00:13:28     at /Users/jenkins/workspace/browser-laptop-build-macos/node_modules/electron-builder/src/macPackager.ts:85:10
> 00:13:28     at Generator.next (<anonymous>)
> 00:13:28 From previous event:
> 00:13:28     at MacPackager.pack (/Users/jenkins/workspace/browser-laptop-build-macos/node_modules/electron-builder/out/macPackager.js:182:11)
> 00:13:28     at /Users/jenkins/workspace/browser-laptop-build-macos/node_modules/electron-builder/src/packager.ts:257:24
> 00:13:28     at Generator.next (<anonymous>)
> 00:13:28     at xfs.mkdir.er (/Users/jenkins/workspace/browser-laptop-build-macos/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
> 00:13:28     at FSReqWrap.oncomplete (fs.js:114:15)
> 00:13:28 From previous event:
> 00:13:28     at Packager.doBuild (/Users/jenkins/workspace/browser-laptop-build-macos/node_modules/electron-builder/out/packager.js:379:11)
> 00:13:28     at /Users/jenkins/workspace/browser-laptop-build-macos/node_modules/electron-builder/src/packager.ts:170:52
> 00:13:28     at Generator.next (<anonymous>)
> 00:13:28     at runCallback (timers.js:672:20)
> 00:13:28     at tryOnImmediate (timers.js:645:5)
> 00:13:28     at processImmediate [as _immediateCallback] (timers.js:617:5)
> 00:13:28 From previous event:
> 00:13:28     at Packager.build (/Users/jenkins/workspace/browser-laptop-build-macos/node_modules/electron-builder/out/packager.js:274:11)
> 00:13:28     at /Users/jenkins/workspace/browser-laptop-build-macos/node_modules/electron-builder/src/builder.ts:198:33
> 00:13:28     at Generator.next (<anonymous>)
> 00:13:28 From previous event:
> 00:13:28     at build (/Users/jenkins/workspace/browser-laptop-build-macos/node_modules/electron-builder/out/builder.js:70:21)
> 00:13:28     at Object.<anonymous> (/Users/jenkins/workspace/browser-laptop-build-macos/node_modules/electron-builder/out/cli/build-cli.js:71:41)
> 00:13:28     at Module._compile (module.js:571:32)
> 00:13:28     at Object.Module._extensions..js (module.js:580:10)
> 00:13:28     at Module.load (module.js:488:32)
> 00:13:28     at tryModuleLoad (module.js:447:12)
> 00:13:28     at Function.Module._load (module.js:439:3)
> 00:13:28     at Module.runMain (module.js:605:10)
> 00:13:28     at run (bootstrap_node.js:427:7)
> 00:13:28     at startup (bootstrap_node.js:151:9)
> 00:13:28     at bootstrap_node.js:542:3

**Comment by bsclifton** [comment]
Fixed in 0.18.x with https://github.com/brave/browser-laptop/commit/f421e4d38c5581436d7e5478c60b373bbf93e401
Fixed in master with https://github.com/brave/browser-laptop/commit/183f1b9b263f98061929f43e4ad1d8fbc9d32978

Cherry pick was done to 0.19.x,0.20.x
