### ISSUE TITLE
Build from source causes white screen

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#10995]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Build from source causes white screen
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64
- Brave Version (revision SHA):
master 
- Steps to reproduce:
    1. Build from  source
    2. `npm start` launches the browser but is unuseable only white screen no tabs
    3. 
    
- Actual result:
See Screenshot
- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
```
npm start
 brave@0.21.0 start E:\srirambv\master\browser-laptop
> node ./tools/start.js --user-data-dir=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck

Crash reporting enabled
Error: unrecognized flag --icu_case_mapping
Try --help for options
[7120:6456:0918/092026.182:ERROR:CONSOLE(0)] "(WEBUI context) http://localhost:8080/gen/app.entry.js:17026: Uncaught AssertionError: state must be an Immutable.Map{AssertionError: state must be an Immutable.Map
    at validateState (http://localhost:8080/gen/app.entry.js:24302:10)
    at Object.getByWindowId (http://localhost:8080/gen/app.entry.js:24369:13)
    at isFocused (http://localhost:8080/gen/app.entry.js:15425:27)
    at mergeProps (http://localhost:8080/gen/app.entry.js:73047:23)
    at buildPropsImpl (http://localhost:8080/gen/app.entry.js:9562:10)
    at ReduxComponent.buildProps (http://localhost:8080/gen/app.entry.js:9634:12)
    at new ReduxComponent (http://localhost:8080/gen/app.entry.js:9592:23)
    at http://localhost:8080/gen/app.entry.js:55384:18
    at measureLifeCyclePerf (http://localhost:8080/gen/app.entry.js:55165:12)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (http://localhost:8080/gen/app.entry.js:55383:16)}", source: chrome://brave/E:/srirambv/master/browser-laptop/app/extensions/brave/index-dev.html (0)
```
![image](https://user-images.githubusercontent.com/17010094/30528674-e43bf83c-9c52-11e7-8ff2-7338715d048e.png)

- Any related issues:

**Comment by syuan100** [comment]
+1 on mac osx

**Comment by cezaraugusto** [comment]
can you guys try again? should be ok now

**Comment by syuan100** [comment]
works now! thanks

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/10991

**Comment by bsclifton** [comment]
Verified this works great on Windows and macOS 👍

**Comment by srirambv** [comment]
Worked on Win x64
