### ISSUE TITLE
Undo closed tab after closing a private tab gives an invalid state error

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#11133]
Close a private tab and try reopening closed tab using keyboard shortcut shows the following error
```
An uncaught exception occurred in the main process Uncaught Exception:
AssertionError: Oops! action window-undo-closed-frame didn't return valid state                                                                                                                                   for reducer:

(state, action) => {
  switch (action.actionType) {
    case appConstants.APP_SET_STATE:
      createMenu(state)
      break
    case windowConstants.WINDOW_SET_FOCUSED_FRAME:
      {
        // Update the checkbox next to "Bookmark Page" (Bookmarks menu)
        const frame = frameStateUtil.getFrameByTabId(state, action.tabId)
        if (frame) {
          currentLocation = frame.location
          setMenuItemChecked(state, locale.translation('bookmarkPage'), isCurren                                                                                                                                  tLocationBookmarked(state))
        }
        break
      }
    case appConstants.APP_CHANGE_SETTING:
      if (action.key === settings.SHOW_BOOKMARKS_TOOLBAR) {
        // Update the checkbox next to "Bookmarks Toolbar" (Bookmarks menu)
        setMenuItemChecked(state, locale.translation('bookmarksToolbar'), action                                                                                                                                  .value)
      }
      break
    case windowConstants.WINDOW_UNDO_CLOSED_FRAME:
      {
        if (!lastClosedUrl) {
          return
        }
        closedFrames = closedFrames.delete(lastClosedUrl)
        const nextLastFrame = closedFrames.last()
        lastClosedUrl = nextLastFrame ? nextLastFrame.get('location') : null
        updateRecentlyClosedMenuItems(state)
        break
      }
    case windowConstants.WINDOW_CLEAR_CLOSED_FRAMES:
      {
        if (!action.location) {
          closedFrames = new Immutable.OrderedMap()
          lastClosedUrl = null
        } else {
          closedFrames = closedFrames.delete(action.location)
          if (lastClosedUrl === action.location) {
            lastClosedUrl = null
          }
        }
        updateRecentlyClosedMenuItems(state)
        break
      }
    case appConstants.APP_TAB_CLOSE_REQUESTED:
      {
        action = makeImmutable(action)
        const tab = getByTabId(state, action.get('tabId'))
        const frame = tab && tab.get('frame')
        if (tab && !tab.get('incognito') && frame && frameStateUtil.isValidClose                                                                                                                                  dFrame(frame)) {
          lastClosedUrl = tab.get('url')
          closedFrames = closedFrames.set(tab.get('url'), tab.get('frame'))
          updateRecentlyClosedMenuItems(state)
        }
        break
      }
    case appConstants.APP_APPLY_SITE_RECORDS:
      if (action.records.find((record) => record.objectData === 'bookmark')) {
        createMenu(state)
      }
      break
    case appConstants.APP_ADD_SITE:
    case appConstants.APP_ADD_BOOKMARK:
    case appConstants.APP_EDIT_BOOKMARK:
      {
        if (action.tag === siteTags.BOOKMARK || action.tag === siteTags.BOOKMARK                                                                                                                                  _FOLDER) {
          createMenu(state)
        } else if (action.siteDetail.constructor === Immutable.List && action.ta                                                                                                                                  g === undefined) {
          let shouldRebuild = false
          action.siteDetail.forEach((site) => {
            const tag = site.getIn(['tags', 0])
            if (tag === siteTags.BOOKMARK || tag === siteTags.BOOKMARK_FOLDER) {
              shouldRebuild = true
            }
          })
          if (shouldRebuild) {
            createMenu(state)
          }
        }
        break
      }
    case appConstants.APP_REMOVE_SITE:
      {
        if (!action.tag || action.tag === siteTags.BOOKMARK || action.tag === si                                                                                                                                  teTags.BOOKMARK_FOLDER) {
          createMenu(state)
        }
        break
      }
    case appConstants.APP_ON_CLEAR_BROWSING_DATA:
      {
        const defaults = state.get('clearBrowsingDataDefaults')
        const temp = state.get('tempClearBrowsingData', Immutable.Map())
        const clearData = defaults ? defaults.merge(temp) : temp
        if (clearData.get('browserHistory')) {
          createMenu(state)
        }
        break
      }
    case windowConstants.WINDOW_CLICK_MENUBAR_SUBMENU:
      {
        const clickedMenuItem = menuUtil.getMenuItem(appMenu, action.label)
        if (clickedMenuItem) {
          const focusedWindow = BrowserWindow.getFocusedWindow()
          clickedMenuItem.click(clickedMenuItem, focusedWindow, focusedWindow.we                                                                                                                                  bContents)
        }
        break
      }
    default:
  }

  return state
}
    at reducers.reduce (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.16\resou                                                                                                                                  rces\app.asar\js\stores\appStore.js:385:14)
    at Array.reduce (<anonymous>)
    at applyReducers (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.16\resourc                                                                                                                                  es\app.asar\js\stores\appStore.js:382:68)
    at handleAppAction (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.16\resou                                                                                                                                  rces\app.asar\js\stores\appStore.js:428:14)
    at callbacks.forEach (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.16\res                                                                                                                                  ources\app.asar\js\dispatcher\appDispatcher.js:107:7)
    at Array.forEach (<anonymous>)
    at AppDispatcher.dispatchToOwnRegisteredCallbacks (C:\Users\Sriram BV\AppDat                                                                                                                                  a\Local\brave\app-0.19.16\resources\app.asar\js\dispatcher\appDispatcher.js:106:                                                                                                                                  20)
    at AppDispatcher.dispatchInternal (C:\Users\Sriram BV\AppData\Local\brave\ap                                                                                                                                  p-0.19.16\resources\app.asar\js\dispatcher\appDispatcher.js:132:10)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
[368:5884:0925/144547.641:ERROR:CONSOLE(0)] "Unchecked runtime.lastError while r                                                                                                                                  unning guestViewInternal.destroyGuest: Unknown error.", source: chrome://brave/C                                                                                                                                  :/Users/Sriram%20BV/AppData/Local/brave/app-0.19.16/resources/app.asar/app/exten                                                                                                                                  sions/brave/index.html (0)
[368:5884:0925/144550.833:ERROR:CONSOLE(0)] "Unchecked runtime.lastError while r                                                                                                                                  unning guestViewInternal.destroyGuest: Unknown error.", source: chrome://brave/C                                                                                                                                  :/Users/Sriram%20BV/AppData/Local/brave/app-0.19.16/resources/app.asar/app/exten                                                                                                                                  sions/brave/index.html (0)
$

```
Above issue for private tab was reproduced twice only. 
cc: @bbondy @bsclifton

**Comment by bbondy** [comment]
0.19.x: 37ead60dcbb2467d9637100e7b62c3f289dfbba3
0.20.x: eb01888fe6164fb7e22a21feb189bb3a823bae08

Fix ended up not being needed in master.

**Comment by kjozwiak** [comment]
Reproduced the issue using v0.19.13 rev: e57786547893a03b1e41b407dacba729133bd8a2 with the STR from https://github.com/brave/browser-laptop/issues/11133#issue-260302985 on all the platforms. Went through verification using the following build:

> Brave: 0.19.25 
> rev: d4fd17a426fe6e19f1acc225fb64e46d80be2105 
> Muon: 4.4.25 
> libchromiumcontent: 61.0.3163.100

Platforms Tested:

* macOS 10.12.6 x64 - PASSED
* Ubuntu 17.04 x64 - PASSED
* Win 10 x64 - PASSED
