### ISSUE TITLE
Automated tests related 'data-test-active-tab' and  'data-test-pinned-tab' failing

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11135]
### Description

Automated tests related 'data-test-active-tab'and 'data-test-pinned-tab' failing. Here's a part of the error lists which look related with this change: https://github.com/brave/browser-laptop/commit/f17046da6007ef19dd2ae1256522f62416f89d9f#diff-4f164dab3a38a1443d7ba3288fef641eL348 for #10691 by @cezaraugusto 

There could be some unrelated issues.

````
6) MessageBox component tests alert when opening a new tab (while alert is showing) lets you follow links in the tab:
 Error: element ("[data-test-id="tab"][data-test-active-tab="true"] [data-test-id="tabTitle"]") still not visible after 10000ms
  at elements("[data-test-id="tab"][data-test-active-tab="true"] [data-test-id="tabTitle"]") - isVisible.js:54:17
  at isVisible("[data-test-id="tab"][data-test-active-tab="true"] [data-test-id="tabTitle"]") - waitForVisible.js:73:22

7) MessageBox component tests alert when opening a new tab (while alert is showing) lets you use the back button:
 Error: element ("[data-test-id="tab"][data-test-active-tab="true"] [data-test-id="tabTitle"]") still not visible after 10000ms
  at elements("[data-test-id="tab"][data-test-active-tab="true"] [data-test-id="tabTitle"]") - isVisible.js:54:17
  at isVisible("[data-test-id="tab"][data-test-active-tab="true"] [data-test-id="tabTitle"]") - waitForVisible.js:73:22

8) MessageBox component tests alert when opening a new tab (while alert is showing) lets you use the forward button:
 Error: element ("[data-test-id="tab"][data-test-active-tab="true"] [data-test-id="tabTitle"]") still not visible after 10000ms
  at elements("[data-test-id="tab"][data-test-active-tab="true"] [data-test-id="tabTitle"]") - isVisible.js:54:17
  at isVisible("[data-test-id="tab"][data-test-active-tab="true"] [data-test-id="tabTitle"]") - waitForVisible.js:73:22


25) navigationBar tests navigation tabnapping does not navigate to the tabnapped location:
 Error: An element could not be located on the page using the given search parameters ("[data-test-active-tab] [data-test-id="tabTitle"]").
  at elements("[data-test-active-tab] [data-test-id="tabTitle"]") - getText.js:18:17
  at window("CDwindow-2be62060-ff90-4a69-9f8d-00cc6710b75c") - brave.js:248:27
  at url() - getUrl.js:30:28
  at getUrl() - brave.js:976:4

26) navigationBar tests favicon Parses favicon when one is present:
 An element could not be located on the page using the given search parameters ("[data-test-active-tab] [data-test-favicon]").
Error

28) navigationBar tests themeColor Uses the default tab color when one is not specified:
 An element could not be located on the page using the given search parameters ("[data-test-active-tab]").
Error

30) siteInfo component tests siteInfo warning on phishing URLs shows siteInfo once when switching to a new tab:
 Error: element ("[data-test-active-tab][data-frame-key="2"]") still not existing after 10000ms
  at elements("[data-test-active-tab][data-frame-key="2"]") - isExisting.js:46:17
  at isExisting("[data-test-active-tab][data-frame-key="2"]") - waitForExist.js:67:22

31) urlBarSuggestions "before each" hook for "does not show Brave default sites":
 Error: element ("[data-test-active-tab][data-frame-key="2"]") still not existing after 10000ms
  at elements("[data-test-active-tab][data-frame-key="2"]") - isExisting.js:46:17
  at isExisting("[data-test-active-tab][data-frame-key="2"]") - waitForExist.js:67:22

33) pinnedTabs Pins an existing frame creates when signaled:
 element ("[data-test-pinned-tab][data-frame-key="2"]") still not existing after 10000ms
Error

34) pinnedTabs Pins an existing frame unpins and creates a non-pinned tab:
 Error: element ("[data-test-pinned-tab="false"][data-frame-key="2"]") still not existing after 10000ms
  at elements("[data-test-pinned-tab="false"][data-frame-key="2"]") - isExisting.js:46:17
  at isExisting("[data-test-pinned-tab="false"][data-frame-key="2"]") - waitForExist.js:67:22

36) tab pages basic tab page functionality shows no tab pages when you have only 1 page:
 Error: An element could not be located on the page using the given search parameters.
  at element("[data-test-active-tab]") - handleMouseButtonCommand.js:29:17

37) tab pages basic tab page functionality focuses active tab's page when closing last tab on page:
 element ("[data-test-active-tab]") still not visible after 10000ms
Error

41) tab tests back forward actions sets correct title:
 Error: element ("[data-test-active-tab] [data-test-id="tabTitle"]") still not visible after 10000ms
  at elements("[data-test-active-tab] [data-test-id="tabTitle"]") - isVisible.js:54:17
  at isVisible("[data-test-active-tab] [data-test-id="tabTitle"]") - waitForVisible.js:73:22

42) tab tests back forward actions middle click opens in the new tab:
 Error: element ("[data-test-active-tab] [data-test-id="tabTitle"]") still not visible after 10000ms
  at elements("[data-test-active-tab] [data-test-id="tabTitle"]") - isVisible.js:54:17
  at isVisible("[data-test-active-tab] [data-test-id="tabTitle"]") - waitForVisible.js:73:22

43) tab tests new private tab signal creates a new private tab:
 element ("[data-test-private-tab][data-frame-key="2"]") still not existing after 10000ms
Error

44) tab tests close tab can close a normal tab:
 Error: element ("[data-test-active-tab][data-frame-key="1"]") still not existing after 10000ms
  at elements("[data-test-active-tab][data-frame-key="1"]") - isExisting.js:46:17
  at isExisting("[data-test-active-tab][data-frame-key="1"]") - waitForExist.js:67:22

45) tab tests close tab should undo last closed tab:
 Error: element ("[data-test-active-tab][data-frame-key="1"]") still not existing after 10000ms
  at elements("[data-test-active-tab][data-frame-key="1"]") - isExisting.js:46:17
  at isExisting("[data-test-active-tab][data-frame-key="1"]") - waitForExist.js:67:22

46) tab tests sequentially closing tabs fallsback to last active tab if next tab does not exist:
 element ("[data-test-active-tab="true"][data-frame-key="2"]") still not visible after 10000ms
Error

47) tab tests webview previews when tab is hovered does not show preview in the active tab:
 Error: element ("[data-test-active-tab][data-frame-key="1"]") still not existing after 10000ms
  at elements("[data-test-active-tab][data-frame-key="1"]") - isExisting.js:46:17
  at isExisting("[data-test-active-tab][data-frame-key="1"]") - waitForExist.js:67:22

48) tab tests tabs with icons shows tab's icon when page is not about:blank or about:newtab :
 element ("[data-test-active-tab] [data-test-favicon]") still not existing after 10000ms
Error

49) tab tests tabs with icons unloaded tabs should display the specified favicon:
 element ("[data-frame-key="2"] [data-test-favicon="http://localhost:25481/img/test.ico"]") still not existing after 10000ms
Error

50) tab tests webview in fullscreen mode keep favicon and title after exiting fullscreen mode:
 Error: An element could not be located on the page using the given search parameters.
  at element("[data-test-active-tab]") - moveToObject.js:47:17
  at window("CDwindow-d3228958-60d2-430d-9329-e133d8bb4792") - brave.js:248:27
  at url() - getUrl.js:30:28
  at getUrl() - brave.js:976:4

51) tabUIState unit tests showTabEndIcon returns false for regular tabs:

  AssertionError [ERR_ASSERTION]: true == false
  + expected - actual

  -true
  +false
  
  at Context.<anonymous> (test/unit/app/common/state/tabUIStateTest.js:167:14)
  at Generator.next (<anonymous>)
  at onFulfilled (node_modules/co/index.js:65:19)
  at node_modules/co/index.js:54:5
  at Promise (<anonymous>)
  at Context.co (node_modules/co/index.js:50:10)
  at Context.createPromise (node_modules/co/index.js:30:15)
  at Test.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)

52) tabUIState unit tests showTabEndIcon returns false for regular tabs:

  AssertionError [ERR_ASSERTION]: true == false
  + expected - actual

  -true
  +false
  
  at Context.<anonymous> (test/unit/app/common/state/tabUIStateTest.js:176:14)
  at Generator.next (<anonymous>)
  at onFulfilled (node_modules/co/index.js:65:19)
  at node_modules/co/index.js:54:5
  at Promise (<anonymous>)
  at Context.co (node_modules/co/index.js:50:10)
  at Context.createPromise (node_modules/co/index.js:30:15)
  at Test.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)
````

### Steps to Reproduce

  1. npm run test
  2.
  3.

**Actual result:**

See above.

**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]

Consistently.

**Comment by luixxiul** [comment]
@cezaraugusto would you mind checking out the issues? thanks!

**Comment by cezaraugusto** [comment]
missed this. tab-related done w/ ce69551 and favicon/UI-related done w/ above commit 9fcf974

**Comment by luixxiul** [comment]
would you please cherry-pick them to `0.20.x` where #10691 was merged too?

**Comment by luixxiul** [comment]
@cezaraugusto still one test is failing: https://travis-ci.org/brave/browser-laptop/jobs/279713444#L3734

````
waitForElementCount("[data-test-id="tabPage"]", 2)
waitForElementCount("[data-test-id="tabPage"]", 2) => 2
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20)
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
waitForElementCount("[data-test-id="tabs"] [data-test-id="tab"]", 20) => 1
      1) hovering over a tab page changes it
waitForBrowserWindow()
````

**Comment by cezaraugusto** [comment]
@luixxiul thanks for reminding, done w/ a0adb61dd26344cf57361551ec983709c5f60e04 and 013059c79129609aadc9d0f284bd51625112b680
