### ISSUE TITLE
Interacting with phantom tab can crash browser

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#11183]
### Description
See https://github.com/brave/browser-laptop/issues/11070 for an overview of the phantom tab issue (which seems to have been introduced with 0.19.7)

#### cause phantom tab
1. Go to `about:preferences#tabs`
2. Turn on `Switch to new tabs immediately`
3. Go to any sites in new tab
4. Middle click on any links on the page
5. Go back to the tab in step 3
6. Middle click on any links on the page
#### interact with it (part 1)
7. Right click phantom tab to open context menu
8. Notice that the UI doesn't respond anymore (typing in URL bar, hitting enter, etc)
9. Open browser dev tools via Shift + F8 to see errors
#### interact with it (part 2)
7. Drag phantom tab
8. Error is logged to command line (if you launched via command line)

**Actual result:**
When right clicking (part 1)
![screen shot 2017-09-27 at 11 59 25 am](https://user-images.githubusercontent.com/4733304/30932140-79531cd2-a37b-11e7-8a66-9db171f4d211.png)
When dragging (part 2)
```
TypeError: Cannot read property 'delete' of null
    at frameOptsFromFrame (/Users/clifton/Documents/browser-laptop/js/state/frameStateUtil.js:315:6)
    at tabsReducer (/Users/clifton/Documents/browser-laptop/app/browser/reducers/tabsReducer.js:353:25)
    at reducers.reduce (/Users/clifton/Documents/browser-laptop/js/stores/appStore.js:384:24)
    at Array.reduce (<anonymous>)
    at applyReducers (/Users/clifton/Documents/browser-laptop/js/stores/appStore.js:382:68)
    at handleAppAction (/Users/clifton/Documents/browser-laptop/js/stores/appStore.js:428:14)
    at callbacks.forEach (/Users/clifton/Documents/browser-laptop/js/dispatcher/appDispatcher.js:107:7)
    at Array.forEach (<anonymous>)
    at AppDispatcher.dispatchToOwnRegisteredCallbacks (/Users/clifton/Documents/browser-laptop/js/dispatcher/appDispatcher.js:106:20)
    at AppDispatcher.dispatchInternal (/Users/clifton/Documents/browser-laptop/js/dispatcher/appDispatcher.js:132:10)
```

**Expected result:**
not crashing

**Reproduces how often:** 100%

### Brave Version
Brave: 0.19.20 
rev: d9566ab3cab788c5157a9d281de5201afe27e47e 
Muon: 4.4.25 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64

**Reproducible on current live release:**
No

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/11185

**Comment by srirambv** [comment]
Happened once on 0.19.23 but could have been a corrupt profile. Not able to reproduce on  a new profile/upgrade from 0.19.23

**Comment by bsclifton** [comment]
@srirambv you had a crash happen? If so, can you please screenshot?

The issue tracking the root cause itself (phantom tab) is https://github.com/brave/browser-laptop/issues/11070 (which is not yet in a build).

I'll close this issue as it seems this crash issue was mixed up with the actual issue itself
