### ISSUE TITLE
Cannot find module '../../app/browser/reducers/ledgerReducer & Cannot find module './stores/appStore'

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#11283]
### Description

While testing/verifying some issues that were not related to the ledger, I received the following error messages in the console when I launched Brave (even though payments are disabled):

```
An uncaught exception occurred in the main process Uncaught Exception:
Error: Cannot find module '../../app/browser/reducers/ledgerReducer'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Applications/Brave.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at handleAppAction (/Applications/Brave.app/Contents/Resources/app.asar/js/stores/appStore.js:390:25)
    at callbacks.forEach (/Applications/Brave.app/Contents/Resources/app.asar/js/dispatcher/appDispatcher.js:107:7)
    at Array.forEach (<anonymous>)
    at AppDispatcher.dispatchToOwnRegisteredCallbacks (/Applications/Brave.app/Contents/Resources/app.asar/js/dispatcher/appDispatcher.js:106:20)
    at AppDispatcher.dispatchInternal (/Applications/Brave.app/Contents/Resources/app.asar/js/dispatcher/appDispatcher.js:132:10)
Waiting 60 seconds for process to load
```

```
An uncaught exception occurred in the main process Uncaught Exception:
Error: Cannot find module './stores/appStore'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Applications/Brave.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at resolveValue (/Applications/Brave.app/Contents/Resources/app.asar/js/settings.js:61:9)
    at module.exports.getSetting (/Applications/Brave.app/Contents/Resources/app.asar/js/settings.js:68:19)
    at Object.module.exports.init (/Applications/Brave.app/Contents/Resources/app.asar/app/extensions.js:483:7)
    at perWindowStateLoaded (/Applications/Brave.app/Contents/Resources/app.asar/app/index.js:180:16)
    at Immediate.setImmediate (/Applications/Brave.app/Contents/Resources/app.asar/app/index.js:170:24)
Waiting 60 seconds for process to load
```

### Steps to Reproduce

Unfortunately I don't really have any good STR as this happened when I re-launched Brave. I tried reproducing a few times without any luck. I figured I would post this incase it might yield useful information for @NejcZdovc from the above two exceptions.

### Brave Version

**about:brave info:**

> Brave: 0.19.28 
> rev: 08781a596c1a0a461c8863692e4be51ebb3babf2 
> Muon: 4.4.25 
> libchromiumcontent: 61.0.3163.100 
> V8: 6.1.534.41 
> Node.js: 7.9.0 
> Update Channel: Beta 
> OS Platform: macOS 
> OS Release: 16.7.0 
> OS Architecture: x6

### Additional Information

<img width="1031" alt="screen shot 2017-10-05 at 1 25 57 am" src="https://user-images.githubusercontent.com/2602313/31212086-41e5b88a-a96c-11e7-8bf9-189de77b936e.png">

**Comment by kjozwiak** [comment]
I'm not sure if this makes a difference or helps, but used the following command to launch brave:

`/Applications/Brave.app/Contents/MacOS/Brave --console-log`

**Comment by NejcZdovc** [comment]
I think this is the same one as #10494

**Comment by kjozwiak** [comment]
> I think this is the same one as #10494

Definitely a dupe of #10494, looks like the same stack.... I must have had another process running when I launched Brave.
