### ISSUE TITLE
Browser crashes with "Cannot read property 'get' of undefined"

### ISSUE THREAD

**Issue by rafid059** [brave/browser-laptop#11399]
### Description

I upgraded brave to the latest release on Fedora 24 as described here: https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md#fedora-x86_64

After the update:

* there was no 'new tab' already opened after starting the browser (img3)
* The 'plus' sign doesn't open any new tabs. (img3)
* The address bar is invisible too.
* The help dropdown opens but that's it. Selecting any of the options like 'settings' or 'downloads' doesn't open any tabs. (img2)
* Tried the keyboard shortcuts to open new tabs or the downloads tab, but that doesn't work either.
* Bookmarks toolbar is there, and the bookmark folder dropdown works too BUT selecting a bookmarked page doesn't open any tab. (img1)

I uninstalled and reinstalled the latest release (which is 0.18.36-1) from the repo and it's the same. Also, `brave --help` cmd crashes and opens the browser instead with all of the issues mentioned above. Here's the following error that the cmd spits out:

```
$ brave --help
Error: unrecognized flag --icu_case_mapping
Try --help for options
Crash reporting enabled
Could not access master password; aborting
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'get' of undefined
    at migrate (/usr/share/brave/resources/app.asar/app/browser/reducers/spellCheckerReducer.js:13:13)
    at spellCheckerReducer (/usr/share/brave/resources/app.asar/app/browser/reducers/spellCheckerReducer.js:35:15)
    at reducers.reduce (/usr/share/brave/resources/app.asar/js/stores/appStore.js:382:24)
    at Array.reduce (<anonymous>)
    at applyReducers (/usr/share/brave/resources/app.asar/js/stores/appStore.js:380:68)
    at handleAppAction (/usr/share/brave/resources/app.asar/js/stores/appStore.js:424:14)
    at callbacks.forEach (/usr/share/brave/resources/app.asar/js/dispatcher/appDispatcher.js:97:7)
    at Array.forEach (<anonymous>)
    at AppDispatcher.dispatchToOwnRegisteredCallbacks (/usr/share/brave/resources/app.asar/js/dispatcher/appDispatcher.js:96:20)
    at AppDispatcher.dispatchInternal (/usr/share/brave/resources/app.asar/js/dispatcher/appDispatcher.js:122:10)
Waiting 60 seconds for process to load
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'getState' of null
    at module.exports.isResourceEnabled (/usr/share/brave/resources/app.asar/app/filtering.js:731:29)
    at Immediate.setImmediate (/usr/share/brave/resources/app.asar/app/browser/tabs.js:724:11)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

### Steps to Reproduce

  1. upgrade to 0.18.36-1
  2. open the browser
  3. voila! it doesn't work anymore

OR

  1. install latest brave release (0.18.36-1)
  2. open the browser

**Actual result:**

**img1**:
![b3](https://user-images.githubusercontent.com/6932350/31348858-c43f2436-ad42-11e7-9ade-4e66c3698447.png)

**img2**:
![b2](https://user-images.githubusercontent.com/6932350/31348860-c4499c4a-ad42-11e7-9b88-1c9d20f9c538.png)

**img3**:
![b1](https://user-images.githubusercontent.com/6932350/31348859-c445f04a-ad42-11e7-9b25-9d1d3ad32a8d.png)

**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Brave Version

**about:brave info:**

0.18.36-1

**Reproducible on current live release:**

**Comment by bbondy** [comment]
@rafid059 the latest release is actually 0.19.70
Could you try with that?
https://github.com/brave/browser-laptop/releases/tag/v0.19.70dev

**Comment by bsclifton** [comment]
@rafid059 looking at the code, this can only happen if the `session-store-1` is not loaded properly and `null` / `undefined` are passed into `appAction.setState()`
https://github.com/brave/browser-laptop/blob/d1b6b52a96e72100e40f9913f41f010c1adeba29/app/index.js#L159-L167

I'd recommend checking permissions on `~/.config/brave/session-store-1`.  If you don't yet have data, I'd recommend removing the `~/.config/brave` folder and re-installing

**Comment by rafid059** [comment]
@bbondy at the time of creating this issue, 0.18.36 was the latest version in brave's remote repository or at least that's what I found.

@bsclifton I deleted `~/.config/brave` in its entirety and restarted the browser. It seems to have fixed the problem. Thank you for the solution!

**Comment by bbondy** [comment]
OK Thanks @rafid059 
I think even if it's not loaded properly it can't be undefined so I think something was wrong in that older version.  I'm going to close this unless another report comes in.
