### ISSUE TITLE
ledger wallet keeps loading due to err 500

### ISSUE THREAD

**Issue by cezaraugusto** [brave/browser-laptop#11397]
```
properties error: Error: Ledger client initialization incomplete.
ledger client error(1): {}
Error: HTTP response 500 for POST /v2/registrar/persona/d69d6411a939b2e9b28c83542de628a
    at request.request (/Users/cezaraugusto/dev/browser-laptop/app/browser/api/ledger.js:1487:9)
    at Function.defaultSession.webRequest.fetch (/Users/cezaraugusto/dev/browser-laptop/js/lib/request.js:55:5)
```

STR:

1. Clear ledger data
2. Go to payments tab
3. Try creating a wallet

cc @mrose17 @evq

**Comment by cezaraugusto** [comment]
Marshall said this was an issue w/ rate limit but fixed now and I confirm it is, so closing.

**Comment by luixxiul** [comment]
confirmed it's fixed.
