### ISSUE TITLE
"add-simulated-synopsis-visits" failing due to missing ledger-synopsis.json

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#11429]
### Description

Running `npm run add-simulated-synopsis-visits 100` under the `0.19.x` branch will produce the following error (this is working under the latest `0.18.x`):

```
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/Users/kjozwiak/Library/Application Support/brave-development/ledger-synopsis.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at updateExistingSynopsisFile (/Users/kjozwiak/projects/browser-laptop/tools/lib/synopsisHelpers.js:26:45)
    at addSimulatedSynopsisVisits (/Users/kjozwiak/projects/browser-laptop/tools/lib/utilApp/index.js:47:3)
    at App.app.on (/Users/kjozwiak/projects/browser-laptop/tools/lib/utilApp/index.js:60:7)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
```

Looks like the script can't find the `ledger-synopsis.json`file  which I believe isn't being used anymore.

### Steps to Reproduce

  1. run `npm run add-simulated-synopsis-visits 100` within the latest `0.19.x` branch

**Actual result:**

The command fails and produces the above error.

**Expected result:**

The command should populate the ledger table with randomly generated visits.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Reproducible 100% of the time using the above STR.

### Brave Version

**about:brave info:**

```
kjozwiak@kjozwiakUbuntu:~/projects/browser-laptop$ git branch
  0.18.x
* 0.19.x
  master
```

```
kjozwiak@kjozwiakUbuntu:~/projects/browser-laptop$ git log -1
commit 987d6640812947f0fe81907a3c2cb818228b15a9
Author: Brian Clifton <brian@clifton.me>
Date:   Tue Oct 10 17:29:56 2017 -0700

    Proper update for bat-client (and deps). I didn't do a clean install before installing
```

**Comment by luixxiul** [comment]
duping to https://github.com/brave/browser-laptop/issues/11394
