### ISSUE TITLE
Null case if rates are missing

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#11455]
### Description

I just saw this problem, where rates were not defined
```
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'get' of undefined
    at Object.onWalletProperties (/Users/nejczdovc/Work/OpenSource/browser-laptop/app/browser/api/ledger.js:1694:24)
    at ledgerReducer (/Users/nejczdovc/Work/OpenSource/browser-laptop/app/browser/reducers/ledgerReducer.js:251:27)
    at reducers.reduce (/Users/nejczdovc/Work/OpenSource/browser-laptop/js/stores/appStore.js:169:24)
    at Array.reduce (<anonymous>)
    at applyReducers (/Users/nejczdovc/Work/OpenSource/browser-laptop/js/stores/appStore.js:167:68)
    at handleAppAction (/Users/nejczdovc/Work/OpenSource/browser-laptop/js/stores/appStore.js:230:16)
    at callbacks.forEach (/Users/nejczdovc/Work/OpenSource/browser-laptop/js/dispatcher/appDispatcher.js:107:7)
    at Array.forEach (<anonymous>)
    at AppDispatcher.dispatchToOwnRegisteredCallbacks (/Users/nejczdovc/Work/OpenSource/browser-laptop/js/dispatcher/appDispatcher.js:106:20)
    at AppDispatcher.dispatchInternal (/Users/nejczdovc/Work/OpenSource/browser-laptop/js/dispatcher/appDispatcher.js:132:10)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'get' of undefined
    at Object.onWalletProperties (/Users/nejczdovc/Work/OpenSource/browser-laptop/app/browser/api/ledger.js:1694:24)
    at ledgerReducer (/Users/nejczdovc/Work/OpenSource/browser-laptop/app/browser/reducers/ledgerReducer.js:251:27)
    at reducers.reduce (/Users/nejczdovc/Work/OpenSource/browser-laptop/js/stores/appStore.js:169:24)
    at Array.reduce (<anonymous>)
    at applyReducers (/Users/nejczdovc/Work/OpenSource/browser-laptop/js/stores/appStore.js:167:68)
    at handleAppAction (/Users/nejczdovc/Work/OpenSource/browser-laptop/js/stores/appStore.js:230:16)
    at callbacks.forEach (/Users/nejczdovc/Work/OpenSource/browser-laptop/js/dispatcher/appDispatcher.js:107:7)
    at Array.forEach (<anonymous>)
    at AppDispatcher.dispatchToOwnRegisteredCallbacks (/Users/nejczdovc/Work/OpenSource/browser-laptop/js/dispatcher/appDispatcher.js:106:20)
    at AppDispatcher.dispatchInternal (/Users/nejczdovc/Work/OpenSource/browser-laptop/js/dispatcher/appDispatcher.js:132:10)
    at async.cargo (/Users/nejczdovc/Work/OpenSource/browser-laptop/js/dispatcher/appDispatcher.js:213:19)
    at process (/Users/nejczdovc/Work/OpenSource/browser-laptop/node_modules/async/dist/async.js:2317:17)
    at Immediate.<anonymous> (/Users/nejczdovc/Work/OpenSource/browser-laptop/node_modules/async/dist/async.js:66:16)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
^Cprocess exited with code null
```
I don't have STR, but did add null check in the code

**Comment by kjozwiak** [comment]
@NejcZdovc is there anything QA can do here without any STR? I've added `QA/no-qa-needed` but please let me know if this can be tested/checked.

**Comment by NejcZdovc** [comment]
no, sadly I don't have STR, just saw it once and added null check just to be sure
