### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by catb0t** [brave/browser-laptop#1149]
Following the directions in the README:

```
$ npm install
<ok>
$ cd ./node_modules/abp-filter-parser-cpp ; npm install; cd ../..
<ok>
$ npm run watch &disown
> brave@0.8.2 watch /home/cat/Downloads/misc/browser-laptop
> webpack-dev-server --inline --hot --colors --content-base=./app/
http://localhost:8080/
webpack result is served from http://localhost:8080/gen/
content is served from /home/cat/Downloads/misc/browser-laptop/app
$ npm start
> brave@0.8.2 start /home/cat/Downloads/misc/browser-laptop
> node ./tools/start.js --debug=5858 -enable-logging --v=0 --enable-dcheck
electron "/home/cat/Downloads/misc/browser-laptop" --debug=5858
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:362:9)
    at Object.<anonymous> (/home/cat/Downloads/misc/browser-laptop/node_modules/electron-prebuilt/cli.js:7:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
```
The `npm run watch` command appears to work, but `npm start` exits immediately.
How can I fix this?

**Comment by luixxiul** [comment]
Still persists? Please try again following the latest instruction in the README.

**Comment by luixxiul** [comment]
This should be fixed for now, closing.
