### ISSUE TITLE
Automated tests "sessionStore test window position and size are restored correctly" are failing

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11508]
### Description

Automated tests "sessionStore test window position and size are restored correctly" are failing.

````
7) sessionStore test window position and size are restored correctly brave starts with windows from last time:
      AssertionError: expected 1023 to deeply equal 600
      + expected - actual
      -1023
      +600
      
      at Assertion.assertEqual (node_modules/chai/lib/chai/core/assertions.js:485:19)
      at Assertion.ctx.(anonymous function) (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at Object.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:308:26)
      at Object.exec (node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
      at Object.resolve (node_modules/webdriverio/build/lib/webdriverio.js:189:29)
      at node_modules/webdriverio/build/lib/webdriverio.js:538:32
      at _fulfilled (node_modules/q/q.js:854:54)
      at self.promiseDispatch.done (node_modules/q/q.js:883:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:816:13)
      at node_modules/q/q.js:624:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickDomainCallback (internal/process/next_tick.js:128:9)

  8) sessionStore test window position and size are restored correctly brave starts with home page:
      AssertionError: expected 1023 to deeply equal 600
      + expected - actual
      -1023
      +600
      
      at Assertion.assertEqual (node_modules/chai/lib/chai/core/assertions.js:485:19)
      at Assertion.ctx.(anonymous function) (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at Object.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:308:26)
      at Object.exec (node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
      at Object.resolve (node_modules/webdriverio/build/lib/webdriverio.js:189:29)
      at node_modules/webdriverio/build/lib/webdriverio.js:538:32
      at _fulfilled (node_modules/q/q.js:854:54)
      at self.promiseDispatch.done (node_modules/q/q.js:883:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:816:13)
      at node_modules/q/q.js:624:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickDomainCallback (internal/process/next_tick.js:128:9)

  9) sessionStore test window position and size are restored correctly brave starts with new tab page:
      AssertionError: expected 1023 to deeply equal 600
      + expected - actual
      -1023
      +600
      
      at Assertion.assertEqual (node_modules/chai/lib/chai/core/assertions.js:485:19)
      at Assertion.ctx.(anonymous function) (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
      at Object.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:308:26)
      at Object.exec (node_modules/webdriverio/build/lib/helpers/safeExecute.js:28:24)
      at Object.resolve (node_modules/webdriverio/build/lib/webdriverio.js:189:29)
      at node_modules/webdriverio/build/lib/webdriverio.js:538:32
      at _fulfilled (node_modules/q/q.js:854:54)
      at self.promiseDispatch.done (node_modules/q/q.js:883:30)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:816:13)
      at node_modules/q/q.js:624:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickDomainCallback (internal/process/next_tick.js:128:9)
````

It looks like these are failing since `use new crash reporter api`
- https://travis-ci.org/brave/browser-laptop/jobs/287361373#L3831 (on `master`)
- https://travis-ci.org/brave/browser-laptop/jobs/287361846#L3832 (on `0.21.x`)
- https://travis-ci.org/brave/browser-laptop/jobs/287361932#L3857 (on `0.20.x`)

It also fails on:

- https://travis-ci.org/brave/browser-laptop/jobs/287563508#L3860
- https://travis-ci.org/brave/browser-laptop/jobs/287564545#L3847

Those do not fail by restarting these jobs, so those issues do not seem to be related with NPM package minor / patch updates. See these links for the logs:

https://travis-ci.org/brave/browser-laptop/jobs/287194616#L3581
https://travis-ci.org/brave/browser-laptop/jobs/287029044#L3603

### Additional Information

https://github.com/brave/browser-laptop/pull/11239 (add 10 seconds pause to make sure the browser process was successfully closed) would have helped us to notify those issue.

**Comment by luixxiul** [comment]
Adding the milestone just in case https://github.com/brave/browser-laptop/issues/11499 would be a cause of the issue.

**Comment by luixxiul** [comment]
Here is a list of the jobs where the seesion tests are failing or not:

[#15682.4](https://travis-ci.org/brave/browser-laptop/jobs/287194175) - not failing (on 0.19.x)
[#15683.5](https://travis-ci.org/brave/browser-laptop/jobs/287194616) - not failing (on master)
[#15684.5](https://travis-ci.org/brave/browser-laptop/jobs/287194697#L3604) - not failing 
[#15685.5](https://travis-ci.org/brave/browser-laptop/jobs/287217155#L3563) - not failing (on master)

On `use new crash reporter api`:
[#15692.5](https://travis-ci.org/brave/browser-laptop/jobs/287361373#L3831) - failing (on master)
[#15693.5](https://travis-ci.org/brave/browser-laptop/jobs/287361846#L3832) - failing (on 0.21.x)
[#15694.5](https://travis-ci.org/brave/browser-laptop/jobs/287361932#L3857) - failing (on 0.20.x)

[#15697.5](https://travis-ci.org/brave/browser-laptop/jobs/287369423#L3887) - failing (0.20.x)
[#15698.5](https://travis-ci.org/brave/browser-laptop/jobs/287370755#L3793) - failing
[#15699.5](https://travis-ci.org/brave/browser-laptop/jobs/287370892#L3806) - failing
[#15704.5](https://travis-ci.org/brave/browser-laptop/jobs/287384479#L3815) - failing

**Comment by NejcZdovc** [comment]
moving into 0.19 hotfix 2, because there is where #11499 will land
