### ISSUE TITLE
Error: Seed must be Uint8Array. when toggling payment on/off during wallet transition

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11673]
### Description
Error: Seed must be Uint8Array. when toggling payment on/off during wallet transition

### Steps to Reproduce

  1. Install 0.18.36 and enable payments
  2. Visit few sites to add in ledger table
  3. Keep payment on and close the browser
  4. Upgrade to 0.19.66
  5. Ensure transition overlay is shown when upgraded
  6. Toggle payment switch on/off 4-5 times, console shows 503 error with exception for Uint8Array, Wallet doesn't get converted

**Actual result:**
```
An uncaught exception occurred in the main process Uncaught Exception:
Error: Seed must be Uint8Array.
    at Object.module.exports.deriveSigningKeysFromSeed (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\brave-crypto\index.js:116:11)
    at Client.getKeypair (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:472:24)
    at Client.generateKeypair (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:466:15)
    at Object.callback (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:669:24)
    at Worker.worker.onmessage (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:1276:11)
    at App.app.on (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\electron.asar\browser\api\app.js:112:34)
    at emitThree (events.js:121:20)
    at App.emit (events.js:197:7)
[1025/211617.827:ERROR:process_info.cc(632)] range at 0x64c049cc00000000, size 0x1a9 fully unreadable
[1025/211617.827:ERROR:process_info.cc(632)] range at 0x64c049ec00000000, size 0x1a9 fully unreadable
[1025/211617.828:ERROR:process_info.cc(632)] range at 0x0, size 0x1a9 fully unreadable
ledger client error(3): {}
Error: HTTP response 503 for GET /v2/registrar/persona
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1533:9)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
An uncaught exception occurred in the main process Uncaught Exception:
Error: Seed must be Uint8Array.
    at Object.module.exports.deriveSigningKeysFromSeed (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\brave-crypto\index.js:116:11)
    at Client.getKeypair (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:472:24)
    at Client.generateKeypair (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:466:15)
    at Object.callback (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:669:24)
    at Worker.worker.onmessage (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:1276:11)
    at App.app.on (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\electron.asar\browser\api\app.js:112:34)
    at emitThree (events.js:121:20)
    at App.emit (events.js:197:7)
```

**Expected result:**
No error, wallet conversion should happen successfully

**Reproduces how often:** [What percentage of the time does it reproduce?]
Found while trying to reproduce #11671 

### Brave Version

**about:brave info:**

Brave | 0.19.66
-- | --
rev | 148f5b0
Muon | 4.5.9

**Reproducible on current live release:**

**Comment by NejcZdovc** [comment]
as far as I can see this happens in `bat-client`, so will assign it to @evq

**Comment by evq** [comment]
browser-laptop is doing fixup on bat-client state to sure the seed passed during init is a Uint8Array, however it isn't doing it for `newClient`. I added a workaround in `bat-client` so upgrading to `1.0.14` should resolve this.

**Comment by srirambv** [comment]
Works fine. No seed error shown. however toggling the on/off switch does cause #11705 consistently.
