### ISSUE TITLE
ledger client transition error:  SyntaxError: Unexpected token # in JSON at position 0

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11671]
### Description
JSON error when payment is toggled

### Steps to Reproduce

  1. Install 0.18.36
  2. Enable payment, visit sites to add in ledger table, disable payments
  3. Update to 0.19.66
  4. Launch from console, enable payments, 
  5. Wait for the transition to complete, ensure ledger table from step 2 is shown
  6. Toggle on/off switch 5-6 times
  7. Visit a new site in a new tab, wait on the page for 10 secs
  8. Go back to preferences, transition overlay is shown again and stuck for ever

**Actual result:**
```
$ An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined
[1025/183718.628:ERROR:process_info.cc(632)] range at 0x96d649cc00000000, size 0x283 fully unreadable
[1025/183718.628:ERROR:process_info.cc(632)] range at 0x96d649ec00000000, size 0x283 fully unreadable
[1025/183718.628:ERROR:process_info.cc(632)] range at 0x0, size 0x283 fully unreadable
Waiting 60 seconds for process to load
Error: unrecognized flag --icu_case_mapping
Try --help for options
[2720:1372:1025/183723.595:ERROR:CONSOLE(51976)] "(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit.", source: chrome://brave/C:/Users/Sriram%20BV/AppData/Local/brave/app-0.19.66/resources/app.asar/app/extensions/brave/gen/app.entry.js (51976)
[2720:1372:1025/183723.595:ERROR:CONSOLE(51976)] "(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit.", source: chrome://brave/C:/Users/Sriram%20BV/AppData/Local/brave/app-0.19.66/resources/app.asar/app/extensions/brave/gen/app.entry.js (51976)
[2720:6284:1025/183725.951:ERROR:shader_disk_cache.cc(238)] Failed to create shader cache entry: -2
Error: ENOENT: no such file or directory, access 'C:\Users\Sriram BV\AppData\Roaming\brave\ledger-newstate.json'
Signature verified in registerUserFinal.
Signature verified in registerUserFinal.
(node:2720) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 worker-start listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 worker-start listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:262:19)
    at App.addListener (events.js:279:10)
    at Object.app.createWorker (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\electron.asar\browser\api\app.js:98:7)
    at Client.credentialWorker (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:1267:25)
    at Client.credentialFinalize (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:1314:17)
    at C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:710:14
    at self.roundtrip (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:1154:65)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1544:7)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
(node:2720) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 worker-stop listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 worker-stop listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:262:19)
    at App.addListener (events.js:279:10)
    at Object.app.createWorker (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\electron.asar\browser\api\app.js:103:7)
    at Client.credentialWorker (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:1267:25)
    at Client.credentialFinalize (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:1314:17)
    at C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:710:14
    at self.roundtrip (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:1154:65)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1544:7)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
(node:2720) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 worker-post-message listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 worker-post-message listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:262:19)
    at App.addListener (events.js:279:10)
    at Object.app.createWorker (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\electron.asar\browser\api\app.js:108:7)
    at Client.credentialWorker (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:1267:25)
    at Client.credentialFinalize (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:1314:17)
    at C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:710:14
    at self.roundtrip (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:1154:65)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1544:7)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
(node:2720) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 worker-onerror listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 worker-onerror listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:262:19)
    at App.addListener (events.js:279:10)
    at Object.app.createWorker (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\electron.asar\browser\api\app.js:115:7)
    at Client.credentialWorker (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:1267:25)
    at Client.credentialFinalize (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:1314:17)
    at C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:710:14
    at self.roundtrip (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:1154:65)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1544:7)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
(node:2720) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 app-post-message listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 app-post-message listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:262:19)
    at App.addListener (events.js:279:10)
    at Object.app.createWorker (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\electron.asar\browser\api\app.js:121:7)
    at Client.credentialWorker (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:1267:25)
    at Client.credentialFinalize (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:1314:17)
    at C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:710:14
    at self.roundtrip (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:1154:65)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1544:7)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
Signature verified in registerUserFinal.
Signature verified in registerUserFinal.
Signature verified in registerUserFinal.
Signature verified in registerUserFinal.
Signature verified in registerUserFinal.
Signature verified in registerUserFinal.
Signature verified in registerUserFinal.
Signature verified in registerUserFinal.
Signature verified in registerUserFinal.
Signature verified in registerUserFinal.
Signature verified in registerUserFinal.
Signature verified in registerUserFinal.
ledger client error(3): {}
Error: HTTP response 422 for POST /v2/registrar/persona/f1fdbd3b79d36a28a5fb9a551014003
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1533:9)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
Signature verified in registerUserFinal.
Signature verified in registerUserFinal.
Signature verified in registerUserFinal.
Signature verified in registerUserFinal.
Signature verified in registerUserFinal.
Signature verified in registerUserFinal.
Error: ENOENT: no such file or directory, access 'C:\Users\Sriram BV\AppData\Roaming\brave\ledger-newstate.json'
Signature verified in registerUserFinal.
Signature verified in registerUserFinal.
Signature verified in registerUserFinal.
Signature verified in registerUserFinal.
ledger client transition error:  SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1538:68)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
ledger client transition error:  SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1538:68)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
Signature verified in registerUserFinal.
Signature verified in registerUserFinal.
ledger client transition error:  SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1538:68)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
ledger client transition error:  SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1538:68)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
Signature verified in registerUserFinal.
ledger client transition error:  SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1538:68)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
ledger client transition error:  SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1538:68)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
Signature verified in registerUserFinal.
ledger client transition error:  SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1538:68)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
ledger client transition error:  SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1538:68)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
ledger client transition error:  SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1538:68)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
ledger client transition error:  SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1538:68)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
ledger client transition error:  SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1538:68)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
ledger client transition error:  SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1538:68)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
ledger client transition error:  SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1538:68)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
ledger client transition error:  SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1538:68)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
ledger client transition error:  SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1538:68)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
ledger client transition error:  SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1538:68)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
ledger client transition error:  SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1538:68)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)

```
**Expected result:**
Payment should be enabled, no errors in console

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.19.66
-- | --
rev | 148f5b0
Muon | 4.5.9

**Reproducible on current live release:**
N/A

### Additional Information
Confirmed @kjozwiak saw the errors on Linux and but wasn't stuck on transition overlay the second time

**Comment by bsclifton** [comment]
Closing as this was fixed by @evq via https://github.com/brave/browser-laptop/pull/11601
