### ISSUE TITLE
TypeError: Cannot read property 'password-details-updated' of undefined

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#11690]
### Description

Sometimes Brave gets into a state where saving passwords via the notification will display the following error every time a password is saved:

```
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'password-details-updated' of undefined
    at sendAboutDetails (/usr/lib/brave/resources/app.asar/app/browser/tabs.js:190:44)
    at autofill.getAutofillableLogins (/usr/lib/brave/resources/app.asar/app/browser/tabs.js:277:7)
    at Function.session.defaultSession.autofill.getAutofillableLogins (/usr/lib/brave/resources/app.asar/app/autofill.js:74:5)

An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'password-site-details-updated' of undefined
    at sendAboutDetails (/usr/lib/brave/resources/app.asar/app/browser/tabs.js:190:44)
    at autofill.getBlackedlistLogins (/usr/lib/brave/resources/app.asar/app/browser/tabs.js:280:7)
    at Function.session.defaultSession.autofill.getBlackedlistLogins (/usr/lib/brave/resources/app.asar/app/autofill.js:80:5)
```

I've noticed this happening a few times but don't have good STR. This seems to be working with a brand new profile and sometimes gets into the above state. I created the bug just incase the above uncaught exception reveals anything useful/obvious to the devs. Even though the above error is being displayed in the console, the passwords/login seems to be working without issues.

### Steps to Reproduce

I don't have any STR as of right now... I'll try getting some tomorrow.

**Actual result:**

Brave gets into a state where it displays uncaught exceptions when saving passwords via the notification.

**Expected result:**

When saving passwords via the notification, we shouldn't be displaying any uncaught exception via the console. These errors should be resolved/fixed.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Doesn't occur often, still need STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.67 
> rev: b3a897eef1f1d8d6594e2d8e862bf7a874e86e73 
> Muon: 4.5.9 
> libchromiumcontent: 62.0.3202.62 

**Reproducible on current live release:**

Not 100% sure as I don't have reliable STR. Happens here and there so I'm not sure when this was introduced. Once we have STR, we'll check against the current release build.

### Additional Information

@srirambv @LaurenWags @luixxiul have you seen this happen before?

**Comment by srirambv** [comment]
I tried with multiple accounts on the same site trying to login but couldn't reproduce the error. Tried with update password but still couldn't repro it

**Comment by LaurenWags** [comment]
Haven't repro'd this yet.

**Comment by kjozwiak** [comment]
Saw this again while going through `0.19.120`... Here's the case that I ran through when I received exception listed below:

* log into LinkedIn and click on "Password Settings" via the password notification
* switch back to the LinkedIn tab and select "Save Password" and log out

Once I return to the LinkedIn Home page, the following was displayed in the terminal:

```
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'password-details-updated' of undefined
    at sendAboutDetails (/usr/lib/brave/resources/app.asar/app/browser/tabs.js:202:44)
    at autofill.getAutofillableLogins (/usr/lib/brave/resources/app.asar/app/browser/tabs.js:294:7)
    at Function.session.defaultSession.autofill.getAutofillableLogins (/usr/lib/brave/resources/app.asar/app/autofill.js:74:5)

An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'password-site-details-updated' of undefined
    at sendAboutDetails (/usr/lib/brave/resources/app.asar/app/browser/tabs.js:202:44)
    at autofill.getBlackedlistLogins (/usr/lib/brave/resources/app.asar/app/browser/tabs.js:297:7)
    at Function.session.defaultSession.autofill.getBlackedlistLogins (/usr/lib/brave/resources/app.asar/app/autofill.js:80:5)
```

Unfortunately I can't seem to get STR as this happens here and there.. I've only seen it a handful of times.

**Comment by srirambv** [comment]
Repro'd this but not sure if the steps are correct. This is what I did to see the error on console

1. Login to GitHub
2. Save the credentials
3. Logout from GitHub
4. Switch to another tab
5. Switch back to GitHub tab 
6. Click signin ensure autofill popdown shows up
7. Clear the selection
8. Click on the input field again to bring the login pop down
9. Login and then logout again wait for 2 mins console throws the error

Was able to reproduce the issue only once but that's exactly what I did
