### ISSUE TITLE
MaxListenersExceededWarning when wallet transition happens

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11705]
### Description
MaxListenersExceededWarning when wallet transition happens

### Steps to Reproduce

1. Install 0.18.36 and enable payments via about:preferences#payments
2. Visit several websites and ensure they're appearing under the ledger table
3. disable payments via the "On/Off" switch under about:preferences#payments
4. Install 0.19.67, while transition happens, toggle payments on/off
5. Console shows Maxlistener errors

**Actual result:**
```
(node:10220) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 app-post-message listeners added. Use emitter.setMaxListeners() to increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 app-post-message listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:262:19)
    at App.addListener (events.js:279:10)
    at Object.app.createWorker (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\electron.asar\browser\api\app.js:121:7)
    at Client.credentialWorker (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:1267:25)
    at Client.credentialRequest (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:1304:46)
    at C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:661:10
    at self.roundtrip (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\node_modules\bat-client\index.js:1154:65)
    at request.request (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\app\browser\api\ledger.js:1544:7)
    at Function.defaultSession.webRequest.fetch (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.66\resources\app.asar\js\lib\request.js:55:5)
```
**Expected result:**
Should not show any error

**Reproduces how often:** [What percentage of the time does it reproduce?]
Consistently, Reproduce on Linux by @kjozwiak 

### Brave Version

**about:brave info:**

Brave | 0.19.67
-- | --
rev | b3a897e
Muon | 4.5.9

**Reproducible on current live release:**
N/A

**Comment by bsclifton** [comment]
This is an interesting one (seeing the call-stack).  I don't think this is a problem- however, if this really is not a problem, it would be nice to suppress the logs

cc: @bridiver, @bbondy

**Comment by NejcZdovc** [comment]
Closing as we don't have a lot of users in transition anymore and I think it's not a problem
