### ISSUE TITLE
Package gnome-keyring-1 was not found

### ISSUE THREAD

**Issue by rahilwazir** [brave/browser-laptop#1172]
I'm getting the same build error as on [travis-ci](https://travis-ci.org/brave/browser-laptop#L3980)

When running `npm start`:

```
> brave@0.8.2 start /home/rw/brrrrr/brave
> node ./tools/start.js --debug=5858 -enable-logging --v=0 --enable-dcheck

electron "/home/brrrrr/brrrrr/brave" --debug=5858
Error opening app
The app provided is not a valid Electron app, please read the docs on how to write one:
https://github.com/atom/electron/tree/vundefined/docs

Error: Cannot find module 'keytar'
```

When running `npm i`:

```
Package gnome-keyring-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gnome-keyring-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gnome-keyring-1' found
gyp: Call to 'pkg-config --libs-only-l gnome-keyring-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/brrrrr/.nvm/versions/node/v5.9.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.0-15-generic
gyp ERR! command "/home/brrrrr/.nvm/versions/node/v5.9.1/bin/node" "/home/brrrrr/.nvm/versions/node/v5.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/brrrrr/Desktop/brave/node_modules/keytar
gyp ERR! node -v v5.9.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
npm WARN optional Skipping failed optional dependency /electron-builder/appdmg:
npm WARN notsup Not compatible with your operating system or architecture: appdmg@0.3.6
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.9
npm ERR! Linux 4.4.0-15-generic
npm ERR! argv "/home/brrrrr/.nvm/versions/node/v5.9.1/bin/node" "/home/brrrrr/.nvm/versions/node/v5.9.1/bin/npm" "i"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keytar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/brrrrr/brrrr/brave/npm-debug.log
```

**Comment by bbondy** [comment]
You'll have to install the dependency: `libgnome-keyring-dev`
Was fixed in Travis here. 
https://github.com/brave/browser-laptop/commit/533cbce4c244e1cea6813fa9a2bb2b5eee26058f

Closing this, thanks for pointing out Travis being broken.

**Comment by luixxiul** [comment]
@bbondy Travis is broken for a long time. Is it not worth fixing?

**Comment by bbondy** [comment]
They fail intermittently, but not because of Package gnome-keyring-1.  We're working on improving the success rate.  Some of it very recently.

**Comment by luixxiul** [comment]
Yes, I saw them too :+1:
