### ISSUE TITLE
Moving a bookmark on the toolbar folder makes a zombie bookmark

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11798]
### Description

Moving a bookmark on the toolbar folder makes a zombie bookmark. 

### Steps to Reproduce

  1. Open about:about
  2. Bookmark the page
  3. Add a bookmark folder, naming it `Test`
  4. Drag the bookmark and drop it to `Test`
  5. Blank bookmark appears (clicking it does nothing)

Then:
  1. Open a new tab
  7. Visit https://slashdot.org
  8. Bookmark slashdot
  9. The zombie is replaced with the slashdot bookmark
  10. Drag the slashdot to `Test`
  11. Zombie again

**Actual result:**

![bug](https://user-images.githubusercontent.com/3362943/32431015-15cbf72e-c315-11e7-943c-da1698bb72f8.gif)

**Expected result:**

The blank bookmark should not appear

**Reproduces how often:**

Consistently.

### Brave Version

**about:brave info:**

Brave: 0.20.5 
V8: 6.2.414.36 
rev: 0cc4f80e759d303fa109ab427ce862d5720dd97b 
Muon: 4.5.14 
OS Release: 4.9.0-3-amd64 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 62.0.3202.75

**Reproducible on current live release:**

No.

**Comment by luixxiul** [comment]
This is the log you get when you click the zombie:

````
TypeError: Cannot read property 'trim' of undefined
    at isURL (/usr/lib/brave-beta/resources/app.asar/js/lib/urlutil.js:172:19)
    at normalizeUrl (/usr/lib/brave-beta/resources/app.asar/app/browser/tabs.js:49:7)
    at Object.loadURL (/usr/lib/brave-beta/resources/app.asar/app/browser/tabs.js:693:17)
    at Immediate.setImmediate (/usr/lib/brave-beta/resources/app.asar/app/browser/reducers/tabsReducer.js:273:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
````

**Comment by NejcZdovc** [comment]
let's retest after https://github.com/brave/browser-laptop/pull/12517 lands
