### ISSUE TITLE
Beta build doesn't launch from console

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11824]
### Description
Beta build doesn't launch from console

### Steps to Reproduce
   1. Install 0.20.6
   2. Close the browser 
   3. Launch from console, doesn't launch, same result as #11791, console shows error 

**Actual result:**
```
$ An uncaught exception occurred in the main process Uncaught Exception:
Error: Cannot find module './updater'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\Sriram BV\AppData\Local\BraveBeta\app-0.20.6\resources\electron.asar\common\reset-search-paths.js:41:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at C:\Users\Sriram BV\AppData\Local\BraveBeta\app-0.20.6\resources\app.asar\app\index.js:53:17
    at Object.<anonymous> (C:\Users\Sriram BV\AppData\Local\BraveBeta\app-0.20.6\resources\app.asar\app\index.js:356:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
[1107/145650.716:ERROR:process_info.cc(632)] range at 0x9e864b0600000000, size 0x1f3 fully unreadable
[1107/145650.716:ERROR:process_info.cc(632)] range at 0x9e864b2600000000, size 0x1f3 fully unreadable
[1107/145650.716:ERROR:process_info.cc(632)] range at 0x0, size 0x1f3 fully unreadable
Waiting 60 seconds for process to load
```

**Expected result:**
Browser should launch from console

**Reproduces how often:**
100%

### Brave Version
**about:brave info:**

Brave | 0.20.6
-- | --
V8 | 6.2.414.36
rev | 18f7d1e
Muon | 4.5.14
OS Release | 10.0.15063
Update Channel | Beta
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 62.0.3202.75

**Reproducible on current live release:**
N/A

**Comment by darkdh** [comment]
If you wanna launch non release Brave from console, make sure you specify 
`user-data-dir-name` switch.
See shortcut on start menu or desktop
`C:\Users\darkdh\AppData\Local\BraveBeta\BraveBeta.exe  -a "--user-data-dir-name=brave-beta`

**Comment by luixxiul** [comment]
Obviously it's worth for adding to README.md 😄 

I'll add that info to https://community.brave.com/c/common-issues 👍

**Comment by darkdh** [comment]
sorry, I take it back. I just recalled we have automatically adding switch functionality
https://github.com/brave/browser-laptop/blob/9fd2958bff6d07535b00d8d56c7c1bce9f23cab4/app/windowsInit.js#L81-L83

**Comment by kjozwiak** [comment]
Using `0.20.9`, ensured that the following two commands launched brave within the terminal under Ubuntu 17.10 x64:

* `brave-beta --user-data-dir-name=brave-beta`
* `brave-beta`

**Comment by kjozwiak** [comment]
Even though is marked as "Windows", double checked and ensured that you can launch brave from all three platforms via the terminal/console.
