### ISSUE TITLE
YouTube / Netflix movie freezes a couple of seconds per minutes

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11924]
### Description

There is a report that YouTube video freezes a couple of seconds.

https://community.brave.com/t/youtube-freezes-some-more-details/10635?u=suguru

> Three Brave versions ago the video playback freezes would last for half a second to two seconds.
Two Braves ago the freezes were dramatically reduced. Very brief freezes.
The last Brave update and the current Brave version the freezes are back to half to two seconds.
>
> I started timing the freezes on a few videos. All from the same uploader and same resolution: 720p/60fps.
> Almost like clockwork (within a few seconds) it would freeze at 1:00, 6:00, 11:00. 16:00…
> At one minute then every five minutes there after…

I notice the same thing on YouTube and Netflix as well. According to the report the issue looks similar to this one https://github.com/brave/browser-laptop/issues/10094, while on this case UI is not locked up.

### Steps to Reproduce

  1. Watch a movie on Netflix or YouTube

**Actual result:**

See above.

**Expected result:**

The movie should not freeze.

**Reproduces how often:**

Consistently.

### Brave Version

**about:brave info:**

 
Brave: 0.19.88 
rev: c29eca63249e3d43584ca1dcc47f3e7a7e904324 
Muon: 4.5.15 
libchromiumcontent: 62.0.3202.89 
V8: 6.2.414.40 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.14393 
OS Architecture: x64

**Reproducible on current live release:**

Yes.

**Comment by srirambv** [comment]
Haven't seen this on YouTube.

**Comment by luixxiul** [comment]
https://community.brave.com/t/youtube-freezes-some-more-details/10635/3?u=suguru

> Further experimenting.
> 
> Same YouTube uploader as before. Same resolution 720/60.
>
> I opened five videos by clicking the links with the middle mouse button so they open in new tabs but dont start playing.
>
> First video freezes at:
> 0:28, 5:25, 10:20, 15:15. Again, first freeze, then five minutes for each one after that.
>
> The second video was interesting:
> 1:02, 5:57, 10:46… Then I got an email, so I paused the video, opened the email, clicked the link in the email which opened a new tab in brave and it caused all the other YouTube videos I had open to start playing.
>
> I paused all the other videos and kept watching the one I was on.
> … 13:50, 18:36, 23:29.
>
> Again, initial freeze, then every five minutes after that. Except for when things screwed up in the middle and time was three minutes, but then it was still every five minutes from then on.

**Comment by srirambv** [comment]
Seeing this on 0.19.91 for YouTube after playing videos for a bit.

**Comment by srirambv** [comment]
Happens but not consistently reproducible on YouTube

**Comment by srirambv** [comment]
Seeing this error on console when the video stutter 
```
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot set property 'faviconName' of undefined
    at Object.onMediaPublisher (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.91\resources\app.asar\app\browser\api\ledger.js:2290:51)
    at ledgerReducer (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.91\resources\app.asar\app\browser\reducers\ledgerReducer.js:414:27)
    at reducers.reduce (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.91\resources\app.asar\js\stores\appStore.js:383:24)
    at Array.reduce (<anonymous>)
    at applyReducers (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.91\resources\app.asar\js\stores\appStore.js:381:68)
    at handleAppAction (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.91\resources\app.asar\js\stores\appStore.js:440:16)
    at callbacks.forEach (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.91\resources\app.asar\js\dispatcher\appDispatcher.js:107:7)
    at Array.forEach (<anonymous>)
    at AppDispatcher.dispatchToOwnRegisteredCallbacks (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.91\resources\app.asar\js\dispatcher\appDispatcher.js:106:20)
    at AppDispatcher.dispatchInternal (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.91\resources\app.asar\js\dispatcher\appDispatcher.js:132:10)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
[1114/133746.382:ERROR:process_info.cc(632)] range at 0xc38c4a1c00000000, size 0x1e3 fully unreadable
[1114/133746.382:ERROR:process_info.cc(632)] range at 0xc38c4a3c00000000, size 0x1e3 fully unreadable
[1114/133746.382:ERROR:process_info.cc(632)] range at 0x0, size 0x1e3 fully unreadable
```
cc: @NejcZdovc

**Comment by kjozwiak** [comment]
Seeing the above happen a lot when I was playing videos from [Jimmy Kimmel Live](https://www.youtube.com/user/JimmyKimmelLive/videos) when going through the YT feature that's slated for `hotfix5`... Happens every 10-20 seconds.

**Comment by NejcZdovc** [comment]
@kjozwiak let's retest after new RC that have #11969 in

**Comment by srchulo** [comment]
I'm seeing this on Windows 10 on version 0.19.139. I've had videos freeze on YouTube a lot for a long time. I've switched to Edge just for YouTube.
