### ISSUE TITLE
Error: Cannot find module './babel-core' when launching 0.19.89

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11925]
### Description
Error: Cannot find module './babel-core' when launching 0.19.89

### Steps to Reproduce
  1. Upgrade to 0.19.89 via check for update/ manual install
  2. Close browser and launch from console
  3. Console shows error when browser window is launched

**Actual result:**
```
An uncaught exception occurred in the main process Uncaught Exception:
Error: Cannot find module './babel-core'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.89\resources\electron.asar\common\reset-search-paths.js:41:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at module.exports (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.89\resources\app.asar\node_modules\ast-types\def\babel.js:2:12)
    at use (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.89\resources\app.asar\node_modules\ast-types\fork.js:11:31)
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.89\resources\app.asar\node_modules\ast-types\fork.js:20:10)
    at C:\Users\Sriram BV\AppData\Local\brave\app-0.19.89\resources\app.asar\node_modules\ast-types\main.js:1:182
    at Object.<anonymous> (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.89\resources\app.asar\node_modules\ast-types\main.js:18:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Expected result:**
Should not show error

**Reproduces how often:**
Only on upgrade from older version

### Brave Version

**about:brave info:**

Brave | 0.19.89
-- | --
rev | 20badac
Muon | 4.5.15
libchromiumcontent | 62.0.3202.89
V8 | 6.2.414.40
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**
NA

### Additional Information
Issue happens only on upgrade profile not when launching a clean profile from console. Links opened in new tab doesn't close, browser window cannot be closed by clicking on the close button. Have to right click and close window from task bar

**Comment by cezaraugusto** [comment]
closing as fixed

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/commit/13e00e81ceb2007b35535109f57b5824f1f015cb#diff-eb1f8c8a44791e608fb0fbe96819221e
