### ISSUE TITLE
Unable to launch Brave on Ubuntu 16.04

### ISSUE THREAD

**Issue by kweiner** [brave/browser-laptop#12021]
### Steps to Reproduce

  1. Install Brave according to instructions on https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md
  2. Open a terminal window and issue the command: brave

**Actual result:**

Error: unrecognized flag --icu_case_mapping
Try --help for options
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot set property 'order' of null
    at oldSites.forEach (/usr/lib/brave/resources/app.asar/app/sessionStore.js:594:18)
    at List.__iterate (/usr/lib/brave/resources/app.asar/node_modules/immutable/dist/immutable.js:2206:13)
    at List.forEach (/usr/lib/brave/resources/app.asar/node_modules/immutable/dist/immutable.js:4381:19)
    at Object.module.exports.runPostMigrations (/usr/lib/brave/resources/app.asar/app/sessionStore.js:592:14)
    at Promise (/usr/lib/brave/resources/app.asar/app/sessionStore.js:723:38)
    at new Promise (<anonymous>)
    at Object.module.exports.loadAppState (/usr/lib/brave/resources/app.asar/app/sessionStore.js:669:10)
    at /usr/lib/brave/resources/app.asar/app/index.js:96:40
    at Object.<anonymous> (/usr/lib/brave/resources/app.asar/app/index.js:343:2)
    at Module._compile (module.js:571:32)
Waiting 60 seconds for process to load

**Expected result:**
I expected the Brave browser to start up.

**Reproduces how often:**

100% of the time

### Brave Version

**about:brave info:**

I can't open Brave so I don't know which exact version it is, however the Ubuntu Software Center shows me this version: brave 0.19.95-1

**Reproducible on current live release:**

### Additional Information

This is the output of lse_release -a:

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by KarateCowboy** [comment]
Hi @kweiner 

I am also running Ubuntu Xenial. I had a similar problem running from the command line, but not using the graphical launcher. As a workaround, you can create a launch script that mimics the graphical launchers.

Drop this into a text file name `launchbrave` 

```
#!/bin/sh
brave --user-data-dir-name=brave -- %U
```

Then:
```
chmod 755 launchbrave
sudo mv launchbrave /usr/local/bin
```

And now `launchbrave` should work from the cmd.

**Comment by kweiner** [comment]
Thanks @KarateCowboy, but I was able to get Brave working by uninstalling it and re-installing as a snap package.  The only tricky thing was that the executable wasn't on the path by default.

**Comment by KarateCowboy** [comment]
Sounds good, @kweiner . Still, the regular install should be launchable from the cmd-line. Looks like they'll be addressing that.

**Comment by bsclifton** [comment]
This should be fixed now- I'm going to close the issue.  Let's re-open if the issue still occurs 😄  Thanks!
