### ISSUE TITLE
Context Menu is not displayed due to error on rpc-server.js

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#12175]
### Description

Context Menu is not displayed due to error on rpc-server.js.

````
[9783:9783:1205/020734.910164:ERROR:CONSOLE(219)] "Uncaught Error: Unknown type: function
TypeError: Unknown type: function
    at metaToValue (/usr/lib/brave/resources/electron.asar/browser/rpc-server.js:171:15)
    at metaToValue (/usr/lib/brave/resources/electron.asar/browser/rpc-server.js:166:30)
    at Array.map (<anonymous>)
    at unwrapArgs (/usr/lib/brave/resources/electron.asar/browser/rpc-server.js:174:15)
    at metaToValue (/usr/lib/brave/resources/electron.asar/browser/rpc-server.js:150:16)
    at Array.map (<anonymous>)
    at unwrapArgs (/usr/lib/brave/resources/electron.asar/browser/rpc-server.js:174:15)
    at EventEmitter.<anonymous> (/usr/lib/brave/resources/electron.asar/browser/rpc-server.js:282:12)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)", source: extensions::remote (219)
````

### Steps to Reproduce

  1. Open https://github.com
  2. Click anywhere with a right mouse button to display the context menu
  3.

**Actual result:**

The context menu is not displayed due to the error above.

**Expected result:**

It should be displayed.

**Reproduces how often:**

Consistently

### Brave Version

**about:brave info:**

````
Brave: 0.19.106 
rev: 88cb988a2796b81c391b4302c04a6fb9df4f979d 
Muon: 4.5.21 
libchromiumcontent: 63.0.3239.59 
V8: 6.3.292 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Linux 
OS Release: 4.9.0-4-amd64 
OS Architecture: x64
````

**Reproducible on current live release:**

No.

**Comment by kjozwiak** [comment]
This is still an issue with the latest `0.19.106` C63 build... Receiving an `Uncaught Error: Unknown` whenever attempting to retrieve a context menu using right click.... Error being displayed:

```
[11560:11560:1205/121212.122713:ERROR:CONSOLE(219)] "Uncaught Error: Unknown type: function
TypeError: Unknown type: function
    at metaToValue (/usr/lib/brave/resources/electron.asar/browser/rpc-server.js:171:15)
    at metaToValue (/usr/lib/brave/resources/electron.asar/browser/rpc-server.js:166:30)
    at Array.map (<anonymous>)
    at unwrapArgs (/usr/lib/brave/resources/electron.asar/browser/rpc-server.js:174:15)
    at metaToValue (/usr/lib/brave/resources/electron.asar/browser/rpc-server.js:150:16)
    at Array.map (<anonymous>)
    at unwrapArgs (/usr/lib/brave/resources/electron.asar/browser/rpc-server.js:174:15)
    at EventEmitter.<anonymous> (/usr/lib/brave/resources/electron.asar/browser/rpc-server.js:282:12)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/usr/lib/brave/resources/electron.asar/browser/api/web-contents.js:189:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)", source: extensions::remote (219)
```

**Comment by srirambv** [comment]
Seeing the following error when right click on URL bar on Windows
```
$ [7692:2920:1205/171455.651:ERROR:CONSOLE(31034)] "Uncaught Error: Unknown type: function
TypeError: Unknown type: function
    at metaToValue (C:\Users\Sriram BV\AppData\Local\Brave\app-0.19.106\resources\electron.asar\browser\rpc-server.js:171:15)
    at metaToValue (C:\Users\Sriram BV\AppData\Local\Brave\app-0.19.106\resources\electron.asar\browser\rpc-server.js:166:30)
    at Array.map (<anonymous>)
    at unwrapArgs (C:\Users\Sriram BV\AppData\Local\Brave\app-0.19.106\resources\electron.asar\browser\rpc-server.js:174:15)
    at metaToValue (C:\Users\Sriram BV\AppData\Local\Brave\app-0.19.106\resources\electron.asar\browser\rpc-server.js:150:16)
    at Array.map (<anonymous>)
    at unwrapArgs (C:\Users\Sriram BV\AppData\Local\Brave\app-0.19.106\resources\electron.asar\browser\rpc-server.js:174:15)
    at EventEmitter.<anonymous> (C:\Users\Sriram BV\AppData\Local\Brave\app-0.19.106\resources\electron.asar\browser\rpc-server.js:282:12)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (C:\Users\Sriram BV\AppData\Local\Brave\app-0.19.106\resources\electron.asar\browser\api\web-contents.js:189:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)", source: chrome://brave/C:/Users/Sriram%20BV/AppData/Local/Brave/app-0.19.106/resources/app.asar/app/extensions/brave/gen/app.entry.js (31034)

```

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/237a6eeee62c97abddfbcb009935acf7478992ae
muon 4.5.22
