### ISSUE TITLE
brave crashing under ubuntu after being launched

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#12298]
### Description

Launching `0.19.117` under Ubuntu will launch Brave for a few seconds and will eventually crash with the following:

```
kjozwiak@kjozwiak-VM:~$ brave
ATTENTION: default value of option force_s3tc_enable overridden by environment.
An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined
Waiting 60 seconds for process to load
Trace/breakpoint trap (core dumped)
```

Unfortuntely, nothing is being dumped into `./config/brave/CrashPad`

### Steps to Reproduce

  1. install brave via `sudo dpkg -i brave_0.19.117_amd64.deb`
  2. once installed, simply launch brave via `brave` within the terminal
  3. brave will launch and the entire screen will appear white for 20-30s before crashing

**Actual result:**

![ubuntucrash](https://user-images.githubusercontent.com/2602313/34027222-5e828ea6-e129-11e7-8a7c-70f78e59d221.gif)

**Expected result:**

Brave shouldn't be crashing when launched under Ubuntu.

**Reproduces how often:**

100% reproducible under  Ubuntu 17.10, Ubuntu 17.04 and Ubuntu 16.04 using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.117 
> rev: 90a5b2277908b475baf195eb083147621facb35b 
> Muon: 4.5.26 
> libchromiumcontent: 63.0.3239.84 
> 

**Reproducible on current live release:**

Seems to be a regression in `0.19.117`

### Additional Information

* macOS 10.13.1 x64 - Couldn't Reproduce
* Win 10 Pro x64 - Couldn't Reproduce
* Ubuntu 17.10 x64 - Reproduced
* Ubuntu 17.04 x64 - Reproduced
* Ubuntu 16.04 x64 - Reproduced

CC'ing @darkdh @bsclifton @bridiver

**Comment by darkdh** [comment]
```
Error: Cannot find module 'v8-compile-cache'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/darkdh/Projects/browser-laptop-bootstrap/src/browser-laptop/node_modules/electron-prebuilt/dist/resources/electron.asar/common/reset-search-paths.js:41:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /home/darkdh/Projects/browser-laptop-bootstrap/src/browser-laptop/app/index.js:10:1
    at Object.<anonymous> (/home/darkdh/Projects/browser-laptop-bootstrap/src/browser-laptop/app/index.js:362:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'v8-compile-cache'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/darkdh/Projects/browser-laptop-bootstrap/src/browser-laptop/node_modules/electron-prebuilt/dist/resources/electron.asar/common/reset-search-paths.js:41:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /home/darkdh/Projects/browser-laptop-bootstrap/src/browser-laptop/app/index.js:10:1
    at Object.<anonymous> (/home/darkdh/Projects/browser-laptop-bootstrap/src/browser-laptop/app/index.js:362:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

```

**Comment by qazip** [comment]
Ubuntu 16.04, have this error when opening brave. It becomes unresponsive until I have to force close it.

```
ATTENTION: default value of option force_s3tc_enable overridden by environment.
An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined
Waiting 60 seconds for process to load
```

I try brave after several months and it doesn't work. Not good.

**Comment by kjozwiak** [comment]
@qazip which version did you download/use?

**Comment by qazip** [comment]
yes @kjozwiak

**Comment by capouch** [comment]
Can confirm that this crash is happening immediately on startup, both versions 117 and 118 are defective.

Linux Slackware 14.2-current.

**Comment by kjozwiak** [comment]
@qazip @capouch has https://github.com/brave/browser-laptop/releases/tag/v0.19.119dev fixed the crashing issue that you were seeing before?

**Comment by capouch** [comment]
@qazip indeed it has.  I hadn't checked to see if there was a release yet, post-fix.  I am using it to do this post, so we're all good, and thanks!!

**Comment by capouch** [comment]
@kjozwiak Bad news!!  It boots up OK, so it doesn't crash like last time.  But after a few minutes of use, all the sudden all the tabs disappear, the screen goes white, and the only fix is to kill it and start over.  I had it crash once in full-screen mode, and it took the whole VM down with it.  So I don't think we're good yet, although the behavior isn't quite the same as it was.

**Comment by kjozwiak** [comment]
@capouch thanks for the update! We're looking into the above crash in #12317.
