### ISSUE TITLE
BAT preferences page sometimes shows internal publisher URI rather than friendly version...

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#12591]
Here are two entries from my ledger synopsis:

<img width="911" alt="0" src="https://user-images.githubusercontent.com/400552/34775035-975c4fbc-f5c6-11e7-8a26-090b49134d25.png">

the first entry is "correct" in that it shows the name of the channel and ciicking on the link takes me to the videos page for the channel.

the second entry is "wrong" in that it shows the internal URI instead of the channel name and clicking on the link results in an error since the link resolves to the exact string you see above.

**Comment by NejcZdovc** [comment]
@mrose17 do you have STR?

**Comment by mrose17** [comment]
i'm not sure how to reproduce it. perhaps i am the only one seeing this!

**Comment by NejcZdovc** [comment]
@brave/qa did you experience anything like this? I know that we have one logged https://github.com/brave/browser-laptop/issues/12271

**Comment by mrose17** [comment]
@NejcZdovc - i am still seeing this. let me suggest a work-around until we can figure out what's going on.  if you have a display string of `youtube#channel:...` change the underlying URL to `https://www.youtube.com/channel/...` . 

you might also add code to the browser so that when `LEDGER_VERBOSE=true` it prints something out when it adds this to the synopsis.

**Comment by NejcZdovc** [comment]
I don't have STR, but this just happened to me as well. Created safety mechanism that solved it for me.

```
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot set property 'faviconName' of undefined
    at Object.onMediaPublisher (/Users/nejczdovc/Work/OpenSource/browser-laptop/app/browser/api/ledger.js:2428:51)
    at ledgerReducer (/Users/nejczdovc/Work/OpenSource/browser-laptop/app/browser/reducers/ledgerReducer.js:468:27)
    at reducers.reduce (/Users/nejczdovc/Work/OpenSource/browser-laptop/js/stores/appStore.js:384:24)
    at Array.reduce (<anonymous>)
    at applyReducers (/Users/nejczdovc/Work/OpenSource/browser-laptop/js/stores/appStore.js:382:68)
    at handleAppAction (/Users/nejczdovc/Work/OpenSource/browser-laptop/js/stores/appStore.js:441:16)
    at callbacks.forEach (/Users/nejczdovc/Work/OpenSource/browser-laptop/js/dispatcher/appDispatcher.js:107:7)
    at Array.forEach (<anonymous>)
    at AppDispatcher.dispatchToOwnRegisteredCallbacks (/Users/nejczdovc/Work/OpenSource/browser-laptop/js/dispatcher/appDispatcher.js:106:20)
    at AppDispatcher.dispatchInternal (/Users/nejczdovc/Work/OpenSource/browser-laptop/js/dispatcher/appDispatcher.js:132:10)
    at async.cargo (/Users/nejczdovc/Work/OpenSource/browser-laptop/js/dispatcher/appDispatcher.js:213:19)
    at process (/Users/nejczdovc/Work/OpenSource/browser-laptop/node_modules/async/dist/async.js:2317:17)
    at Immediate.<anonymous> (/Users/nejczdovc/Work/OpenSource/browser-laptop/node_modules/async/dist/async.js:66:16)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by mrose17** [comment]
@NejcZdovc - excellent! can you also make the fix i suggest above in terms of fixing the URL on the preferences page?

**Comment by kjozwiak** [comment]
As discussed in slack, this case will be covered by QA when going through the manual regression passes. Example: https://github.com/brave/qa-resources/blob/master/wikitemplate.md#ledger
