### ISSUE TITLE
Installation issues on an upgraded (24->26) fedora linux virtual machine (on QubesOS)

### ISSUE THREAD

**Issue by 3d73a4a412** [brave/browser-laptop#12782]
### Description

I had installed brave on a fedora-24 vm (qubesos), with a bit of trouble with the key (had to wget it, then add it manually but ok), but it worked. I upgraded to 26 and now brave does not work. I tried uninstalling reinstalling updating autoremove etc nada.

### Steps to Reproduce

I am not wholly sure about the detail I need to provide here, it simply won't start but I will add alittle
  1. start from the menu/icon and/or from cli, via the menu I see nothing, via cli I see what I pasted at the end.
  2.
  3.

**Actual result:**

Brave does not start up, nothing, no screen then crash, only the error I got below 

**Expected result:**
Expected to start up

**Reproduces how often:**

100% of the time, have yet to get Brave to be able to start up since I upgraded from fedora 24->26

### Brave Version

**about:brave info:**

don't remember, just about the lastest as I was updating it regularly until 2 days ago. As I am not able to start brave up I can't say exactly what ver it is. is there a file in my home dir that I could look in to get it?

**Reproducible on current live release:**

to be honest I am not sure what a "live build is" but I added the brave repo to my fedora24/26 vm so it updated via the repo regularly.

### Additional Information

This is the output I get when I try to start it from the terminal:

````
[1030:1030:0122/171540.634098:ERROR:sandbox_linux.cc(375)] InitializeSandbox() called with multiple threads in process gpu-process.
An uncaught exception occurred in the main process Uncaught Exception:
undefined: undefined
Waiting 60 seconds for process to load
An uncaught exception occurred in the main process Uncaught Exception:
Error: libgnome-keyring.so.0: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:182:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (/usr/share/brave/resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at /usr/share/brave/resources/app.asar/node_modules/keytar/lib/keytar.js:4:12
    at /usr/share/brave/resources/app.asar/node_modules/keytar/lib/keytar.js:58:4
Waiting 60 seconds for process to load
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'getIn' of null
    at registerComponents (/usr/share/brave/resources/app.asar/app/extensions.js:578:28)
    at Object.module.exports.init (/usr/share/brave/resources/app.asar/app/extensions.js:583:3)
    at perWindowStateLoaded (/usr/share/brave/resources/app.asar/app/index.js:186:16)
    at Immediate.setImmediate (/usr/share/brave/resources/app.asar/app/index.js:176:24)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate (timers.js:617:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Waiting 60 seconds for process to load
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'get' of null
    at Object.getExtensions (/usr/share/brave/resources/app.asar/app/common/state/extensionState.js:16:18)
    at ComponentUpdater.componentUpdater.on (/usr/share/brave/resources/app.asar/app/extensions.js:386:39)
    at emitTwo (events.js:106:13)
    at ComponentUpdater.emit (events.js:194:7)
Waiting 60 seconds for process to load
Action called before state was initialized: extension-installed
Action called before state was initialized: extension-enabled
Action called before state was initialized: extension-installed
Action called before state was initialized: extension-enabled
Action called before state was initialized: extension-installed
Action called before state was initialized: extension-enabled
Action called before state was initialized: extension-installed
Action called before state was initialized: extension-enabled
[996:1023:0122/171541.564535:ERROR:service_manager_context.cc(219)] Attempting to run unsupported native service: /usr/share/brave/content_gpu.service

Process failed to load within 60 seconds
````

**Comment by 3d73a4a412** [comment]
Ok, is there some more info I could leave? It seems this is not a priority (am assuming due to newer issues have already been assigned). I am happy to give whatever info I can, I was %100 sure about the parts that were being asked for but if any devs could ask me questions perhaps I could provide more relevant info?

**Comment by luixxiul** [comment]
CC @posix4e

**Comment by bsclifton** [comment]
@3d73a4a412 I believe you can install `libgnome-keyring` and it should resolve the issue. I think this dependency was missed until recently (docs should have been updated)

I'll close for now- please check out https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md and re-open if you still encounter the issue. Thanks 😄
