### ISSUE TITLE
Possible way to lose state, pls investigate

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#12896]
I noticed that if you do an app.quit during startup, you will get this error:

```
TypeError: Cannot read property 'set' of null
   at saveAppState (/Users/bbondy/projects/brave/browser-laptop/app/sessionStoreShutdown.js:83:46)
   at sessionStoreQueue.push (/Users/bbondy/projects/brave/browser-laptop/app/sessionStoreShutdown.js:164:7)
   at async.queue (/Users/bbondy/projects/brave/browser-laptop/app/sessionStoreShutdown.js:59:5)
   at /Users/bbondy/projects/brave/browser-laptop/node_modules/async/dist/async.js:4069:9
   at process (/Users/bbondy/projects/brave/browser-laptop/node_modules/async/dist/async.js:2317:17)
   at Immediate.<anonymous> (/Users/bbondy/projects/brave/browser-laptop/node_modules/async/dist/async.js:66:16)
```

It seems like a possible way to lose state, so I'm posting it for investigation. 

The original place I had this code was in app/index.js in this block:

```
  // Check in case a user is upgrading with this setting.
  // For non-legacy users, they will always have these settings in sync.
  if (getSetting(HARDWARE_ACCELERATION_ENABLED, initialSettings) === false &&
      app.getBooleanPref('hardware_acceleration_mode.enabled')) {
    // This won't take effect until the next restart of the app, so some users
    // may have to restart an extra time if UI doesn't work.
    app.setBooleanPref('hardware_acceleration_mode.enabled', false)
  }
```

I was going to app.relaunch and then app.quit, but it caused that error so I did the workaround with the comment above to just let it load.

**Comment by bridiver** [comment]
I'm thinking we should either block shutdown until all windows are loaded or shutdown without saving state
