### ISSUE TITLE
Missing Properties on Publisher Object Breaks Brave

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#13330]
### Test plan
(steps copied from https://github.com/brave/browser-laptop/issues/13488)

Corrupted state: [session-store-1.zip](https://github.com/brave/browser-laptop/files/1826679/session-store-1.zip)

You can manually modify the `ledger.synopsis.publishers` section of your `session-store-1` to match the below (the first entry is corrupt and prevents Brave from loading properly).
```js
{
    "ledger": {
        "synopsis": {
            "publishers": {
                "youtube#channel:UCdDpQ461uxNA3odAnpuigAg": {
                    "weight": 3,
                    "pinPercentage": 3,
                    "window": [
                        {
                            "timestamp": 1521228928558
                        }
                    ],
                    "options": {
                        "exclude": false
                    }
                },
                "youtube#channel:UCgFvT6pUq9HLOvKBYERzXSQ": {
                    "scores": {
                        "concave": 13.411161746224534,
                        "visits": 10
                    },
                    "visits": 1,
                    "window": [
                        {
                            "timestamp": 1520655903012,
                            "visits": 1,
                            "duration": 195578,
                            "scores": {
                                "concave": 13.411161746224534,
                                "visits": 10
                            }
                        }
                    ],
                    "publisherURL": "https://www.youtube.com/user/Davie504/videos",
                    "duration": 195578,
                    "faviconURL": "file://C:\\Users\\jjdsa\\AppData\\Roaming\\brave\\ledger-favicons\\youtube_channel_UCgFvT6pUq9HLOvKBYERzXSQ.jpeg",
                    "providerName": "YouTube",
                    "options": {
                        "exclude": true,
                        "verified": false,
                        "verifiedTimestamp": 6533268663129080000
                    },
                    "faviconName": "Davie504"
                }
            }
        }
    }
}
```

### Description

```
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'concave' of undefined
    at Synopsis.<anonymous> (E:\srirambv\browser-laptop\node_modules\bat-publisher\index.js:328:43)
    at Array.forEach (<anonymous>)
    at Synopsis._topN (E:\srirambv\browser-laptop\node_modules\bat-publisher\index.js:327:36)
    at Synopsis.topN (E:\srirambv\browser-laptop\node_modules\bat-publisher\index.js:299:15)
    at Object.run (E:\srirambv\browser-laptop\app\browser\api\ledger.js:2211:28)
    at ledgerReducer (E:\srirambv\browser-laptop\app\browser\reducers\ledgerReducer.js:286:19)
    at reducers.reduce (E:\srirambv\browser-laptop\js\stores\appStore.js:191:24)
    at Array.reduce (<anonymous>)
    at applyReducers (E:\srirambv\browser-laptop\js\stores\appStore.js:189:68)
    at handleAppAction (E:\srirambv\browser-laptop\js\stores\appStore.js:253:16)
    at callbacks.forEach (E:\srirambv\browser-laptop\js\dispatcher\appDispatcher.js:107:7)
    at Array.forEach (<anonymous>)
    at AppDispatcher.dispatchToOwnRegisteredCallbacks (E:\srirambv\browser-laptop\js\dispatcher\appDispatcher.js:106:20)
    at AppDispatcher.dispatchInternal (E:\srirambv\browser-laptop\js\dispatcher\appDispatcher.js:132:10)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
```

Saw it only once

**Comment by LaurenWags** [comment]
+1 from me - just experienced this on 0.21.16 no STR though.

**Comment by NejcZdovc** [comment]
will be fixed with https://github.com/brave-intl/bat-publisher/pull/23

**Comment by bsclifton** [comment]
+1 from @MoonRubles via https://github.com/brave/browser-laptop/issues/13474
> ### Description
>After a hard crash (UI completely unresponsive, restarted computer), there are NO tabs visible, and cannot add tabs. No address bar. Main menu is there, but Settings... doesnt open window. Lastpass window blank.
>
>Note: can someone tell me what files to delete to remove the corruption? I was using Payments on this computer so I'd like not to lose all my funds.
>
>Also: this occurred right about when payments should have happened, where Ive been having an  issue #13156 
>
> ### Steps to Reproduce
>
>  1. Wait for brave to lock up on its own. Happens every few days.
>  2. If you are unlucky, when you start brave will be unusable as described above.
>  3. Repeated restart does not change this.
>
> **Actual result:**
> ![braveblank](https://user-images.githubusercontent.com/36520807/37508155-12307f9a-28af-11e8-8425-6de519d21f91.PNG)
