### ISSUE TITLE
WEBUI context error when autofill entry is saved

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13421]
### Description
WEBUI context error when autofill entry is saved

### Steps to Reproduce
  1. Clean install 0.21.656
  2. Have an autofill entry created
  3. Open https://www.roboform.com/filling-test-all-fields, click on a filed and select autofill entry
  4. Click the auto-filled field and clear form
  5. Switch tab focus
  6 Console throws error after a few minutes

**Actual result:**
```
[7528:1280:0312/174543.509:ERROR:CONSOLE(0)] "(WEBUI context) chrome://brave/C:/Users/bellurs/AppData/Local/BraveBeta/app-0.21.656/resources/app.asar/app/extensions/brave/gen/app.entry.js:1: Uncaught Error: e=>{s.autofillSelectionClicked(t.get("tabId"),r,i,o)} could not be cloned.{Error: e=>{s.autofillSelectionClicked(t.get("tabId"),r,i,o)} could not be cloned.
    at EventEmitter.s.on (chrome://brave/C:/Users/bellurs/AppData/Local/BraveBeta/app-0.21.656/resources/app.asar/app/extensions/brave/gen/app.entry.js:1:961420)
    at emitTwo (extensions::event_emitter:105:13)
    at EventEmitter.emit (extensions::event_emitter:193:7)
    at EventEmitter.ipcRenderer.emit (extensions::ipc_utils:35:22)}", source: chrome://brave/C:/Users/bellurs/AppData/Local/BraveBeta/app-0.21.656/resources/app.asar/app/extensions/brave/index.html (0)
```

**Expected result:**
Shouldn't throw any error 

**Reproduces how often:**
No idea

### Brave Version

**about:brave info:**

Brave | 0.21.656
-- | --
Brave Sync | v1.4.2
libchromiumcontent | 65.0.3325.146
Muon | 4.9.0
Node.js | 7.9.0
OS Architecture | x64
OS Platform | Microsoft Windows
OS Release | 10.0.16299
rev | c8e9925
Update Channel | Beta
V8 | 6.5.254.31

**Reproducible on current live release:**
No

### Additional Information
cc: @btlechowski @LaurenWags @kjozwiak to verify on other platforms

**Comment by srirambv** [comment]
cc: @darkdh @bridiver @bsclifton

**Comment by LaurenWags** [comment]
Have not been able to reproduce on MacOS yet.

**Comment by kjozwiak** [comment]
Managed to run into this as well on macOS but I'm not 100% sure if it's related to auto-fill. When I ran into the above issue, I was going through the following use case:

* visited motorsport.com and opened a few tabs using `command + click`
* visited reddit.com and bookmarked the website
* opened several tabs from reddit using `command + click`
* switched over to a tab that was opened from reddit and exited the browser

```
[24312:775:0312/120406.826495:ERROR:CONSOLE(0)] "(WEBUI context) chrome://brave/Applications/Brave-Beta.app/Contents/Resources/app.asar/app/extensions/brave/gen/app.entry.js:1: Uncaught Error: function (t,n){c({openerTabId:e})} could not be cloned.{Error: function (t,n){c({openerTabId:e})} could not be cloned.
    at EventEmitter.s.on (chrome://brave/Applications/Brave-Beta.app/Contents/Resources/app.asar/app/extensions/brave/gen/app.entry.js:1:961419)
    at emitTwo (extensions::event_emitter:105:13)
    at EventEmitter.emit (extensions::event_emitter:193:7)
    at EventEmitter.ipcRenderer.emit (extensions::ipc_utils:35:22)}", source: chrome://brave/Applications/Brave-Beta.app/Contents/Resources/app.asar/app/extensions/brave/index.html (0)
```

Once I relaunched the browser, I was missing all my tabs that were opened from reddit.

**Comment by darkdh** [comment]
reduce the `sessionSaveInterval`
https://github.com/brave/browser-laptop/blob/9d5977ae9c9965dc9a9060426c60f15fbee3d73f/js/constants/appConfig.js#L22
would be much easier to reproduce the `function is not serializable`  [error](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) causing by we put lots of functions into array template
<img width="949" alt="screen shot 2018-03-12 at 4 10 09 pm" src="https://user-images.githubusercontent.com/11330831/37314565-17bf1196-2612-11e8-8f60-ed916e0b5b6a.png">

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/13432

**Comment by srirambv** [comment]
No console error based on steps from original issue description or from https://github.com/brave/browser-laptop/issues/13421#issuecomment-372431738
