### ISSUE TITLE
brave becomes unresponsive when using a search engine that isn't being responsive/having connectivity issues

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#13469]
### Description

Closing several tabs that are attempting to search using a search engine that is having connectivity issues will result in Brave becoming completely unresponsive. You'll receive the following errors in the terminal:

```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at request (/Applications/Brave-Beta.app/Contents/Resources/app.asar/app/common/lib/fetchSearchSuggestions.js:19:27)
    at Function.defaultSession.webRequest.fetch (/Applications/Brave-Beta.app/Contents/Resources/app.asar/js/lib/request.js:54:5)
```

```
An uncaught exception occurred in the main process Uncaught Exception:
AssertionError: Could not find tab for 21
    at Object.getTabPropertyByTabId (/Applications/Brave-Beta.app/Contents/Resources/app.asar/app/common/state/tabState.js:448:12)
    at Object.getWindowId (/Applications/Brave-Beta.app/Contents/Resources/app.asar/app/common/state/tabState.js:454:21)
    at urlBarSuggestionsReducer (/Applications/Brave-Beta.app/Contents/Resources/app.asar/app/browser/reducers/urlBarSuggestionsReducer.js:104:35)
    at reducers.reduce (/Applications/Brave-Beta.app/Contents/Resources/app.asar/js/stores/appStore.js:191:24)
    at Array.reduce (<anonymous>)
    at applyReducers (/Applications/Brave-Beta.app/Contents/Resources/app.asar/js/stores/appStore.js:189:68)
    at handleAppAction (/Applications/Brave-Beta.app/Contents/Resources/app.asar/js/stores/appStore.js:253:16)
    at callbacks.forEach (/Applications/Brave-Beta.app/Contents/Resources/app.asar/js/dispatcher/appDispatcher.js:107:7)
    at Array.forEach (<anonymous>)
    at AppDispatcher.dispatchToOwnRegisteredCallbacks (/Applications/Brave-Beta.app/Contents/Resources/app.asar/js/dispatcher/appDispatcher.js:106:20)
    at AppDispatcher.dispatchInternal (/Applications/Brave-Beta.app/Contents/Resources/app.asar/js/dispatcher/appDispatcher.js:132:10)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

### Steps to Reproduce

  1. open brave and set the default search engine to `Infogalactic` via `about:preferences#search`
  2. enable "autocomplete search terms as you type` via `about:preferences#search`
  3. open a new tab and search for something randomly
  4. quickly open a new tab and search for another term quickly
  5. repeat 3-4 so you have 3-5 tabs attempting to search using `Infogalactic`
  6. close all the tabs that you've opened that are attempting to search using `Infogalactic`

You'll see the above exceptions/errors in the terminal and Brave will eventually become completely unresponsive.

**Actual result:**

Brave becomes completely unresponsive. Example: https://youtu.be/nWk2oXf6uQ0 

**Expected result:**

Brave should never become unresponsive.

**Reproduces how often:**

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.21.658 
> V8: 6.5.254.36 
> rev: ad8bdc1d4f9c175d37dd9d4bb1b93dd0be512a1f
> libchromiumcontent: 65.0.3325.162
> Muon: 4.9.2 
> OS Release: 17.4.0 
> Update Channel: Beta 
> OS Architecture: x64 
> OS Platform: macOS 
> Node.js: 7.9.0 
> Brave Sync: v1.4.2 

**Reproducible on current live release:**

Yes, currently also reproducible under 0.21.18 580be78 which is the latest released build.

**Comment by kjozwiak** [comment]
Note: Looks like Infogalactic is now working correctly so I can't reproduce the issue anymore. I'm assuming this can happen with any of the search engines.

It looks like Brave doesn't behave well when it can't contact a search engine that's enabled as default with autocomplete enabled.

**Comment by wws35801** [comment]
Brave will not open due to attempting to run YouTube TV.  
![brave is locked up](https://user-images.githubusercontent.com/39407377/40235169-06bb6eb2-5a6f-11e8-8b04-8a10cb9908db.png)

**Comment by kjozwiak** [comment]
@wws35801 it doesn't look like the issue you're experiencing is related to this one. Seems like Brave got into a `not responding` state when you attempted to authenticate using a YubiKey via LastPass. Can you reproduce this consistently? Mind creating a new ticket if you can reproduce?

**Comment by wws35801** [comment]
I am not sophisticated enough to clear all the locations where Brave is set to open the last open files at start up.  I assume they are in the registry somewhere.  Thus Brave is useless to me as I have uninstalled and reinstalled and it attempts to reopen the same files and thus locks up.  It is back to Chrome for me, unfortunately.

**Comment by kjozwiak** [comment]
@wws35801 which files are you attempting to open that's causing the lock ups?
