### ISSUE TITLE
Missing Properties on Publisher Object Breaks Brave

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#13488]
### Description
A corrupted entry in _session-store-1's_ `ledger.synopsis.publishers` collection can cause Brave to render no tabs, and refuse to create any tabs. This issue was also reported on [Twitter](https://twitter.com/Ripley_Riley/status/974851272435208192) and in [Community](https://community.brave.com/t/unable-to-open-any-new-tabs/18028).

![image](https://user-images.githubusercontent.com/815158/37551743-836a2dc6-2974-11e8-9b53-c25f5f1236e5.png)

### Steps to Reproduce
_Manually modify a publishers-entry to resemble the first object shown below_

**Actual result:**
Tabs are non-existent and non-instantiatable in Brave. 

**Expected result:**
Brave should gracefully handle publisher objects which lack certain properties.

**Reproduces how often:**
I believe this is prone to happen once a month, when visit-metrics are removed from publisher objects.

### Brave Version
0.21.19

**about:brave info:**

**Reproducible on current live release:**
Yes

### Additional Information
Below are two objects. The first one prevents Brave from loading properly.
```js
{
    "ledger": {
        "synopsis": {
            "publishers": {
                "youtube#channel:UCdDpQ461uxNA3odAnpuigAg": {
                    "weight": 3,
                    "pinPercentage": 3,
                    "window": [
                        {
                            "timestamp": 1521228928558
                        }
                    ],
                    "options": {
                        "exclude": false
                    }
                },
                "youtube#channel:UCgFvT6pUq9HLOvKBYERzXSQ": {
                    "scores": {
                        "concave": 13.411161746224534,
                        "visits": 10
                    },
                    "visits": 1,
                    "window": [
                        {
                            "timestamp": 1520655903012,
                            "visits": 1,
                            "duration": 195578,
                            "scores": {
                                "concave": 13.411161746224534,
                                "visits": 10
                            }
                        }
                    ],
                    "publisherURL": "https://www.youtube.com/user/Davie504/videos",
                    "duration": 195578,
                    "faviconURL": "file://C:\\Users\\jjdsa\\AppData\\Roaming\\brave\\ledger-favicons\\youtube_channel_UCgFvT6pUq9HLOvKBYERzXSQ.jpeg",
                    "providerName": "YouTube",
                    "options": {
                        "exclude": true,
                        "verified": false,
                        "verifiedTimestamp": 6533268663129080000
                    },
                    "faviconName": "Davie504"
                }
            }
        }
    }
}
```

**Comment by jonathansampson** [comment]
I'm seeing some entries with even less information:

```js
                "sampsonresume.com": {
                    "weight": 0,
                    "window": [
                        {
                            "timestamp": 1521228928558
                        }
                    ],
                    "options": {
                        "exclude": false
                    }
                },
```

**Comment by jonathansampson** [comment]
@NejcZdovc, this is the error I'm seeing:

```
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'concave' of undefined
    at getPublisherData (C:\browser-laptop\app\browser\api\ledger.js:328:25)
    at Object.keys.forEach.publisherKey (C:\browser-laptop\app\browser\api\ledger.js:437:23)
    at Array.forEach (<anonymous>)
    at synopsisNormalizer (C:\browser-laptop\app\browser\api\ledger.js:425:27)
    at updatePublisherInfo (C:\browser-laptop\app\browser\api\ledger.js:552:11)
    at initSynopsis (C:\browser-laptop\app\browser\api\ledger.js:1230:11)
    at enable (C:\browser-laptop\app\browser\api\ledger.js:1304:11)
    at initialize (C:\browser-laptop\app\browser\api\ledger.js:1995:11)
    at Object.init (C:\browser-laptop\app\browser\api\ledger.js:2192:10)
    at ledgerReducer (C:\browser-laptop\app\browser\reducers\ledgerReducer.js:39:27)
```

**Comment by jonathansampson** [comment]
Closing as dupe to https://github.com/brave/browser-laptop/issues/13330
