### ISSUE TITLE
browser becomes unresponsive when running into TypeError: Cannot read property 'concave' of undefined

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#13511]
### Description

When going through `0.21.23` using `LEDGER_VERBOSE=true LEDGER_ENVIRONMENT=staging ./Brave.exe`, I received the following `TypeError` in the command prompt when visiting a website right after enabling the ledger and accepting a UGP grant:

```
TypeError: Cannot read property 'concave' of undefined
    at Synopsis.<anonymous> (C:\Users\kamil\AppData\Local\Brave\app-0.21.23\resources\app.asar\node_modules\bat-publisher\index.js:284:32)
    at Array.forEach (<anonymous>)
    at Synopsis.addPublisher (C:\Users\kamil\AppData\Local\Brave\app-0.21.23\resources\app.asar\node_modules\bat-publisher\index.js:283:27)
    at saveVisit (C:\Users\kamil\AppData\Local\Brave\app-0.21.23\resources\app.asar\app\browser\api\ledger.js:739:12)
    at addSiteVisit (C:\Users\kamil\AppData\Local\Brave\app-0.21.23\resources\app.asar\app\browser\api\ledger.js:724:10)
    at addNewLocation (C:\Users\kamil\AppData\Local\Brave\app-0.21.23\resources\app.asar\app\browser\api\ledger.js:841:15)
    at Object.pageDataChanged (C:\Users\kamil\AppData\Local\Brave\app-0.21.23\resources\app.asar\app\browser\api\ledger.js:982:13)
    at ledgerReducer (C:\Users\kamil\AppData\Local\Brave\app-0.21.23\resources\app.asar\app\browser\reducers\ledgerReducer.js:330:29)
    at reducers.reduce (C:\Users\kamil\AppData\Local\Brave\app-0.21.23\resources\app.asar\js\stores\appStore.js:191:24)
    at Array.reduce (<anonymous>)
    at applyReducers (C:\Users\kamil\AppData\Local\Brave\app-0.21.23\resources\app.asar\js\stores\appStore.js:189:68)
    at handleAppAction (C:\Users\kamil\AppData\Local\Brave\app-0.21.23\resources\app.asar\js\stores\appStore.js:253:16)
    at callbacks.forEach (C:\Users\kamil\AppData\Local\Brave\app-0.21.23\resources\app.asar\js\dispatcher\appDispatcher.js:107:7)
    at Array.forEach (<anonymous>)
    at AppDispatcher.dispatchToOwnRegisteredCallbacks (C:\Users\kamil\AppData\Local\Brave\app-0.21.23\resources\app.asar\js\dispatcher\appDispatcher.js:106:20)
    at AppDispatcher.dispatchInternal (C:\Users\kamil\AppData\Local\Brave\app-0.21.23\resources\app.asar\js\dispatcher\appDispatcher.js:132:10)
```
Once you receive the above error, it basically makes the entire browser unusable and requires the process to be terminated. I managed to run into the above issue on five different occasions.

### Steps to Reproduce

  1. launch `0.21.23` 6f9c4f7 and enable the ledger via `about:preferences#payments`
  2. accept the UGP grant
  3. while you're waiting for your BAT to appear under the balance, open a new tab
  4. visit https://www.boardgamegeek.com and leave it opened for a while

You'll notice that the website isn't being added into the ledger table and you'll eventually run into `TypeError: Cannot read property 'concave' of undefined`.

*Note:* This isn't easy to reproduce and doesn't always happen. However, as mentioned above, I did run into it 5 times.

**Actual result:**

The browser shouldn't become unresponsive and produce the above error when adding websites into the ledger.

**Expected result:**

Websites should be added into the ledger without any issues.

**Reproduces how often:**

It's not really easy to reproduce but I did manage to run into it on five different occasions.

### Brave Version

**about:brave info:**

> Brave: 0.21.23 
> rev: 6f9c4f7bfe298317bd5a00b979e28b33f4c769eb 
> Muon: 4.9.3
> libchromiumcontent: 65.0.3325.162
> OS Release: 10.0.16299 
> Update Channel: Release 
> OS Architecture: x64 
> OS Platform: Microsoft Windows 
> Node.js: 7.9.0 
> V8: 6.5.254.36 
> Brave Sync: v1.4.2 

**Reproducible on current live release:**

I'm not 100% sure as this isn't easy to reproduce. However, I'm assuming it's in the release version as well as per #13330.

### Additional Information

Related to #13330.

**Comment by NejcZdovc** [comment]
closing since fixed with https://github.com/brave-intl/bat-publisher/commit/37af0d22c50ca3637be59fa1d20dd40131825950

**Comment by kjozwiak** [comment]
STR are not really reliable and this is really hard to reproduce. QA will go through the manual ledger passes and ensure that this isn't happening when enabling wallets, adding websites, recording time on YT, Twitch etc..
