### ISSUE TITLE
ledger.js::run() throws an error when client.verboseP is set

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#13751]
TypeError: Cannot read property 'toString' of undefined
            at fields.forEach (/Applications/Brave.app/Contents/Resources/app.asar/app/browser/api/ledger.js:2311:54)
            at Array.forEach (<anonymous>)
            at line (/Applications/Brave.app/Contents/Resources/app.asar/app/browser/api/ledger.js:2308:14)
            at entries.forEach (/Applications/Brave.app/Contents/Resources/app.asar/app/browser/api/ledger.js:2335:7)
            at Array.forEach (<anonymous>)
            at run (/Applications/Brave.app/Contents/Resources/app.asar/app/browser/api/ledger.js:2331:13)
            at Object.onCallback (/Applications/Brave.app/Contents/Resources/app.asar/app/browser/api/ledger.js:2050:3)
            at ledgerReducer (/Applications/Brave.app/Contents/Resources/app.asar/app/browser/reducers/ledgerReducer.js:283:27)
            at reducers.reduce (/Applications/Brave.app/Contents/Resources/app.asar/js/stores/appStore.js:191:24)
            at Array.reduce (<anonymous>)
            at applyReducers (/Applications/Brave.app/Contents/Resources/app.asar/js/stores/appStore.js:189:68)
            at handleAppAction (/Applications/Brave.app/Contents/Resources/app.asar/js/stores/appStore.js:253:16)
            at callbacks.forEach (/Applications/Brave.app/Contents/Resources/app.asar/js/dispatcher/appDispatcher.js:107:7)
            at Array.forEach (<anonymous>)
            at AppDispatcher.dispatchToOwnRegisteredCallbacks (/Applications/Brave.app/Contents/Resources/app.asar/js/dispatcher/appDispatcher.js:106:20)
            at AppDispatcher.dispatchInternal (/Applications/Brave.app/Contents/Resources/app.asar/js/dispatcher/appDispatcher.js:132:10)

**Comment by mrose17** [comment]
it is probably this line:

                if (typeof field !== 'string') field = field.toString()

which suggests that there should be a test for `typeof field !== 'undefined'`

**Comment by kjozwiak** [comment]
Even though this was marked as `QA/no-qa-needed`, it was tested as there were several issues in this milestone that required using `LEDGER_VERBOSE=true`.
