### ISSUE TITLE
Crash after checking updates through Menu Bar

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#13876]
### Steps to Reproduce

1. Open Menu Bar (alt on windows)
2. Go to Help->Check for updates

**Actual result:**
Crash
Cannot change tabs
Cannot close browser through x nor trhough hamburger menu
Other menu items don't work
![unstable_browser](https://user-images.githubusercontent.com/34715963/39063118-16159226-44ca-11e8-8bb2-9b7e8fe4ef22.gif)
```
An uncaught exception occurred in the main process Uncaught Exception:
Error: invalid keyPath
    at invariant (C:\Users\bartlomiej\AppData\Local\Brave\app-0.22.665\resources\app.asar\node_modules\immutable\dist\immutable.js:870:27)
    at updateInDeepMap (C:\Users\bartlomiej\AppData\Local\Brave\app-0.22.665\resources\app.asar\node_modules\immutable\dist\immutable.js:1974:5)
    at updateInDeepMap (C:\Users\bartlomiej\AppData\Local\Brave\app-0.22.665\resources\app.asar\node_modules\immutable\dist\immutable.js:1980:23)
    at Map.updateIn (C:\Users\bartlomiej\AppData\Local\Brave\app-0.22.665\resources\app.asar\node_modules\immutable\dist\immutable.js:1278:26)
    at Map.setIn (C:\Users\bartlomiej\AppData\Local\Brave\app-0.22.665\resources\app.asar\node_modules\immutable\dist\immutable.js:1256:19)
    at tabsReducer (C:\Users\bartlomiej\AppData\Local\Brave\app-0.22.665\resources\app.asar\app\browser\reducers\tabsReducer.js:155:27)
    at reducers.reduce (C:\Users\bartlomiej\AppData\Local\Brave\app-0.22.665\resources\app.asar\js\stores\appStore.js:191:24)
    at Array.reduce (<anonymous>)
    at applyReducers (C:\Users\bartlomiej\AppData\Local\Brave\app-0.22.665\resources\app.asar\js\stores\appStore.js:189:68)
    at handleAppAction (C:\Users\bartlomiej\AppData\Local\Brave\app-0.22.665\resources\app.asar\js\stores\appStore.js:253:16)
[0420/183646.794:ERROR:http_transport_win.cc(273)] WinHttpSendRequest: A security error occurred (0x2f8f)
```

**Expected result:**
No Crash

**Reproduces how often:**
100%

### Brave Version
Not reproducible on v.0.22.22
```
Brave: 0.22.665 
V8: 6.6.346.24 
rev: bc13ab63f87b22dce366175927ffef54cb5cd201 
Muon: 5.2.5 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.117
```
Also reproduced by @kjozwiak on Win10 x64

cc @petemill @kjozwiak @LaurenWags @srirambv

**Comment by LaurenWags** [comment]
MacOS doesn't have Help > Check for Updates, but I tried Brave > Check for Updates and could not reproduce this.

**Comment by LaurenWags** [comment]
Verified on macOS 10.12.6 with
0.22.667 https://github.com/brave/browser-laptop/commit/0433b26a03c8daf9b181057cd2ffa7b530496faf
Muon 5.2.6
libchromiumcontent 66.0.3359.117
