### ISSUE TITLE
Broken seed overlay is not displayed

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#14001]
### Steps to Reproduce

1. Enable payments and close browser after wallet is created
2. Edit ledger-state.json file and change the `keyinfo` section to look like this per https://github.com/brave/browser-laptop/issues/13424#issuecomment-377130187:
"keyinfo": {
   "seed": {
    "0": 0,
    "1": 0
  }
3. Relaunch browser go to payments --> payments doesn't show corrupted overlay
4. Furthermore, when I go to the gear icon and try to view my words, all backup words are displayed even though my ledger-state.json file shows `keyinfo` as above.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.703 https://github.com/brave/browser-laptop/commit/903b8d0d3703b5fdc5a719294403e7460d9b806d
* muon 6.0.8
* libchromiumcontent 66.0.3359.139

**Comment by LaurenWags** [comment]
Note, while testing @kjozwiak and I did encounter the following error. Confirmed with @ryanml and @NejcZdovc that it is expected in this scenario.

TypeError: Invalid entropy
    at Object.entropyToMnemonic (/Applications/Brave-Beta.app/Contents/Resources/app.asar/node_modules/bip39/index.js:98:34)
    at Object.fromBytesOrHex (/Applications/Brave-Beta.app/Contents/Resources/app.asar/node_modules/brave-crypto/index.js:191:20)
    at Object.Client.getWalletPassphrase (/Applications/Brave-Beta.app/Contents/Resources/app.asar/node_modules/bat-client/index.js:521:39)
    at getStateInfo (/Applications/Brave-Beta.app/Contents/Resources/app.asar/app/browser/api/ledger.js:1680:45)
    at Object.onInitRead (/Applications/Brave-Beta.app/Contents/Resources/app.asar/app/browser/api/ledger.js:2326:11)
    at ledgerReducer (/Applications/Brave-Beta.app/Contents/Resources/app.asar/app/browser/reducers/ledgerReducer.js:334:27)
    at handleAppAction (/Applications/Brave-Beta.app/Contents/Resources/app.asar/js/stores/appStore.js:249:16)
    at callbacks.forEach (/Applications/Brave-Beta.app/Contents/Resources/app.asar/js/dispatcher/appDispatcher.js:107:7)
    at Array.forEach (<anonymous>)

**Comment by btlechowski** [comment]
Is it valid behavior that recovery dialog is shown?
![image](https://user-images.githubusercontent.com/34715963/39815479-591bfab0-5398-11e8-83d1-9511131b196a.png)

On top of that I can go to 'Backup my wallet ' and use the words for recovery.

Tested with clean profile on
```
Brave: 0.22.703 
V8: 6.6.346.26 
rev: 903b8d0d3703b5fdc5a719294403e7460d9b806d 
Muon: 6.0.8 
OS Release: 4.13.0-21-generic 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.139
```

**Comment by NejcZdovc** [comment]
@btlechowski yes broken seed dialog should be displayed when you corrupt your seed
