### ISSUE TITLE
enabling extensions throws an error in terminal and logs an report in chrome://crashes

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14075]
### Description
Enabling extensions (tried Bitwarden, Dashlane, Honey) in 0.22.703 throws an error in the terminal. Could not repro the error in 0.22.669.

### Steps to Reproduce

  1. Launch via CLI.
  2. Go to about:preferences#extensions and enable Bitwarden (or Dashlane, etc).
  3. Bitwarden enables. You don't need to login.

**Actual result:**
Error is displayed in the terminal and a crash report is logged in chrome://crashes.

```
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from 607
    at Object.fromTabID (/Users/laurenwagner/BraveDocuments/Laptop/Brave Beta/Brave-Beta.app/Contents/Resources/electron.asar/browser/api/web-contents.js:251:30)
    at getWebContentsForTab (/Users/laurenwagner/BraveDocuments/Laptop/Brave Beta/Brave-Beta.app/Contents/Resources/electron.asar/browser/api/extensions.js:127:22)
    at getTabValue (/Users/laurenwagner/BraveDocuments/Laptop/Brave Beta/Brave-Beta.app/Contents/Resources/electron.asar/browser/api/extensions.js:131:21)
    at tabIds.reduce (/Users/laurenwagner/BraveDocuments/Laptop/Brave Beta/Brave-Beta.app/Contents/Resources/electron.asar/browser/api/extensions.js:351:19)
    at Array.reduce (<anonymous>)
    at tabsQuery (/Users/laurenwagner/BraveDocuments/Laptop/Brave Beta/Brave-Beta.app/Contents/Resources/electron.asar/browser/api/extensions.js:350:26)
    at EventEmitter.<anonymous> (/Users/laurenwagner/BraveDocuments/Laptop/Brave Beta/Brave-Beta.app/Contents/Resources/electron.asar/browser/api/extensions.js:500:18)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
    at WebContents.<anonymous> (/Users/laurenwagner/BraveDocuments/Laptop/Brave Beta/Brave-Beta.app/Contents/Resources/electron.asar/browser/api/web-contents.js:180:13)
```

Additional errors/crash reports will accumulate each time you open a new tab.

**Expected result:**
No error in terminal, no crash reports in chrome://crashes.

**Reproduces how often:**
Easily.

### Brave Version

**about:brave info:**
0.22.703

**Reproducible on current live release:**
no, does not reproduce on 0.22.669

### Additional Information
Reproduced by @kjozwiak on macOS and Win using Bitwarden.

I saw this behavior with Bitwarden, Dashlane, Honey, LastPass.

**Comment by kjozwiak** [comment]
> Additional errors/crash reports will accumulate each time you open a new tab.

This could lead to an influx of crash reports from users who have Bitwarden enabled. Every time a user opens a tab, they'll trigger the above crash which is also logged in `chrome://crashes` and sent into `stats.brave`.

**Comment by LaurenWags** [comment]
You also get this error if you enable sync, navigate to about:extensions page, and click on the '_generated_background_page.html' link.

**Comment by petemill** [comment]
@LaurenWags does the fact your error can be reproduced with current release preview mean that sync does not work?

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/muon/commit/3bb5db3032c03dfb52e048e281c0d0a2c4ec9c0a which is present in Muon 6.0.9

**Comment by LaurenWags** [comment]
When using a large profile, if you enable, disable, and re-enable an extension (Bitwarden, Honey, etc) - you get a message like this in the terminal and a crash in chrome://crashes:
[91570:775:0514/140410.017682:FATAL:dispatcher.cc(899)] bmnlcjabgnpnenekpadlanbbkooimhnj was never loaded: 

If you use a clean profile, this does not happen. Reproduced by @kjozwiak 

cc @petemill @bsclifton

**Comment by kjozwiak** [comment]
Created https://github.com/brave/browser-laptop/issues/14123 for the above issue that @LaurenWags mentioned above.

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.712 e48c5ff
* muon 6.0.9
* libchromiumcontent 66.0.3359.139
