### ISSUE TITLE
Browser is unusable after rapidly turning payments on and off

### ISSUE THREAD

**Issue by btlechowski** [brave/browser-laptop#14179]
### Steps to Reproduce
  1. Clean profile
  2. Run brave with LEDGER_ENVIRONMENT=staging
  3. Go to about:preferences#payments
  4. Rapidly turn Brave Payments on and off

**Actual result:**
Browser becomes unusable. Cannot switch tabs, Cannot close tabs. 
USD values are never shown
![image](https://user-images.githubusercontent.com/34715963/40261000-63e09114-5afe-11e8-9214-aabd49e9936c.png)

Error in terminal:
```
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'sync' of null
    at Object.onLedgerFirstSync (/usr/lib/brave-beta/resources/app.asar/app/browser/api/ledger.js:2397:14)
    at ledgerReducer (/usr/lib/brave-beta/resources/app.asar/app/browser/reducers/ledgerReducer.js:303:27)
    at handleAppAction (/usr/lib/brave-beta/resources/app.asar/js/stores/appStore.js:260:16)
    at callbacks.forEach (/usr/lib/brave-beta/resources/app.asar/js/dispatcher/appDispatcher.js:107:7)
    at Array.forEach (<anonymous>)
    at AppDispatcher.dispatchToOwnRegisteredCallbacks (/usr/lib/brave-beta/resources/app.asar/js/dispatcher/appDispatcher.js:106:20)
    at AppDispatcher.dispatchInternal (/usr/lib/brave-beta/resources/app.asar/js/dispatcher/appDispatcher.js:132:10)
    at async.cargo (/usr/lib/brave-beta/resources/app.asar/js/dispatcher/appDispatcher.js:213:19)
    at Object.process (/usr/lib/brave-beta/resources/app.asar/node_modules/async/dist/async.js:2330:17)
    at /usr/lib/brave-beta/resources/app.asar/node_modules/async/dist/async.js:2238:19
```

**Reproduces how often:**
10%

### Brave Version
I was able only to repro on staging server. But reproducibility is low on this issue so it could be bad luck.
 
```
Brave: 0.22.716 
V8: 6.6.346.32 
rev: 5ae68e8994b83385a75fbb5ebd4d1cd8081ad45e 
Muon: 6.0.11 
OS Release: 4.13.0-21-generic 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170
```

**Reproducible on current live release:**
No, even on staging server. v0.22.714 Ubuntu 17.10 x64. But reproducibility is low on this issue so it could be bad luck.

cc @srirambv @LaurenWags @kjozwiak @bsclifton @GeetaSarvadnya @petemill

**Comment by bsclifton** [comment]
Assigning @ryanml as he has done some preliminary investigation; I believe he was not able to reproduce, but perhaps we can put extra checks in place (regarding the above error)

**Comment by NejcZdovc** [comment]
@bsclifton @btlechowski based on the fact that you need to machine gun it, I think that this should go into triage backlog? wdyt?

**Comment by bsclifton** [comment]
@NejcZdovc I think that's a good call 😄 Let's move it
