### ISSUE TITLE
Brave crashes when ledger-state.json is missing/corrupted (after update to 0.22.714)

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14202]
### Description
Some users in community have reported that Brave is unresponsive/beachballs after they update to 0.22.714. A couple of users have solved this by getting a clean profile. One user said they went back to 0.22.669, updated again and the issue was gone. Another user removed their ledger-state.json file and the issue was resolved.

https://community.brave.com/t/brave-0-22-714-beachballs-on-launch-on-mac-os-10-13-4-had-to-force-quit/22175
https://community.brave.com/t/browser-crashes-seconds-after-launch/22438
https://community.brave.com/t/mac-spinning-disc-and-hang/22422
https://community.brave.com/t/update-problem-0-22-714-6-0-9-18-mai-18-mac-os-x-10-11-6/22160

### Steps to Reproduce
I don't have solid steps so far, but the general ones are:
  1. Have 0.22.669 installed (probably with ledger enabled).
  2. Update to 0.22.714
  3.

**Actual result:**
Brave hangs/beachballs after you relaunch once you've been updated to 0.22.714.

**Expected result:**
No hanging/beach ball.

**Reproduces how often:**
Unknown, have not yet reproduced.

### Brave Version

**about:brave info:**
0.22.714

**Reproducible on current live release:**
yes 0.22.714 is current release

**Comment by mlhaufe** [comment]
I am also experiencing this in 0.22.721

**Comment by LaurenWags** [comment]
@mlhaufe what's your OS?

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/brave-crashes-on-startup-windows-10/22797

**Comment by mlhaufe** [comment]
@LaurenWags 

FYI, by cutting and pasting **ledger-state.json** into another location I was able to get the browser to load without locking.

But, after opening I am unable to switch tabs, close the browser or access any menu. (Previewing tabs still works)

When I kill the application with Task Manager I get a number of error windows (x6):

![image](https://user-images.githubusercontent.com/826584/40676941-d0781252-6341-11e8-9dc8-2047dfa67431.png)

When I put the  **ledger-state.json* file back into its original location it locks again.

I am also a "victim" of the following issue. Not sure if it is related:

https://github.com/brave-intl/bat-ledger/issues/205

**Comment by bsclifton** [comment]
@mlhaufe can you please try moving ledger-state.json into another location again? Like you said, this should get you loaded and then you should be unable to switch tabs. When this happens, can you please press Shift + F8 to open the browser tools? Then (in that small window) you can go to the "Console" tab.  There should be errors being logged

Basically, once we identify the errors, fixing them should be very easy 😄 👍  I believe there is an error happening which is not caught and is breaking the UI

**Comment by mlhaufe** [comment]
@bsclifton 

![image](https://user-images.githubusercontent.com/826584/40685113-f6415004-6358-11e8-9f71-d259a5ea0457.png)

**Comment by bsclifton** [comment]
@mlhaufe thanks for the quick response- unfortunately, looks like there wasn't any rendering issues ☹️ 

If you happen to have Git Bash installed, you can run Brave from the command line and get some good output (unfortunately, cmd.exe doesn't capture stdout properly)

If you haven't already, you can also try reverting to an older version (basically the last working version- https://github.com/brave/browser-laptop/releases/tag/v0.22.669dev). I'm curious if that works fine.  If so, re-running the upgrade may help 

As a last resort- if you were willing- you could share your `session-store-1` file with me at clifton@brave.com. I would definitely understand if you chose not to do this (you can always try to delete the history or bookmarks one-by-one, if the UI isn't locked up)

**Comment by mlhaufe** [comment]
I'll send you an email shortly.

**Comment by gallegosart** [comment]
It looks like I'm having this problem (w10 x64, 0.22.721)
Launching via Git:
$ Crash reporting enabled
(node:15104) MaxListenersExceededWarning: Possible EventEmitter memory leak dete                                                       cted. 11 window-renderer-ready listeners added. Use emitter.setMaxListeners() to                                                        increase limit
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 wind                                                       ow-renderer-ready listeners added. Use emitter.setMaxListeners() to increase lim                                                       it
    at _addListener (events.js:262:19)
    at BrowserWindow.addListener (events.js:279:10)
    at BrowserWindow.once (events.js:308:8)
    at Immediate.setImmediate (C:\Users\NAME\AppData\Local\Brave\app-0.22.721\reso                                                       urces\app.asar\app\browser\tabs.js:1072:15)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
[15104:11356:0530/173332.924:ERROR:CONSOLE(27)] "(node) warning: possible EventE                                                       mitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() t                                                       o increase limit.", source: chrome://brave/C:/Users/NAME/AppData/Local/Brave/app-0                                                       .22.721/resources/app.asar/app/extensions/brave/gen/app.entry.js (27)
[15104:11356:0530/173333.187:ERROR:CONSOLE(27)] "(node) warning: possible EventE                                                       mitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() t                                                       o increase limit.", source: chrome://brave/C:/Users/NAME/AppData/Local/Brave/app-0                                                       .22.721/resources/app.asar/app/extensions/brave/gen/app.entry.js (27)
[15104:11356:0530/173333.295:ERROR:CONSOLE(27)] "(node) warning: possible EventE                                                       mitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() t                                                       o increase limit.", source: chrome://brave/C:/Users/NAME/AppData/Local/Brave/app-0                                                       .22.721/resources/app.asar/app/extensions/brave/gen/app.entry.js (27)

**Comment by gallegosart** [comment]
Deleting ledger-state.json cleared this up.

**Comment by bsclifton** [comment]
@mlhaufe thanks for sharing (I did receive the files0! I'm looking into this issue now...

**Comment by bsclifton** [comment]
Root cause identified - talking with team about a fix. This only affects folks who have payments enabled

**Comment by gallegosart** [comment]
Fired up Brave with .json deleted, which gives me a few moments before UI stops responding. Used that time to turn off Payments, then shut down and restarted and all seems well again.

**Comment by kjozwiak** [comment]
@NejcZdovc @bsclifton could you please add a test plan that QA can use for verification?

**Comment by btlechowski** [comment]
Verified on Ubuntu 17.10 x64
* 0.22.727 https://github.com/brave/browser-laptop/commit/2c94bbad00d70b87328f04574725979960e18f9f
* muon 6.0.12
* libchromiumcontent 66.0.3359.170
