### ISSUE TITLE
Reconcile doesn't go through 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14276]
### Description
Reconcile doesn't go through 

### Steps to Reproduce
  1. Install 0.22.723
  2. Claim grant
  3. Browse for 30 mins to meet the min reconcile criteria
  4. Edit reconcilestamp to an older date 
  5. Launch browser with `LEDGER_NO_DELAY=true LEDGER_NO_FUZZING=true LEDGER_VERBOSE=true` parameters
  6. Browser shows `Contribution Overdue` but doesn't reconcile

**Actual result:**
Console throws 400 error andreconcile doesn't happen

**Expected result:**
Reconcile should happen

**Reproduces how often:**
Easy

### Brave Version

**about:brave info:**

Brave | 0.22.723
-- | --
V8 | 6.6.346.32
rev | edb3e88
Muon | 6.0.12
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
libchromiumcontent | 66.0.3359.170

**Reproducible on current live release:**
N/A

### Additional Information
Issue reproduced on mac by @LaurenWags

**Comment by NejcZdovc** [comment]
@srirambv what is the error? Are you on production or staging?

**Comment by NejcZdovc** [comment]
```
<<< PUT https://ledger-staging.mercury.basicattentiontoken.org/v2/wallet/ba1e14ea-cb37-43b0-a207-44155350d699
<<< content-type: application/json; charset=utf-8
<<< user-agent: Brave/0.24.0 Chrome/66.0.3359.170 Muon/6.0.12 macOS x64
<<< accept-encoding:
<<<
<<< {
<<<   "viewingId": "b0bb7011-9307-4edc-b664-1c9ba84566b5",
<<<   "surveyorId": "B+M/8RjWfNYFZjeXBqpvXJBGev4S05wI9olydoW0hzb",
<<<   "requestType": "httpSignature",
<<<   "signedTx": {
<<<     "headers": {
<<<       "digest": "SHA-256=sWh/DtY5jN8umAPNQRsG8i8pnr88ySLEBQ2ys07y2DU=",
<<<       "signature": "keyId=\"primary\",algorithm=\"ed25519\",headers=\"digest\",signature=\"fr7z/T/qzgZAtRQPVerDWI0vcB/sMKflKwVQbHmWI6+2hELHfTl9VSI6i1AFUmDK+4czGhOR9aI22Wj//TCfAw==\""
<<<     },
<<<     "body": {
<<<       "denomination": {
<<<         "amount": "5",
<<<         "currency": "BAT"
<<<       },
<<<       "destination": "6654ecb0-6079-4f6c-ba58-791cc890a561"
<<<     },
<<<     "octets": "{\"denomination\":{\"amount\":\"5\",\"currency\":\"BAT\"},\"destination\":\"6654ecb0-6079-4f6c-ba58-791cc890a561\"}"
<<<   }
<<< }
[ response for PUT https://ledger-staging.mercury.basicattentiontoken.org/v2/wallet/ba1e14ea-cb37-43b0-a207-44155350d699 ]
>>> HTTP/1.1 500
>>> cache-control: no-cache
>>> connection: keep-alive
>>> content-length: 96
>>> content-type: application/json; charset=utf-8
>>> date: Wed, 30 May 2018 15:15:02 GMT
>>> server: Cowboy
>>> vary: accept-encoding
>>> via: 1.1 vegur
>>> x-rate-limit-limit: 60
>>> x-rate-limit-remaining: 59
>>> x-rate-limit-reset: 1527693360
>>>
>>> {"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}
<<< PUT https://ledger-staging.mercury.basicattentiontoken.org/v2/wallet/ba1e14ea-cb37-43b0-a207-44155350d699
<<< content-type: application/json; charset=utf-8
<<< user-agent: Brave/0.24.0 Chrome/66.0.3359.170 Muon/6.0.12 macOS x64
<<< accept-encoding:
<<<
<<< {
<<<   "viewingId": "b0bb7011-9307-4edc-b664-1c9ba84566b5",
<<<   "surveyorId": "B+M/8RjWfNYFZjeXBqpvXJBGev4S05wI9olydoW0hzb",
<<<   "requestType": "httpSignature",
<<<   "signedTx": {
<<<     "headers": {
<<<       "digest": "SHA-256=sWh/DtY5jN8umAPNQRsG8i8pnr88ySLEBQ2ys07y2DU=",
<<<       "signature": "keyId=\"primary\",algorithm=\"ed25519\",headers=\"digest\",signature=\"fr7z/T/qzgZAtRQPVerDWI0vcB/sMKflKwVQbHmWI6+2hELHfTl9VSI6i1AFUmDK+4czGhOR9aI22Wj//TCfAw==\""
<<<     },
<<<     "body": {
<<<       "denomination": {
<<<         "amount": "5",
<<<         "currency": "BAT"
<<<       },
<<<       "destination": "6654ecb0-6079-4f6c-ba58-791cc890a561"
<<<     },
<<<     "octets": "{\"denomination\":{\"amount\":\"5\",\"currency\":\"BAT\"},\"destination\":\"6654ecb0-6079-4f6c-ba58-791cc890a561\"}"
<<<   }
<<< }
[ response for PUT https://ledger-staging.mercury.basicattentiontoken.org/v2/wallet/ba1e14ea-cb37-43b0-a207-44155350d699 ]
>>> HTTP/1.1 400
>>> cache-control: no-cache
>>> connection: keep-alive
>>> content-length: 84
>>> content-type: application/json; charset=utf-8
>>> date: Wed, 30 May 2018 15:15:04 GMT
>>> server: Cowboy
>>> vary: accept-encoding
>>> via: 1.1 vegur
>>> x-rate-limit-limit: 60
>>> x-rate-limit-remaining: 58
>>> x-rate-limit-reset: 1527693360
>>>
>>> {"statusCode":400,"error":"Bad Request","message":"Response Error: 400 Bad Request"}

ledger client callback: clientP=true errP=true resultP=false delayTime=undefined
ledger client error(1): {}
Error: HTTP response 400 for PUT /v2/wallet/ba1e14ea-cb37-43b0-a207-44155350d699
    at request.request (/Users/nejczdovc/Work/OpenSource/browser-laptop/app/browser/api/ledger.js:1611:9)
    at Function.defaultSession.webRequest.fetch (/Users/nejczdovc/Work/OpenSource/browser-laptop/js/lib/request.js:75:5)
```

cc @evq

**Comment by srirambv** [comment]
@NejcZdovc this is on staging

**Comment by kjozwiak** [comment]
Closing. @evq fixed the staging server last night and contributing/reconcilement with UGP grants is now working under the staging server.

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.22.724 1f07e93
* muon 6.0.12
* libchromiumcontent 66.0.3359.170
