### ISSUE TITLE
Python unittests failing without requests module installed

### ISSUE THREAD

**Issue by RyanJarv** [brave/browser-laptop#14430]
### Description
Python unittests fail when run in an environment without python requests installed.

### Steps to Reproduce
  1. pip uninstall requests
  2. yarn run unittest

**Actual result:**
```
$ yarn run unittest
yarn run v1.6.0
$ python tools/test && cross-env NODE_ENV=test mocha "test/unit/**/*Test.js" --globals chrome,DOMParser,XMLSerializer
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/rgerstenkorn/Code/browser-laptop/tools/test/__main__.py", line 9, in <module>
    from test_publish import *
  File "tools/test/test_publish.py", line 13, in <module>
    import publish_release
  File "/Users/rgerstenkorn/Code/browser-laptop/tools/test/../publish_release.py", line 10, in <module>
    from lib.github import GitHub
  File "/Users/rgerstenkorn/Code/browser-laptop/tools/test/../lib/github.py", line 12, in <module>
    import requests
ImportError: No module named requests
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected result:**
Tests don't try to import the actual requests module since it isn't being used there

**Reproduces how often:**
Everytime on current master

**Comment by RyanJarv** [comment]
PR: https://github.com/brave/browser-laptop/pull/14429
