### ISSUE TITLE
Unable to create Eth wallet on Windows via extension menu

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14822]
### Description
Unable to create Eth wallet on Windows via extension menu

### Steps to Reproduce

  1. Build from #14734 
  2. Enable Eth wallet
  3. Click on extension and click on create wallet
  4. Enter password and click create, nothing happens

**Actual result:**
Wallet creation fails on Windows with following console errors
```
An uncaught exception occurred in the main process Uncaught Exception:
Error: connect ENOENT C:\Users\\AppData\Roaming\brave-development\ethereum\geth.ipc
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
[14012:10052:0724/123413.707:ERROR:CONSOLE(0)] "Denying load of chrome-extension://dakeiobolocmlkdebloniehpglcjkgcp/wallet-icon.png#brave-favicon-fragment. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.", source: chrome://brave/C:/browser-laptop/app/extensions/brave/index-dev.html (0)
```

**Expected result:**
Wallet should be created.

**Reproduces how often:**
100% 
Reproduced by @kjozwiak  on Windows

### Brave Version
ac4c649

**Reproducible on current live release:**
N/A

### Additional Information
@LaurenWags was able to create wallet with above steps on mac

**Comment by flamsmark** [comment]
Resolved in https://github.com/brave/browser-laptop/pull/14734/commits/223323c42339ede12daddd630445205cb6ba2814 .

**Comment by GeetaSarvadnya** [comment]
Verified on Windows x64 with
• 0.23.100 5e197a1a877c9967aecc838b9a7ca528ee5b46bd
• Muon 8.0.8
• libchromiumcontent 68.0.3440.84

**Comment by kjozwiak** [comment]
Even though this as related to Windows, we should also make sure that there's no extension button anywhere within the product on both macOS and Linux as well. The only way to access ETH Wallet is via `about:preferences#ethwallet`.
