### ISSUE TITLE
Build on windows10 with error: Cannot find module 'ad-block'

### ISSUE THREAD

**Issue by hugetiny** [brave/browser-laptop#15143]
### Description
OS:Windows10

npm run watch
webpack: Compiled successfully.

npm start
App threw an error during load
Error: Cannot find module 'ad-block'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (D:\browser-laptop\node_modules\_electron-prebuilt@1.4.31@electron-prebuilt\dist\re
sources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (D:\browser-laptop\node_modules\_v8-compile-cache@1.1.2@v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\browser-laptop\app\adBlock.js:8:49)
    at Module._compile (D:\browser-laptop\node_modules\_v8-compile-cache@1.1.2@v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
An uncaught exception occurred in the main process Uncaught Exception:
Error: Cannot find module 'ad-block'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (D:\browser-laptop\node_modules\_electron-prebuilt@1.4.31@electron-prebuilt\dist\re
sources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (D:\browser-laptop\node_modules\_v8-compile-cache@1.1.2@v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\browser-laptop\app\adBlock.js:8:49)
    at Module._compile (D:\browser-laptop\node_modules\_v8-compile-cache@1.1.2@v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
process exited with code 7
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! brave@0.25.0 start: `node ./tools/start.js --user-data-dir-name=brave-development --enable-logging --v=0 --enable-
extension-activity-logging --enable-sandbox-logging --enable-dcheck`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the brave@0.25.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by bsclifton** [comment]
@hugetiny did you do an `npm install` before you ran `npm run watch`?

**Comment by hugetiny** [comment]
@bsclifton Solved.
Everytime I run "npm install"I have to download "https://s3.us-east-2.amazonaws.com/demo-tor-binaries/tor-0.3.3.8-win32-brave-5.exe" from remote address and it can cause some problems.I recommend to move the tor-0.3.3.8-win32-brave-5.exe to path:"app/extensions/bin"

**Comment by bsclifton** [comment]
@hugetiny awesome, thanks for digging in (and updating us after you solved) 😄 👍
