### ISSUE TITLE
Brave JavaScript Error - Latest Development Build

### ISSUE THREAD

**Issue by rocky4-iv** [brave/browser-laptop#1550]
Here is the output from Brave Dev Build That just updated  today. Causes feeze-up & invisible window.
JavaScript Error occurred in the main process
Uncaught Exception:
TypeError: Error processing argument at index 1, conversion failure from 
    at TypeError (native)
    at process.<anonymous> (/usr/lib/brave/resources/electron.asar/browser/chrome-extension.js:90:34)
    at emitMany (events.js:121:13)
    at process.emit (events.js:195:7)
    at installExtension (/usr/lib/brave/resources/app.asar/app/extensions.js:28:13)
    at enableExtensions (/usr/lib/brave/resources/app.asar/app/extensions.js:46:5)
    at AppStore.addChangeListener (/usr/lib/brave/resources/app.asar/app/extensions.js:64:5)
    at emitNone (events.js:85:20)
    at AppStore.emit (events.js:179:7)
    at AppStore.emitChanges (/usr/lib/brave/resources/app.asar/js/stores/appStore.js:185:10)

**Comment by diracdeltas** [comment]
just to confirm, this was downloaded from https://github.com/brave/browser-laptop/releases ?

**Comment by bridiver** [comment]
I think there still must have been a mismatch with electron versions because line 90 of chrome-extension.js is blank in master

**Comment by rocky4-iv** [comment]
Actutally the latest dev build install was installed through Pamac updates. And the original Brave install was done through AUR - Arch User Repository -git version. I'm running Manjaro Linux.
I'll attempt uninstall and then use Bleachbit to clean configuration files and build fresh from source with new PKGBuild.

**Comment by bridiver** [comment]
deleting `node_modules` and `~/.electron` followed by `npm install` should clear it up as @diracdeltas described

**Comment by rocky4-iv** [comment]
Re: diracdeltas & bridiver
Just to verify for deletion of: (./node_modules) I have 84 items listed in: /lib/node_modules/npm/node_modules
Should I delete the folder path indicated?

**Comment by bsclifton** [comment]
Closing this issue as it's been a while since there's been an update

@rocky4-iv please re-open this issue if you continue to have issues and the above advice (deleting the ~/.electron and node_modules folders) does not work. Thanks :smile:
