### ISSUE TITLE
about:error reloads the tab of the opener page

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#1908]
**Did you search for similar issues before submitting this one?**
yes

- Steps to reproduce:
    1. turn off wifi
    2. cmd-click link to open in a new tab
    3. turn wifi back on, then click the 'retry' button

the opener page reloads instead of the frame that about:error is loaded in

**Comment by diracdeltas** [comment]
though i just tried this again and got an error:
```
Uncaught Exception:
TypeError: Cannot read property 'send' of null
    at EventEmitter.ipcMain.on (/Applications/Brave.app/Contents/Resources/app.asar/app/index.js:315:31)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at EventEmitter.<anonymous> (/Applications/Brave.app/Contents/Resources/electron.asar/browser/api/web-contents.js:130:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

**Comment by luixxiul** [comment]
How about now?

**Comment by diracdeltas** [comment]
Yup still happens on master

**Comment by diracdeltas** [comment]
also happens on cert error pages if you switch the active tab before the cert error has fired; i think i have a fix though
