### ISSUE TITLE
MessageAttachmentSet destroyed with unconsumed descriptors: 0/1

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1979]
I get the following message on the console:

````
[2763:0530/164620:WARNING:ipc_message_attachment_set.cc(57)] MessageAttachmentSet destroyed with unconsumed descriptors: 0/1
ATTENTION: default value of option force_s3tc_enable overridden by environment.
TypeError: Error processing argument at index 0, conversion failure from null
    at TypeError (native)
    at Object.exports.init.err [as init] (/home/test/browser-laptop/app/updater.js:98:17)
    at PackageLoader.load (/home/test/browser-laptop/app/index.js:578:15)
    at fs.readFile (/home/test/browser-laptop/app/package-loader.js:16:5)
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
````

I'm not sure if this is an error, but I notice it for the first time. Restarting doesn't help.

- Platform (Win7, 8, 10? OS X? Linux distro?): Ubuntu 14.10

- Brave Version: Master branch

- Steps to reproduce:
    1. ``npm run watch``
    2. ``npm start``

Setting the milestone for now.

**Comment by luixxiul** [comment]
Duping to #1980
