### ISSUE TITLE
Error message should be more useful on app/updater.js:98

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#1980]
**Describe the issue you encountered:** Tabs crash. Also I get the following message on the console:

```
[6493:0530/171931:WARNING:x11_util.cc(1407)] X error received: serial 32, error_code 9 (BadDrawable (invalid Pixmap or Window parameter)), request_code 155, minor_code 7 (DRI2GetBuffersWithFormat )
TypeError: Error processing argument at index 0, conversion failure from null
    at TypeError (native)
    at Object.exports.init.err [as init] (/home/test/browser-laptop/app/updater.js:98:17)
    at PackageLoader.load (/home/test/browser-laptop/app/index.js:578:15)
    at fs.readFile (/home/test/browser-laptop/app/package-loader.js:16:5)
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
../../third_party/tcmalloc/chromium/src/free_list.h:118] Memory corruption detected. 
```

**Comment by bbondy** [comment]
0.10.2 since it isn't reproducible.

**Comment by luixxiul** [comment]
I'm doing fresh install and try again later.

**Comment by luixxiul** [comment]
It's fine now, though this error still persists:
````
TypeError: Error processing argument at index 0, conversion failure from null
    at TypeError (native)
    at Object.exports.init.err [as init] (/home/test/browser-laptop/app/updater.js:98:17)
    at PackageLoader.load (/home/test/browser-laptop/app/index.js:578:15)
    at fs.readFile (/home/test/browser-laptop/app/package-loader.js:16:5)
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
````

**Comment by diracdeltas** [comment]
`app/updater.js:98` is already in a try-catch block with a comment that it'll throw an error in dev mode. we could update the error message to be more useful, but this doesn't seem like a bug given that

**Comment by diracdeltas** [comment]
can this be closed/removed from the milestone?

**Comment by bbondy** [comment]
Removed from  milestone, you can close if you think there are no action items

**Comment by luixxiul** [comment]
Closing as stale.
