### ISSUE TITLE
Error: Failed to get path

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2198]
**Describe the issue you encountered:** ``npm start`` does not load the browser at all.

Here is the message on the terminal:

````
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Failed to get path
    at Error (native)
    at Object.<anonymous> (/home/test/browser-laptop/app/flash.js:11:41)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/test/browser-laptop/app/index.js:46:15)

````

- Platform (Win7, 8, 10? OS X? Linux distro?): Ubuntu 14.04, and Windows 10 per the comment by @bsclifton on slack.

- Brave Version: Master Branch (latest commit b4f0ff6)

**Comment by bbondy** [comment]
do you maybe need a fresh npm install?
I think you need Electron 1.2.2 for this to work.

**Comment by luixxiul** [comment]
Yes it worked, same as #1916. Closing.
