### ISSUE TITLE
Can't run `npm run-script watch` because of `webpack-dev-server`

### ISSUE THREAD

**Issue by Aidoboy** [brave/browser-laptop#229]
It give me this:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run-script', 'watch' ]
2 info using npm@2.14.12
3 info using node@v4.2.5
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info prewatch brave@0.7.7
6 info watch brave@0.7.7
7 verbose unsafe-perm in lifecycle true
8 info brave@0.7.7 Failed to exec watch script
9 verbose stack Error: brave@0.7.7 watch: `webpack-dev-server`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid brave@0.7.7
11 verbose cwd /home/aidan/Source/brave-browser-laptop
12 error Linux 4.2.0-23-generic
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run-script" "watch"
14 error node v4.2.5
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error brave@0.7.7 watch: `webpack-dev-server`
17 error Exit status 1
18 error Failed at the brave@0.7.7 watch script 'webpack-dev-server'.
18 error This is most likely a problem with the brave package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     webpack-dev-server
18 error You can get their info via:
18 error     npm owner ls brave
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

Anyone know what's up? I don't know anything about `webpack-dev-server`.

**Comment by hamidsafdari** [comment]
It does say so in the `README.md` to run `npm run watch` first and then `npm start`.
Run them in separate terminals.

**Comment by bridiver** [comment]
incorrect run-script docs are updated https://github.com/brave/browser-laptop/commit/f33f2eeeec16c525c470346a67fb6f147aa51074
Feel free to re-open if you have trouble when running ```npm run watch```

**Comment by Aidoboy** [comment]
@bridiver Since you closed it [\[citation\]](http://stackoverflow.com/a/21333938/1526048), I can't re-open it, but it's still broken:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'watch' ]
2 info using npm@2.14.12
3 info using node@v4.2.5
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info prewatch brave@0.7.7
6 info watch brave@0.7.7
7 verbose unsafe-perm in lifecycle true
8 info brave@0.7.7 Failed to exec watch script
9 verbose stack Error: brave@0.7.7 watch: `webpack-dev-server`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid brave@0.7.7
11 verbose cwd /home/aidan/Source/brave-browser-laptop
12 error Linux 4.2.0-23-generic
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "watch"
14 error node v4.2.5
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error brave@0.7.7 watch: `webpack-dev-server`
17 error Exit status 1
18 error Failed at the brave@0.7.7 watch script 'webpack-dev-server'.
18 error This is most likely a problem with the brave package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     webpack-dev-server
18 error You can get their info via:
18 error     npm owner ls brave
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by bridiver** [comment]
Ha, details... I have re-opened it for you :) I'm shooting in the dark a little here because we haven't built it on Linux, but as a first step I would try updating to node v5+ (specified in installation step 3 on the README, but should probably be more prominent). Do you have any additional log output?

**Comment by Aidoboy** [comment]
When I update to node 5, I get an error while building. Give me a minute.

**Comment by Aidoboy** [comment]
I got this: https://gist.github.com/Aidoboy/dbf6b5f6b5c84eaf5e12

**Comment by bridiver** [comment]
do you have node-gyp installed globally?

**Comment by Aidoboy** [comment]
```
/usr/lib
└─┬ npm@3.3.12
  ├── abbrev@1.0.7
  ├── ansi-regex@2.0.0
  ├── ansicolors@0.3.2
  ├── ansistyles@0.1.3
  ├── aproba@1.0.1
  ├── archy@1.0.0
  ├── async-some@1.0.2
  ├── chownr@1.0.1
  ├─┬ cmd-shim@2.0.1
  │ └── graceful-fs@3.0.8
  ├─┬ columnify@1.5.2
  │ └─┬ wcwidth@1.0.0
  │   └─┬ defaults@1.0.3
  │     └── clone@1.0.2
  ├─┬ config-chain@1.1.9
  │ └── proto-list@1.2.4
  ├── debuglog@1.0.1
  ├─┬ dezalgo@1.0.3
  │ └── asap@2.0.3
  ├── editor@1.0.0
  ├── fs-vacuum@1.2.7
  ├── fs-write-stream-atomic@1.0.4
  ├── fstream@1.0.8
  ├─┬ fstream-npm@1.0.5
  │ └─┬ fstream-ignore@1.0.2
  │   └─┬ minimatch@2.0.10
  │     └─┬ brace-expansion@1.1.1
  │       ├── balanced-match@0.2.0
  │       └── concat-map@0.0.1
  ├─┬ glob@5.0.15
  │ ├─┬ minimatch@3.0.0
  │ │ └─┬ brace-expansion@1.1.1
  │ │   ├── balanced-match@0.2.0
  │ │   └── concat-map@0.0.1
  │ └── path-is-absolute@1.0.0
  ├── graceful-fs@4.1.2
  ├── has-unicode@1.0.1
  ├── hosted-git-info@2.1.4
  ├── iferr@0.1.5
  ├── inflight@1.0.4
  ├── inherits@2.0.1
  ├── ini@1.3.4
  ├─┬ init-package-json@1.9.1
  │ └── promzard@0.3.0
  ├── lockfile@1.0.1
  ├── lodash._baseindexof@3.1.0
  ├── lodash._baseuniq@3.0.3
  ├── lodash._bindcallback@3.0.1
  ├── lodash._cacheindexof@3.0.2
  ├── lodash._createcache@3.1.2
  ├── lodash._getnative@3.9.1
  ├─┬ lodash.clonedeep@3.0.2
  │ └─┬ lodash._baseclone@3.3.0
  │   ├── lodash._arraycopy@3.0.0
  │   ├── lodash._arrayeach@3.0.0
  │   ├─┬ lodash._baseassign@3.2.0
  │   │ └── lodash._basecopy@3.0.1
  │   └── lodash._basefor@3.0.2
  ├── lodash.isarguments@3.0.4
  ├── lodash.isarray@3.0.4
  ├── lodash.keys@3.1.2
  ├── lodash.restparam@3.6.1
  ├─┬ lodash.union@3.1.0
  │ └── lodash._baseflatten@3.1.4
  ├─┬ lodash.uniq@3.2.2
  │ ├─┬ lodash._basecallback@3.3.1
  │ │ ├─┬ lodash._baseisequal@3.0.7
  │ │ │ └── lodash.istypedarray@3.0.2
  │ │ └── lodash.pairs@3.0.1
  │ └── lodash._isiterateecall@3.0.9
  ├─┬ lodash.without@3.2.1
  │ └── lodash._basedifference@3.0.3
  ├─┬ mkdirp@0.5.1
  │ └── minimist@0.0.8
  ├─┬ node-gyp@3.0.3
  │ ├─┬ glob@4.5.3
  │ │ └─┬ minimatch@2.0.10
  │ │   └─┬ brace-expansion@1.1.1
  │ │     ├── balanced-match@0.2.0
  │ │     └── concat-map@0.0.1
  │ ├─┬ minimatch@1.0.0
  │ │ ├── lru-cache@2.7.0
  │ │ └── sigmund@1.0.1
  │ ├─┬ path-array@1.0.0
  │ │ └─┬ array-index@0.1.1
  │ │   └─┬ debug@2.2.0
  │ │     └── ms@0.7.1
  │ └─┬ tar@1.0.3
  │   └── block-stream@0.0.8
  ├── nopt@3.0.4
  ├── normalize-git-url@3.0.1
  ├─┬ normalize-package-data@2.3.4
  │ └─┬ is-builtin-module@1.0.0
  │   └── builtin-modules@1.1.0
  ├── npm-cache-filename@1.0.2
  ├── npm-install-checks@2.0.1
  ├── npm-package-arg@4.0.2
  ├─┬ npm-registry-client@7.0.7
  │ └─┬ concat-stream@1.5.0
  │   ├─┬ readable-stream@2.0.2
  │   │ ├── core-util-is@1.0.1
  │   │ ├── isarray@0.0.1
  │   │ ├── process-nextick-args@1.0.3
  │   │ ├── string_decoder@0.10.31
  │   │ └── util-deprecate@1.0.2
  │   └── typedarray@0.0.6
  ├── npm-user-validate@0.1.2
  ├─┬ npmlog@1.2.1
  │ ├── ansi@0.3.0
  │ ├─┬ are-we-there-yet@1.0.4
  │ │ ├── delegates@0.1.0
  │ │ └─┬ readable-stream@1.1.13
  │ │   ├── core-util-is@1.0.1
  │ │   ├── isarray@0.0.1
  │ │   └── string_decoder@0.10.31
  │ └─┬ gauge@1.2.2
  │   ├─┬ lodash.pad@3.1.1
  │   │ ├── lodash._basetostring@3.0.1
  │   │ └─┬ lodash._createpadding@3.6.1
  │   │   └── lodash.repeat@3.0.1
  │   ├── lodash.padleft@3.1.1
  │   └── lodash.padright@3.1.1
  ├── once@1.3.2
  ├── opener@1.4.1
  ├─┬ osenv@0.1.3
  │ ├── os-homedir@1.0.1
  │ └── os-tmpdir@1.0.1
  ├── path-is-inside@1.0.1
  ├─┬ read@1.0.7
  │ └── mute-stream@0.0.5
  ├── read-cmd-shim@1.0.1
  ├─┬ read-installed@4.0.3
  │ └── util-extend@1.0.1
  ├─┬ read-package-json@2.0.1
  │ └─┬ json-parse-helpfulerror@1.0.3
  │   └── jju@1.2.1
  ├── read-package-tree@5.1.2
  ├── readdir-scoped-modules@1.0.2
  ├── realize-package-specifier@3.0.1
  ├─┬ request@2.65.0
  │ ├── aws-sign2@0.6.0
  │ ├─┬ bl@1.0.0
  │ │ └─┬ readable-stream@2.0.2
  │ │   ├── core-util-is@1.0.1
  │ │   ├── isarray@0.0.1
  │ │   ├── process-nextick-args@1.0.3
  │ │   ├── string_decoder@0.10.31
  │ │   └── util-deprecate@1.0.2
  │ ├── caseless@0.11.0
  │ ├─┬ combined-stream@1.0.5
  │ │ └── delayed-stream@1.0.0
  │ ├── extend@3.0.0
  │ ├── forever-agent@0.6.1
  │ ├─┬ form-data@1.0.0-rc3
  │ │ └── async@1.4.2
  │ ├─┬ har-validator@2.0.2
  │ │ ├─┬ chalk@1.1.1
  │ │ │ ├── ansi-styles@2.1.0
  │ │ │ ├── escape-string-regexp@1.0.3
  │ │ │ ├── has-ansi@2.0.0
  │ │ │ └── supports-color@2.0.0
  │ │ ├─┬ commander@2.9.0
  │ │ │ └── graceful-readlink@1.0.1
  │ │ ├─┬ is-my-json-valid@2.12.2
  │ │ │ ├── generate-function@2.0.0
  │ │ │ ├─┬ generate-object-property@1.2.0
  │ │ │ │ └── is-property@1.0.2
  │ │ │ ├── jsonpointer@2.0.0
  │ │ │ └── xtend@4.0.0
  │ │ └─┬ pinkie-promise@1.0.0
  │ │   └── pinkie@1.0.0
  │ ├─┬ hawk@3.1.0
  │ │ ├── boom@2.9.0
  │ │ ├── cryptiles@2.0.5
  │ │ ├── hoek@2.16.3
  │ │ └── sntp@1.0.9
  │ ├─┬ http-signature@0.11.0
  │ │ ├── asn1@0.1.11
  │ │ ├── assert-plus@0.1.5
  │ │ └── ctype@0.5.3
  │ ├── isstream@0.1.2
  │ ├── json-stringify-safe@5.0.1
  │ ├─┬ mime-types@2.1.7
  │ │ └── mime-db@1.19.0
  │ ├── node-uuid@1.4.3
  │ ├── oauth-sign@0.8.0
  │ ├── qs@5.2.0
  │ ├── stringstream@0.0.4
  │ ├── tough-cookie@2.2.0
  │ └── tunnel-agent@0.4.1
  ├── retry@0.8.0
  ├── rimraf@2.4.3
  ├── semver@5.0.3
  ├─┬ sha@2.0.1
  │ └─┬ readable-stream@2.0.2
  │   ├── core-util-is@1.0.1
  │   ├── isarray@0.0.1
  │   ├── process-nextick-args@1.0.3
  │   ├── string_decoder@0.10.31
  │   └── util-deprecate@1.0.2
  ├── slide@1.1.6
  ├── sorted-object@1.0.0
  ├── strip-ansi@3.0.0
  ├─┬ tar@2.2.1
  │ └── block-stream@0.0.8
  ├── text-table@0.2.0
  ├── uid-number@0.0.6
  ├── umask@1.1.0
  ├─┬ unique-filename@1.0.0
  │ └── unique-slug@1.0.0
  ├── unpipe@1.0.0
  ├─┬ validate-npm-package-license@3.0.1
  │ ├─┬ spdx-correct@1.0.1
  │ │ └── spdx-license-ids@1.0.2
  │ └─┬ spdx-expression-parse@1.0.0
  │   └── spdx-exceptions@1.0.3
  ├─┬ validate-npm-package-name@2.2.2
  │ └── builtins@0.0.7
  ├─┬ which@1.2.0
  │ └─┬ is-absolute@0.1.7
  │   └── is-relative@0.1.3
  ├── wrappy@1.0.1
  └── write-file-atomic@1.1.3
```

**Comment by Aidoboy** [comment]
It's in there

**Comment by bbondy** [comment]
I think you need v3.2.1 of node-gyp

**Comment by Aidoboy** [comment]
Updated node-gyp, but I'm still getting the same error.

**Comment by Aidoboy** [comment]
Got it installed on Node 5 by using `sudo npm install --unsafe-perm` from #214, but I'm getting the original error again.

**Comment by bridiver** [comment]
What Linux distribution/version are you using? I'll see if I can replicate

**Comment by Aidoboy** [comment]
Ubuntu 15.10

On Mon, Jan 25, 2016, 11:33 AM Brian Johnson <notifications@github.com>
wrote:

> What Linux distribution/version are you using? I'll see if I can replicate
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brave/browser-laptop/issues/229#issuecomment-174595946>
> .
>
-- 

“Listen to the mustn'ts, child. Listen to the don'ts. Listen to the
shouldn'ts, the impossibles, the won'ts. Listen to the never haves, then
listen close to me... Anything can happen, child. Anything can be.” ~Shel
Silverstein

**Comment by Aidoboy** [comment]
I got arpund this by using 'npm run build-package', but now I guess I don't get debug output.

**Comment by luixxiul** [comment]
@bridiver maybe closing again?

**Comment by bridiver** [comment]
Yea, I'm going to go ahead and close. We've made a lot of updates since Jan 26 and we test on Ubuntu.
