### ISSUE TITLE
cannot run multiple instances of pdfjs at once

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#2619]
if an instance of Brave is already running on OS X and i try to start another one, i see a console error:
```
 [59216:0720/170245:INFO:CONSOLE(0)] "Error in response to storage.get: TypeError: Cannot read property 'featureDetectLastUA' of undefined
    at Object.callback (chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/feature-detect.js:30:15)
    at chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/feature-detect.js:28:22", source: chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/pdfHandler.html (0)
[59216:0720/170245:INFO:CONSOLE(0)] "Unchecked runtime.lastError while running storage.get: IO error: .../LOCK: No further details. (ChromeMethodBFE: 15::LockFile::1)
    at chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/feature-detect.js:28:22", source: chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/pdfHandler.html (0)
[59216:0720/170248:WARNING:session_storage_database.cc(349)] Failed to open leveldb in /path/brave/Session Storage, error: IO error: /path/brave/Session Storage/LOCK: No further details. (ChromeMethodBFE: 15::LockFile::1)
```

**Comment by diracdeltas** [comment]
probably not a problem except for devs
