### ISSUE TITLE
Brave's S3 bucket for brave/electron prebuilt dependency binaries is private

### ISSUE THREAD

**Issue by willy-b** [brave/browser-laptop#2899]
(Note: This is an issue for `brave/electron`, but that repo does not allow issues so I am posting it here. I will not be offended if you delete without reply)

When doing a minimal build of `brave/electron`, the script attempts to download Brave's prebuilt binary for `libchromiumcontent` and other dependencies, but can't due to the buckets being private, e.g. ` `https://s3.amazonaws.com/brave-laptop-binaries/libchromiumcontent.

Here's a screenshot showing response from AWS if URL is accessed in browser:
![s3_brave-laptop-binaries_403_libchromiumcontent-zip](https://cloud.githubusercontent.com/assets/6969859/17355718/64bbf7ae-5907-11e6-8691-efd028a6a3c7.png)

If the bucket was not private then developers could test simple JS changes to Brave's Electron without rebuilding everything (which takes 25GB and a lot of time).

Thanks!

**Comment by willy-b** [comment]
A little more detail. 
This means that if a developer runs the bootstrap and build scripts for `brave/electron` as laid out in the docs they will get a permission error.

After running `./script/bootstrap.py`, when I run `build.py` I get the following error:
```
 ./script/build.py -v --dev
[...]
/usr/bin/python /home/willy/projs/git/3rd/brave/electron/vendor/brightray/script/bootstrap --dev --commit de868695083d30cdfe5adb07793a8d7ccb57f8d8 --target_arch x64 https://s3.amazonaws.com/brave-laptop-binaries/libchromiumcontent
Downloading libchromiumcontent.zip...
https://s3.amazonaws.com/brave-laptop-binaries/libchromiumcontent/linux/x64/de868695083d30cdfe5adb07793a8d7ccb57f8d8/libchromiumcontent.zip
Traceback (most recent call last):
  File "/home/willy/projs/git/3rd/brave/electron/vendor/brightray/vendor/libchromiumcontent/script/download", line 180, in <module>
    sys.exit(main())
  File "/home/willy/projs/git/3rd/brave/electron/vendor/brightray/vendor/libchromiumcontent/script/download", line 61, in main
    args.force)
  File "/home/willy/projs/git/3rd/brave/electron/vendor/brightray/vendor/libchromiumcontent/script/download", line 126, in download_if_needed
    download(destination, base_url, commit, filename)
  File "/home/willy/projs/git/3rd/brave/electron/vendor/brightray/vendor/libchromiumcontent/script/download", line 136, in download
    download_and_extract(destination, url)
  File "/home/willy/projs/git/3rd/brave/electron/vendor/brightray/vendor/libchromiumcontent/script/download", line 149, in download_and_extract
    with contextlib.closing(urllib2.urlopen(url)) as u:
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>
Traceback (most recent call last):
  File "/home/willy/projs/git/3rd/brave/electron/vendor/brightray/script/bootstrap", line 98, in <module>
    sys.exit(main())
  File "/home/willy/projs/git/3rd/brave/electron/vendor/brightray/script/bootstrap", line 31, in main
    args.libcc_static_library_path)
  File "/home/willy/projs/git/3rd/brave/electron/vendor/brightray/script/bootstrap", line 84, in setup_libchromiumcontent
    subprocess.check_call([sys.executable, download] + args)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '/home/willy/projs/git/3rd/brave/electron/vendor/brightray/vendor/libchromiumcontent/script/download', '-f', '-c', 'de868695083d30cdfe5adb07793a8d7ccb57f8d8', '--target_arch', 'x64', 'https://s3.amazonaws.com/brave-laptop-binaries/libchromiumcontent', '/home/willy/projs/git/3rd/brave/electron/vendor/brightray/vendor/download/libchromiumcontent']' returned non-zero exit status 1
None
Traceback (most recent call last):
  File "./script/bootstrap.py", line 263, in <module>
    sys.exit(main())
  File "./script/bootstrap.py", line 61, in main
    libcc_static_library_path)
  File "./script/bootstrap.py", line 153, in bootstrap_brightray
    execute_stdout([sys.executable, bootstrap] + args)
  File "/home/willy/projs/git/3rd/brave/electron/script/lib/util.py", line 177, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['/usr/bin/python', '/home/willy/projs/git/3rd/brave/electron/vendor/brightray/script/bootstrap', '--dev', '--commit', 'de868695083d30cdfe5adb07793a8d7ccb57f8d8', '--target_arch', 'x64', 'https://s3.amazonaws.com/brave-laptop-binaries/libchromiumcontent']' returned non-zero exit status 1
```
Note the S3 bucket URL, which is configured in `./script/lib/config.py`.

**Comment by bbondy** [comment]
we're going to be changing it so that browser-laptop includes electron in its build to avoid things like this.

**Comment by bridiver** [comment]
everything should be world readable now

**Comment by willy-b** [comment]
Confirmed, I can access the `brave-laptop-binaries` bucket now, thanks!
