### ISSUE TITLE
A JavaScript error occurred in the main process - Error: libgnome-keyring.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by msiyer** [brave/browser-laptop#2910]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Followed the following steps to download and extract latest binaries on Arch Linux desktop:

> wget -O brave.tar.bz2 https://laptop-updates.brave.com/latest/linux64
> tar xvjf brave.tar.bz2  

Tried launching the **brave** executable. Encountered following exception:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libgnome-keyring.so.0: cannot open shared object file: No such file or directory
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/msiyer/Brave-linux-x64/resources/app.asar/node_modules/keytar/lib/keytar.js:4:12)
```

**Expected behavior:**
**brave** executable should launch.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Arch Linux (4.6.4-1-ARCH), Xfce DM

- Brave Version:
0.11.1

**Comment by willy-b** [comment]
Is `libgnome-keyring` installed?

Maybe try `pacman -S libgnome-keyring`.

I haven't tried Arch Linux yet, but if that doesn't work I can grab a VM and try to figure it out.

**Comment by msiyer** [comment]
Installed `libgnome-keyring` and **brave** launches. I am adding this comment using **brave**. However, It still prints an error at terminal:

> TypeError: Error processing argument at index 0, conversion failure from null
>     at TypeError (native)
>     at Object.exports.init.err [as init] (/home/msiyer/Brave-linux-x64/resources/app.asar/app/updater.js:98:17)
>     at PackageLoader.load (/home/msiyer/Brave-linux-x64/resources/app.asar/app/index.js:648:15)
>     at fs.readFile (/home/msiyer/Brave-linux-x64/resources/app.asar/app/package-loader.js:16:5)
>     at ELECTRON_ASAR.js:416:16
>     at FSReqWrap.wrapper [as oncomplete] (fs.js:675:17)

Are we supposed to have external dependencies?

**Comment by luixxiul** [comment]
Hi @msiyer, I also noticed it and reported it in #1980.

Making portable versions sounds nice. Would you please open an issue for that? (Still I don't think it would be ready until 1.0 at least). Closing this issue.

**Comment by msiyer** [comment]
sure @luixxiul, I will open an issue for the portable version. Thanks for your time.

**Comment by daharper** [comment]
Hello, not sure if I should mention this here, but just want to let you know that I'm getting the same error running KDE neon (KDE Plasma Version 5.8.4, KDE Frameworks 5.29.0, Kernerl 4.4.0.47-generic):

An uncaught exception occurred in the main process Uncaught Exception:
Error: libgnome-keyring.so.0: cannot open shared object file: No such file or directory
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:182:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/brave/resources/app.asar/node_modules/keytar/lib/keytar.js:4:12)
