### ISSUE TITLE
Win7 Brave will not open right after an update.

### ISSUE THREAD

**Issue by markgif** [brave/browser-laptop#3019]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Allowed Brave to update, after it prompted me. After the update Brave did not restart. I started it manually, the Brave window appeared for a moment with no content, then disappeared. Tried it again, same behavior. Window appears then disappears. Brave is not in Task Manager Applications tab or Processes tab.

**Expected behavior:**
Brave should open and stay open.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win7 64-bit.

- Brave Version:
Can't tell anymore because it won't open, but it just installed an update today, 6 Aug 2016.

- Steps to reproduce:
    1. Double-click Brave icon.
    2. Watch window appear for a couple seconds, then disappear.
    3. Wince, cry, etc.

- Screenshot if needed:
n/a

- Any related issues:
no

**Comment by markgif** [comment]
I tried shutting down and rebooting the computer, same problem. So I uninstalled Brave. Then I downloaded Brave again and installed it, and it's the same problem. Brave opens and then closes a couple seconds later with no notifications. Too bad, I liked using it.

**Comment by markgif** [comment]
I was curious so I tried opening Brave again the next day without changing anything, no reboot. And now it works fine. No problems. It says it is version 0.11.3. So I guess I'll close this! Thanks.

**Comment by bsclifton** [comment]
Sometimes you need to wince and cry a bit :stuck_out_tongue: In all seriousness, I have had issued where the install has failed and I had to uninstall, reboot, then re-install.

If this does happen again, please be sure to revisit this issue with as much info as you can capture and we'll check it out :smile:

**Comment by markgif** [comment]
Thanks! If it helps, Below is what my SquirrelSetup.log looks like now with a normally operating Brave.
------------
2016-08-06 18:10:11> Program: Starting Squirrel Updater: --createShortcut=Brave.exe
2016-08-06 18:10:11> ApplyReleasesImpl: About to create shortcuts for Brave.exe, rootAppDir C:\Users\Mark\AppData\Local\brave
2016-08-06 18:10:11> ApplyReleasesImpl: Creating shortcut for Brave.exe => C:\Users\Mark\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Brave Inc.\Brave.lnk
2016-08-06 18:10:12> ApplyReleasesImpl: About to save shortcut: C:\Users\Mark\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Brave Inc.\Brave.lnk (target C:\Users\Mark\AppData\Local\brave\Update.exe, workingDir C:\Users\Mark\AppData\Local\brave\app-0.11.3, args --processStart "Brave.exe")
2016-08-06 18:10:12> ApplyReleasesImpl: Creating shortcut for Brave.exe => C:\Users\Mark\Desktop\Brave.lnk
2016-08-06 18:10:12> ApplyReleasesImpl: About to save shortcut: C:\Users\Mark\Desktop\Brave.lnk (target C:\Users\Mark\AppData\Local\brave\Update.exe, workingDir C:\Users\Mark\AppData\Local\brave\app-0.11.3, args --processStart "Brave.exe")
2016-08-06 18:10:36> Program: Starting Squirrel Updater: --processStart Brave.exe
2016-08-06 18:10:36> Program: Want to launch 'C:\Users\Mark\AppData\Local\brave\app-0.11.3\Brave.exe'
2016-08-06 18:10:36> Program: About to launch: 'C:\Users\Mark\AppData\Local\brave\app-0.11.3\Brave.exe': 
2016-08-07 13:36:21> Program: Starting Squirrel Updater: --processStart Brave.exe
2016-08-07 13:36:21> Program: Want to launch 'C:\Users\Mark\AppData\Local\brave\app-0.11.3\Brave.exe'
2016-08-07 13:36:21> Program: About to launch: 'C:\Users\Mark\AppData\Local\brave\app-0.11.3\Brave.exe': 
2016-08-07 14:12:49> Program: Starting Squirrel Updater: --processStart Brave.exe
2016-08-07 14:12:49> Program: Want to launch 'C:\Users\Mark\AppData\Local\brave\app-0.11.3\Brave.exe'
2016-08-07 14:12:49> Program: About to launch: 'C:\Users\Mark\AppData\Local\brave\app-0.11.3\Brave.exe': 
2016-08-09 22:20:46> Program: Starting Squirrel Updater: --processStart Brave.exe
2016-08-09 22:20:47> Program: Want to launch 'C:\Users\Mark\AppData\Local\brave\app-0.11.3\Brave.exe'
2016-08-09 22:20:47> Program: About to launch: 'C:\Users\Mark\AppData\Local\brave\app-0.11.3\Brave.exe': 
2016-08-10 09:45:15> Program: Starting Squirrel Updater: --download https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64
2016-08-10 09:45:15> Program: Fetching update information, downloading from https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64
2016-08-10 09:45:16> CheckForUpdateImpl: Generated new staging user ID: 1df03405-9f86-55c3-bd89-9f2b8c64ab90
2016-08-10 09:45:16> CheckForUpdateImpl: Downloading RELEASES file from https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64
2016-08-10 09:45:18> FileDownloader: Downloading url: https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64/RELEASES?id=brave&localVersion=0.11.3&arch=amd64
2016-08-10 09:45:25> FileDownloader: Downloading file: https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64/brave-0.11.4-full.nupkg
2016-08-10 09:55:23> UpdateInfo: Couldn't get release notes for:brave-0.11.4-full.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\Mark\AppData\Local\brave\packages\brave-0.11.4-full.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
2016-08-10 09:55:24> Program: Starting Squirrel Updater: --update https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64
2016-08-10 09:55:24> Program: Starting update, downloading from https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64
2016-08-10 09:55:24> Program: About to update to: C:\Users\Mark\AppData\Local\brave
2016-08-10 09:55:24> CheckForUpdateImpl: Using existing staging user ID: 1df03405-9f86-55c3-bd89-9f2b8c64ab90
2016-08-10 09:55:24> CheckForUpdateImpl: Downloading RELEASES file from https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64
2016-08-10 09:55:24> FileDownloader: Downloading url: https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64/RELEASES?id=brave&localVersion=0.11.3&arch=amd64
2016-08-10 09:55:31> FileDownloader: Downloading file: https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64/brave-0.11.4-full.nupkg
2016-08-10 10:05:26> ApplyReleasesImpl: Writing files to app directory: C:\Users\Mark\AppData\Local\brave\app-0.11.4
2016-08-10 10:05:38> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Mark\AppData\Local\brave\app-0.11.4\Brave.exe]
2016-08-10 10:05:39> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-08-10 10:05:39> ApplyReleasesImpl: Fixing up tray icons
2016-08-10 10:05:39> ApplyReleasesImpl: cleanDeadVersions: for version 0.11.4
2016-08-10 10:05:39> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.11.3
2016-08-10 10:05:39> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.11.4
2016-08-10 12:21:45> Program: Starting Squirrel Updater: --processStartAndWait Brave.exe
2016-08-10 12:21:45> Program: Want to launch 'C:\Users\Mark\AppData\Local\brave\app-0.11.4\Brave.exe'
2016-08-10 12:21:45> Program: About to wait for parent PID 12608
2016-08-10 12:21:45> Program: About to launch: 'C:\Users\Mark\AppData\Local\brave\app-0.11.4\Brave.exe': 

----------
end log
