### ISSUE TITLE
NPM START FILED

### ISSUE THREAD

**Issue by fall9100** [brave/browser-laptop#339]
fall@Fall:~/Downloads/browser-laptop-0.7.8$ npm start

> brave@0.7.8 start /home/fall/Downloads/browser-laptop-0.7.8
> node ./tools/start.js --debug=5858 -enable-logging --v=0 --enable-dcheck

electron "/home/fall/Downloads/browser-laptop-0.7.8" --debug=5858
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/fall/Downloads/browser-laptop-0.7.8/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/home/fall/Downloads/browser-laptop-0.7.8/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)

**Comment by rblasett** [comment]
i'm getting the same error on OSX El Capitan

**Comment by rblasett** [comment]
And on OSX Yosemite too. (tried a different machine)

**Comment by rob-blasetti** [comment]
foudn the issue, you have to do `npm run watch` in one tab to start the server, then `npm start` in another

**Comment by bbondy** [comment]
Great, I'll close this issue in that case.
