### ISSUE TITLE
Brave crashes when opening Settings page

### ISSUE THREAD

**Issue by Sh1d0w** [brave/browser-laptop#3737]
**Describe the issue you encountered:**
Upon opening the Settings page Brave crashes every time.

**Expected behavior:**

Brave should not crash when I open the settings page.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux, Fedora 24

- Brave Version:
0.12.0dev

- Steps to reproduce:
    1. Open Brave
    2. Open Settings from the hamburger menu
    3. Crash

- Screenshot if needed:

- Any related issues: #3625

Video STR:
http://webm.land/media/ifEK.webm

Log:

```
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Insufficient number of arguments.
    at TypeError (native)
    at EventEmitter.ipc.on (/usr/share/brave/resources/app.asar/app/ledger.js:165:54)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/usr/share/brave/resources/electron.asar/browser/api/web-contents.js:209:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
/usr/share/brave/resources/app.asar/node_modules/node-anonize2-relic-emscripten/anonize2.js:18
if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKE

TypeError: Insufficient number of arguments.
    at TypeError (native)
    at EventEmitter.ipc.on (/usr/share/brave/resources/app.asar/app/ledger.js:165:54)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/usr/share/brave/resources/electron.asar/browser/api/web-contents.js:209:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```

cc @bbondy @bridiver

**Comment by Sh1d0w** [comment]
Fixed by reinstalling the deps.
