### ISSUE TITLE
Cannot find module 'npmlog' while using npm command

### ISSUE THREAD

**Issue by shahbaz17** [brave/browser-laptop#376]
module.js:341
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:20:13
    at Object.<anonymous> (/usr/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

Can anyone help me to solve this error.
Using Ubuntu
3.19.0-47-generic #53~14.04.1-Ubuntu

**Comment by serv** [comment]
Can you let us know what you get when run these two?

```
$ node -v
$ npm -v
```

**Comment by shahbaz17** [comment]
Hello @serv 
$ node -v 
v5.5.0
$ npm -v
module.js:341
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:20:13
    at Object.<anonymous> (/usr/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

**Comment by julianusti** [comment]
I have the same issue

**Comment by Emaren** [comment]
I have the same issue
node -v 5.10.0

➜  node_modules npm install -g generator-ionic
module.js:341
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:20:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
➜  node_modules node -v
v5.10.0
➜  node_modules npm -v
module.js:341
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:20:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

**Comment by luixxiul** [comment]
That was the issue of npm and should be fixed by building it from source code following https://github.com/tj/n/issues/101#issuecomment-15090791. If not please leave a log, closing.
