### ISSUE TITLE
Brave not working on Debian Wheeze because off GLIBC_2.14' not found

### ISSUE THREAD

**Issue by ZaphodBeeblebroks** [brave/browser-laptop#3925]
When starting Brave on Debian Wheezy this happens:

g@debianG:~$ brave
An uncaught exception occurred in the main process Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/.org.chromium.Chromium.U91dvk)
    at Error (native)
    at process.module.(anonymous function) [as dlopen](ELECTRON_ASAR.js:167:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node](ELECTRON_ASAR.js:181:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/brave/resources/app.asar/app/trackingProtection.js:8:58)
Process failed to load within 60 seconds
g@debianG:~$ 

Brave version: brave_0.12.0_amd64.deb
Debian Wheezy has  GLIBC_2.13-38

Z.Beeblebrox.

**Comment by luixxiul** [comment]
On the latest Debian the browser should work.
