### ISSUE TITLE
Cannot find module 'abp-filter-parser-cpp' - v0.12.5dev-RC1 - MacOS

### ISSUE THREAD

**Issue by ttilley** [brave/browser-laptop#4779]
While attempting to play with and learn brave, I encountered this error despite the package being installed in node_modules and built correctly. I followed the instructions in the readme and am at commit `c1ddef32c7c0877084568b830c0894130bdcbc8f (HEAD -> refs/heads/master, tag: refs/tags/v0.12.5dev-RC1, refs/remotes/origin/master, refs/remotes/origin/dev-channel, refs/remotes/origin/HEAD)`. 

```
Aya:browser-laptop ttilley$ npm start

> brave@0.12.5 start /Users/ttilley/code/github/browser-laptop
> node ./tools/start.js --debug=5858 --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck

App threw an error during load
Error: Cannot find module 'abp-filter-parser-cpp'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/ttilley/code/github/browser-laptop/node_modules/electron-prebuilt/dist/Brave.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ttilley/code/github/browser-laptop/app/adBlock.js:8:28)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
An uncaught exception occurred in the main process Uncaught Exception:
Error: Cannot find module 'abp-filter-parser-cpp'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/ttilley/code/github/browser-laptop/node_modules/electron-prebuilt/dist/Brave.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ttilley/code/github/browser-laptop/app/adBlock.js:8:28)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
Waiting 60 seconds for process to load
^Cprocess exited with code null

Aya:browser-laptop ttilley$ ls node_modules/abp-filter-parser-cpp/build/
Debug     abp-filter-parser-cpp.target.mk  config.gypi
Makefile  binding.Makefile                 gyp-mac-tool
Aya:browser-laptop ttilley$ ls node_modules/abp-filter-parser-cpp/build/Debug/
abp-filter-parser-cpp.node  obj.target
```

Requiring the node file directly works, but even in the interactive shell I cannot require by module name...

```
Aya:browser-laptop ttilley$ ./node_modules/electron-prebuilt/dist/Brave.app/Contents/MacOS/Brave -i
> require('abp-filter-parser-cpp')
Error: Cannot find module 'abp-filter-parser-cpp'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/ttilley/code/github/browser-laptop/node_modules/electron-prebuilt/dist/Brave.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at repl:1:1
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at REPLServer.defaultEval (repl.js:315:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
> require('./node_modules/abp-filter-parser-cpp/build/Debug/abp-filter-parser-cpp.node')
{ ABPFilterParser: [Function: ABPFilterParser],
  FilterOptions:
   { noFilterOption: 0,
     script: 1,
     image: 2,
     stylesheet: 4,
     object: 8,
     xmlHttpRequest: 16,
     objectSubrequest: 32,
     subdocument: 64,
     document: 128,
     other: 256,
     xbl: 512,
     collapse: 1024,
     doNotTrack: 2048,
     elemHide: 4096,
     thirdParty: 8192,
     notThirdParty: 16384 } }
>
```

So... what obvious thing am I missing here?

**Comment by ttilley** [comment]
of course the prebuilt electron isn't a Debug build. ::facepalm::
