### ISSUE TITLE
An uncaught exception occurred in the main process - Cannot find module 'speedometer'

### ISSUE THREAD

**Issue by msiyer** [brave/browser-laptop#5855]
**Did you search for similar issues before submitting this one?**
Yes. No prior issue.

**Describe the issue you encountered:**
The build was successful and I tried to launch brave from the dev package (**not** rpm install and launch). I see this:
```
An uncaught exception occurred in the main process Uncaught Exception:
Error: Cannot find module 'speedometer'
```

I did `npm install speedometer` and also, `dnf install nodejs-speedometer`, but no success.

**Expected behavior:**
brave should launch

- Platform (Win7, 8, 10? macOS? Linux distro?):
Fedora 25

- Brave Version:
brave@0.12.10

Detailed terminal output:
```
An uncaught exception occurred in the main process Uncaught Exception:
Error: Cannot find module 'speedometer'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/home/msiyer/workspace/browser-laptop/Brave-linux-x64/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/msiyer/workspace/browser-laptop/Brave-linux-x64/resources/app.asar/node_modules/webtorrent/index.js:19:19)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
Waiting 60 seconds for process to load
/home/msiyer/workspace/browser-laptop/Brave-linux-x64/resources/app.asar/node_modules/node-anonize2-relic-emscripten/anonize2.js:18
if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVI

Error: Cannot find module 'speedometer'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/home/msiyer/workspace/browser-laptop/Brave-linux-x64/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/msiyer/workspace/browser-laptop/Brave-linux-x64/resources/app.asar/node_modules/webtorrent/index.js:19:19)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)filed

```

**Comment by dcposch** [comment]
this looks like the Linux version of #5849 

should be fixed now!

**Comment by msiyer** [comment]
Updated repository and brave launches bravely.
