### ISSUE TITLE
MacOS 10.10.5: Javascript error when I try to enter a website

### ISSUE THREAD

**Issue by SpikeShape** [brave/browser-laptop#588]
Just pulled the recent changes and compiled. Opened the browser and it re-opened my recent tabs and instantly crashed:

```
A JavaScript error occured in the main process
Uncaught Exception:
TypeError: Wrong number of arguments
    at TypeError (native)
    at Array.Filtering.registerFilteringCB (/Users/rodger/Projects/browser-laptop/Brave-darwin-x64/Brave.app/Contents/Resources/app.asar/app/trackingProtection.js:49:26)
    at Function.<anonymous> (/Users/rodger/Projects/browser-laptop/Brave-darwin-x64/Brave.app/Contents/Resources/app.asar/app/filtering.js:36:43)
```

Closing and re-opening the browser and accessing another website does not help. The message disappears once I hit the OK button several times but it wont load the page I tried to enter.

**Comment by psimyn** [comment]
Duplicate of https://github.com/brave/browser-laptop/issues/556

> you should remove and re npm install your node_modules/tracking-protection

**Comment by SpikeShape** [comment]
Ah sorry. I didn't see that. Going to try that, thanks.
