### ISSUE TITLE
Remaining Linux crashes and nits for 54

### ISSUE THREAD

**Issue by posix4e** [brave/browser-laptop#6091]
-- Crashes these are blockers
[ ] When trying to use the local password store I get
```

```

-- Nits
[ ] Not implemented reached in static bool blink::PlatformKeyboardEvent::currentCapsLockState()
[ ] 
 ``` [5453:5453:1208/095056:ERROR:CONSOLE(219)] "Uncaught Error: Could not call remote function 'isFocused'. Check that the function signature is correct. Underlying error: Object has been destroyed
Error: Could not call remote function 'isFocused'. Check that the function signature is correct. Underlying error: Object has been destroyed
    at callFunction (/usr/share/brave/resources/electron.asar/browser/rpc-server.js:226:11)
    at EventEmitter.<anonymous> (/usr/share/brave/resources/electron.asar/browser/rpc-server.js:319:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/usr/share/brave/resources/electron.asar/browser/api/web-contents.js:181:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)", source: extensions::remote (219)
[5453:5453:1208/095057:ERROR:CONSOLE(219)] "Uncaught Error: Could not call remote function 'isFocused'. Check that the function signature is correct. Underlying error: Object has been destroyed
Error: Could not call remote function 'isFocused'. Check that the function signature is correct. Underlying error: Object has been destroyed
    at callFunction (/usr/share/brave/resources/electron.asar/browser/rpc-server.js:226:11)
    at EventEmitter.<anonymous> (/usr/share/brave/resources/electron.asar/browser/rpc-server.js:319:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/usr/share/brave/resources/electron.asar/browser/api/web-contents.js:181:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)", source: extensions::remote (219)
[5453:5453:1208/095226:ERROR:CONSOLE(219)] "Uncaught Error: Could not call remote function 'isFocused'. Check that the function signature is correct. Underlying error: Object has been destroyed
Error: Could not call remote function 'isFocused'. Check that the function signature is correct. Underlying error: Object has been destroyed
    at callFunction (/usr/share/brave/resources/electron.asar/browser/rpc-server.js:226:11)
    at EventEmitter.<anonymous> (/usr/share/brave/resources/electron.asar/browser/rpc-server.js:319:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/usr/share/brave/resources/electron.asar/browser/api/web-contents.js:181:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)", source: extensions::remote (219)

**Comment by posix4e** [comment]
I am going to break these up

**Comment by luixxiul** [comment]
I labelled `QA/no qa needed` as there is no commits linked to this.
