### ISSUE TITLE
Clicking print/save on about:preferences#payments causes a crash on cr54

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6150]
**Describe the issue you encountered:** Clicking print/save on about:preferences#payments causes a crash on chromium54

````
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'then' of undefined
    at fs.writeFile (/Users/Suguru/browser-laptop/app/ledger.js:269:44)
    at FSReqWrap.oncomplete (fs.js:111:15)
/Users/Suguru/browser-laptop/node_modules/node-anonize2-relic-emscripten/anonize2.js:18
if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;ENVIR

TypeError: Cannot read property 'then' of undefined
    at fs.writeFile (/Users/Suguru/browser-laptop/app/ledger.js:269:44)
    at FSReqWrap.oncomplete (fs.js:111:15)
process exited with code 7
````

**Expected behavior:** It should open the new tab with the dialog for print/save the key file

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: b824ae6453bb90d0863039e4e374cc67d40715fc

- Steps to reproduce:
    1. Open about:preferences#payments
    2. Click "Advanced Settings..."
    3. Click "Backup your wallet"
    4. Click print/save

- Any related issues:

CC @mrose17

**Comment by bbondy** [comment]
I'll fix

**Comment by bbondy** [comment]
It was crashing because it was treating this api as a promise but really it uses callbacks.

Note that the print operation won't actually work until #6159 is addressed.

**Comment by luixxiul** [comment]
Test plan: 
Open about:preferences#payments
Click "Advanced Settings..."
Click "Backup your wallet"
Click print/save
