### ISSUE TITLE
Brave not running node.js error ENONET in spellchecker

### ISSUE THREAD

**Issue by avner-solomon** [brave/browser-laptop#6609]
Platform win 10

Brave 0.12.15

Brave fails to start
An uncaught exception occurred in the main process Uncaught Exception:
Error: ENOENT, node_modules\keytar\build\Release\keytar.node not found in C:\Users\RavenX86\AppData\Local\brave\app-0.12.15\resources\app.asar
    at notFoundError (ELECTRON_ASAR.js:110:19)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:178:9)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\RavenX86\AppData\Local\brave\app-0.12.15\resources\app.asar\node_modules\keytar\lib\keytar.js:4:12)
    at Object.<anonymous> (C:\Users\RavenX86\AppData\Local\brave\app-0.12.15\resources\app.asar\node_modules\keytar\lib\keytar.js:58:4)
    at Module._compile (module.js:556:32)
Waiting 60 seconds for process to load
Process failed to load within 60 seconds

**Comment by Liunkae** [comment]
Could you please try moving the Brave AppData folder?

1. Look for the following folder: `C:\Users\Username\AppData\Local\brave`
2. Rename the `brave` folder to something else (e.g., `brave2`)
3. Open Brave again

**Comment by avner-solomon** [comment]
I still keep randomly getting this error

**Comment by luixxiul** [comment]
@avner-solomon will you please follow these steps to see if it's fixed? https://community.brave.com/t/how-to-solve-almost-every-problem-after-install/605
