### ISSUE TITLE
automated test failures: Payments Panel

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#6890]
**Describe the issue you encountered:**

https://travis-ci.org/brave/browser-laptop/builds/195784610#L4331

- [ ]  3) Payments Panel -> Advanced Panel can backup wallet to file:
     WaitUntilTimeoutError: Promise was rejected with the following reason: AssertionError: 'about:' == 'file:'
      at getValue("#urlInput") - ledgerPanelAdvancedPanelTest.js:161:21

- [ ]  4) Payments Panel -> Advanced Panel shows an error popover if one recovery key is missing:
     TypeError: path must be a string or Buffer
      at TypeError (native)
      at Object.fs.openSync (fs.js:634:18)
      at Object.fs.writeFileSync (fs.js:1327:33)
      at generateAndSaveRecoveryFile (test/components/ledgerPanelAdvancedPanelTest.js:128:6)
      at Context.<anonymous> (test/components/ledgerPanelAdvancedPanelTest.js:199:5)
      at next (native)
      at onFulfilled (node_modules/co-mocha/node_modules/co/index.js:65:19)
      at new Promise (node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:191:7)
      at Context.co (node_modules/co-mocha/node_modules/co/index.js:50:10)
      at Context.createPromise (node_modules/co-mocha/node_modules/co/index.js:30:15)
      at Test.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)
      at run (node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:87:22)
      at node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:100:28
      at flush (node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

- [ ]  5) Payments Panel -> Advanced Panel shows an error popover if a recovery key is not a UUID:
     TypeError: path must be a string or Buffer
      at TypeError (native)
      at Object.fs.openSync (fs.js:634:18)
      at Object.fs.writeFileSync (fs.js:1327:33)
      at generateAndSaveRecoveryFile (test/components/ledgerPanelAdvancedPanelTest.js:128:6)
      at Context.<anonymous> (test/components/ledgerPanelAdvancedPanelTest.js:206:5)
      at next (native)
      at onFulfilled (node_modules/co-mocha/node_modules/co/index.js:65:19)
      at node_modules/co-mocha/node_modules/co/index.js:54:5
      at new Promise (node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:191:7)
      at Context.co (node_modules/co-mocha/node_modules/co/index.js:50:10)
      at Context.createPromise (node_modules/co-mocha/node_modules/co/index.js:30:15)
      at Test.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)
      at run (node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:87:22)
      at node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:100:28
      at flush (node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
  
- [ ] 6) Payments Panel -> Advanced Panel shows an error popover if both recovery keys are missing:
     TypeError: path must be a string or Buffer
      at TypeError (native)
      at Object.fs.openSync (fs.js:634:18)
      at Object.fs.writeFileSync (fs.js:1327:33)
      at generateAndSaveRecoveryFile (test/components/ledgerPanelAdvancedPanelTest.js:128:6)
      at Context.<anonymous> (test/components/ledgerPanelAdvancedPanelTest.js:213:5)
      at next (native)
      at onFulfilled (node_modules/co-mocha/node_modules/co/index.js:65:19)
      at node_modules/co-mocha/node_modules/co/index.js:54:5
      at new Promise (node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:191:7)
      at Context.co (node_modules/co-mocha/node_modules/co/index.js:50:10)
      at Context.createPromise (node_modules/co-mocha/node_modules/co/index.js:30:15)
      at Test.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)
      at run (node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:87:22)
      at node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:100:28
      at flush (node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

- [ ]  7) Payments Panel -> Advanced Panel shows an error popover if the file is empty:
     TypeError: path must be a string or Buffer
      at TypeError (native)
      at Object.fs.openSync (fs.js:634:18)
      at Object.fs.writeFileSync (fs.js:1327:33)
      at generateAndSaveRecoveryFile (test/components/ledgerPanelAdvancedPanelTest.js:128:6)
      at Context.<anonymous> (test/components/ledgerPanelAdvancedPanelTest.js:220:5)
      at next (native)
      at onFulfilled (node_modules/co-mocha/node_modules/co/index.js:65:19)
      at node_modules/co-mocha/node_modules/co/index.js:54:5
      at new Promise (node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:191:7)
      at Context.co (node_modules/co-mocha/node_modules/co/index.js:50:10)
      at Context.createPromise (node_modules/co-mocha/node_modules/co/index.js:30:15)
      at Test.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)
      at run (node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:87:22)
      at node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:100:28
      at flush (node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

- [x]  8) Payments Panel can setup payments "before each" hook for "shows welcome page":
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at windowHandles() - brave.js:208:32

https://travis-ci.org/brave/browser-laptop#L4734

- [ ]  24) Payments Panel -> Advanced Panel shows an error popover if one recovery key is missing:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
  
- [ ]  25) Payments Panel -> Advanced Panel shows an error popover if a recovery key is not a UUID:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
  
- [ ]  26) Payments Panel -> Advanced Panel shows an error popover if both recovery keys are missing:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
  
- [ ]  27) Payments Panel -> Advanced Panel shows an error popover if the file is empty:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.

- Any related issues: #6408

**Comment by bsclifton** [comment]
Partially fixed with https://github.com/brave/browser-laptop/pull/6932 (fixes the regular payment panel tests, not the advanced ones)

**Comment by luixxiul** [comment]
https://travis-ci.org/brave/browser-laptop/jobs/213319342#L787

````
  1) Regular payment panel tests can setup payments "before each" hook for "shows welcome page":
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at windowHandles() - brave.js:231:32
  2) Regular payment panel tests auto include site is added automatically:
     WaitUntilTimeoutError: element ([data-l10n-id="publisher"]) still not visible after 10000ms
      at isVisible("[data-l10n-id="publisher"]") - waitForVisible.js:37:22
  3) Regular payment panel tests auto include site is not added automatically:
     WaitUntilTimeoutError: element ([data-l10n-id="publisher"]) still not visible after 10000ms
      at isVisible("[data-l10n-id="publisher"]") - waitForVisible.js:37:22
  4) Regular payment panel tests auto include first site included, second site excluded:
     WaitUntilTimeoutError: element ([data-l10n-id="publisher"]) still not visible after 10000ms
      at isVisible("[data-l10n-id="publisher"]") - waitForVisible.js:37:22
````

**Comment by NejcZdovc** [comment]
@luixxiul I will address all test regarding the payment in #7642
