### ISSUE TITLE
Crash when I try to open Brave

### ISSUE THREAD

**Issue by bitcoinuser** [brave/browser-laptop#6898]
OS: Ubuntu 64
Brave: 0.13

Terminal message:

leonardo@leonardo-Aspire-V5-471:~$ brave
Crash reporting enabled
An uncaught exception occurred in the main process Uncaught Exception:
RangeError: Maximum call stack size exceeded
    at setListBounds (/usr/share/brave/resources/app.asar/node_modules/immutable/dist/immutable.js:2496:25)
    at /usr/share/brave/resources/app.asar/node_modules/immutable/dist/immutable.js:2410:11
    at List.Map.withMutations (/usr/share/brave/resources/app.asar/node_modules/immutable/dist/immutable.js:1355:7)
    at updateList (/usr/share/brave/resources/app.asar/node_modules/immutable/dist/immutable.js:2407:19)
    at List.set (/usr/share/brave/resources/app.asar/node_modules/immutable/dist/immutable.js:2098:14)
    at /usr/share/brave/resources/app.asar/node_modules/immutable/dist/immutable.js:2071:51
    at /usr/share/brave/resources/app.asar/node_modules/immutable/dist/immutable.js:3088:18
    at List.__iterate (/usr/share/brave/resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at IndexedIterable.filterSequence.__iterateUncached (/usr/share/brave/resources/app.asar/node_modules/immutable/dist/immutable.js:3085:16)
    at seqIterate (/usr/share/brave/resources/app.asar/node_modules/immutable/dist/immutable.js:606:16)
    at IndexedIterable.IndexedSeq.__iterate (/usr/share/brave/resources/app.asar/node_modules/immutable/dist/immutable.js:322:14)
Waiting 60 seconds for process to load

**Comment by bbondy** [comment]
Would you be able to send your `~/.config/brave/session-store-1` file, or email it to brian@brave.com if there is any sensitive information? I assume it can be reproduced every time you start?

**Comment by bitcoinuser** [comment]
Hi, ok, I'll send you the file now

**Comment by bitcoinuser** [comment]
File sent. 

Any idea what is happening?

**Comment by bbondy** [comment]
This was fixed in 0.13.4 available now. You will probably have to install it on top
https://brave.com/downloads.html
