### ISSUE TITLE
Brave crashes on Debian 8 (installed with aptitude as per instruction)

### ISSUE THREAD

**Issue by tonsimple** [brave/browser-laptop#6930]
- Did you search for similar issues before submitting this one?
Yes
This seems related  Brave won't start:  #6909  
But my error is slightly different (see below)

- Describe the issue you encountered:

Brave doesn't start.
Trying to start brave from command line gives 

[7637:7637:0130/233855:ERROR:sandbox_linux.cc(343)] InitializeSandbox() called with multiple threads in process gpu-process. 
An uncaught exception occurred in the main process Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.3LBLZp)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:600:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:182:18)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/brave/resources/app.asar/node_modules/keytar/lib/keytar.js:4:12)
    at Object.<anonymous> (/usr/share/brave/resources/app.asar/node_modules/keytar/lib/keytar.js:58:4)

- Platform (Win7, 8, 10? macOS? Linux distro?):
Debian 8
Living inside QubesOS AppVM
(getting an appVM "from scratch" and installing brave "fresh" does not solve issue)

- Brave Version (revision SHA):
718d8516bd07c01864eaba4d09ff6c17
- Steps to reproduce:
    1.Have QubesOS
    2.Have a Debian AppVM (or Standalone Debian VM, no difference)
    3.Configure it to install Brave as per https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md
    4. install brave (either in templatevm in qubes, or in a standalone VM, no difference)
    5. reboot
    6. try launching brave
    
- Actual result:
brave doesn't launch
trying to launch from command line results in above output

- Expected result:
browser actually, well, working
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Reproduced even in a fresh install
- Is this an issue in the currently released version?
I suppose so?
- Can this issue be consistently reproduced?
Yes, at least for me it reproduces across all Debians I can get my hands on 
- Extra QA steps:
EDITED TO ADD:
**downgrading via sudo apt-get install brave=0.12.15-1 FIXES the problem (for permissive definition of fixes), i.e. 0.12.15-1 starts with no issues and works**

- Screenshot if needed:

- Any related issues:

**Comment by Fromax** [comment]
@tonsimple Which kernel are you running?
I'm on 3.16.0-4 (Jessie default) and get similar issues. Same "fix": downgrading to 0.12.15-1 works.
```
[6871:6871:0131/161507:FATAL:zygote_host_impl_linux.cc(107)] No usable sandbox! 
Update your kernel or see 
https://chromium.googlesource.com/chromium/src/+/maste/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. 
If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
```
Using `brave --no-sandbox` in a terminal still fails:

```
An uncaught exception occurred in the main process Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.c4FndO)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:600:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:182:18)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/brave/resources/app.asar/node_modules/keytar/lib/keytar.js:4:12)
    at Object.<anonymous> (/usr/share/brave/resources/app.asar/node_modules/keytar/lib/keytar.js:58:4)
Waiting 60 seconds for process to load
Process failed to load within 60 seconds
```

**Comment by tonsimple** [comment]
@Fromax 
Initially observed on   4.4.38-11.pvops.qubes.x86_64 (in qubes)

**Comment by Fromax** [comment]
@tonsimple Maybe also related to "Brave won't start [No usable sandbox] #6902"

**Comment by Liunkae** [comment]
For the folks with the [No usable sandbox] error, please see the instructions here: https://github.com/brave/browser-laptop/issues/6902#issuecomment-285130546

**Comment by tonsimple** [comment]
@Liunkae 
Did everything, positively sure user namespaces are verily enabled, still getting the 

_InitializeSandbox() called with multiple threads in process gpu-process.
An uncaught exception occurred in the main process Uncaught Exception:_

error, after which brave dies.
Also, sandbox was enabled in version 0.12.15-1 too, right?

**Comment by tonsimple** [comment]
@Fromax 
My config.gz has

_CONFIG_USER_NS=y_

and 

_sudo sysctl -w kernel.unprivileged_userns_clone=1_

results in:

_sysctl: cannot stat /proc/sys/kernel/unprivileged_userns_clone: No such file or directory_

Google suggests that it means that user namespaces are on, and there is no sysctl switch present to "activate them any further"

So it's probs not my kernel missing namespace support, no?

**Comment by keverets** [comment]
Brave also crashes on Debian 9.0 (stretch) running the default 4.9.0-3-amd64 kernel. The error message is misleading:

```
[4969:4969:0620/054320.068695:FATAL:zygote_host_impl_linux.cc(107)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
Aborted (core dumped)
```

in that it's suggesting a kernel update would fix things (it won't), and the link to chromium docs is not relevant for Brave.

https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md gives a link to superuser that will ultimate provide a temporary work-around, but that's several layers deep of hunting for a solution.

At a minimum, the error message should be updated to provide Brave specific information (especially that the "--no-sandbox" is NOT recommended and that the preferred approach is to enable namespace support).

**Comment by tonsimple** [comment]
For what it's worth, this issue is solved for me in Debian 8 with most recent Brave version (but a new issue now happens which I submitted separately)

**Comment by keverets** [comment]
```
$ cat /etc/debian_version 
9.0
$ uname -a
Linux b570 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2 (2017-06-12) x86_64 GNU/Linux
$ dpkg -l | grep brave
ii  brave                                0.16.13-1                              amd64        Brave laptop and desktop browser
$ brave
[8130:8130:0626/202228.638303:FATAL:zygote_host_impl_linux.cc(107)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
Aborted (core dumped)
```

**Comment by bsclifton** [comment]
Closing as original issue has been closed

A proposal for solving the no-sandbox has been created with https://github.com/brave/browser-laptop/issues/11175

It looks like this is an issue for several platforms:
Not working on Kali linux #7146
Support for Subgraph OS #7899
Brave will not start on Arch Linux: No usable sandbox #9955
