### ISSUE TITLE
Crashes on start. Gtk-Message: Failed to load module "pantheon-filechooser-module"

### ISSUE THREAD

**Issue by dinusuresh** [brave/browser-laptop#7135]
**OS:** Elementary OS 0.4 Loki (64-bit) (Ubuntu 16.04 LTS)
**Brave** 0.13-2_1

Error:

```
Gtk-Message: Failed to load module "pantheon-filechooser-module"
ERROR getting value for field rev in sessionStore::setVersionInformation():  { Error: Cannot find module 'git-rev-sync'
    at Module._resolveFilename (module.js:472:15)
    at Function.Module._resolveFilename (/usr/share/brave/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at exports.browserLaptopRev (/usr/share/brave/resources/app.asar/app/channel.js:29:5)
    at safeGetVersion (/usr/share/brave/resources/app.asar/app/sessionStore.js:363:30)
    at versionFields.forEach (/usr/share/brave/resources/app.asar/app/sessionStore.js:392:29)
    at Array.forEach (native)
    at setVersionInformation (/usr/share/brave/resources/app.asar/app/sessionStore.js:391:17) code: 'MODULE_NOT_FOUND' }
Crash reporting enabled
Failed to get crash dump id.
Report Id: OK
Segmentation fault (core dumped)

```

**Comment by Liunkae** [comment]
How did you install Brave?

**Comment by dinusuresh** [comment]
@Liunkae  
`sudo gdebi brave.deb`

**Comment by luixxiul** [comment]
@dinusuresh would you please have a look at this manual? https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md

**Comment by dinusuresh** [comment]
@Liunkae Installed using the same instructions.

**Comment by dinusuresh** [comment]
**Brave:** 0.13.4_1 (Tried Ubuntu64 & Debian 64)

Both result in the following erro:

```
$ brave
[0224/153726.628224:ERROR:resource_bundle.cc(759)] Failed to load /usr/share/brave/chrome_100_percent.pak
Some features may not be available.
[0224/153726.629560:ERROR:resource_bundle.cc(759)] Failed to load /usr/share/brave/chrome_100_percent.pak
Some features may not be available.
[0224/153726.629585:ERROR:resource_bundle.cc(759)] Failed to load /usr/share/brave/chrome_200_percent.pak
Some features may not be available.
Gtk-Message: Failed to load module "pantheon-filechooser-module"
[12193:12193:0224/153726.688379:ERROR:resource_bundle.cc(759)] Failed to load /usr/share/brave/chrome_100_percent.pak
Some features may not be available.
[12193:12193:0224/153726.689650:ERROR:resource_bundle.cc(759)] Failed to load /usr/share/brave/chrome_100_percent.pak
Some features may not be available.
[12193:12193:0224/153726.689677:ERROR:resource_bundle.cc(759)] Failed to load /usr/share/brave/chrome_200_percent.pak
Some features may not be available.
ERROR getting value for field rev in sessionStore::setVersionInformation():  { Error: Cannot find module 'git-rev-sync'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/usr/share/brave/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at exports.browserLaptopRev (/usr/share/brave/resources/app.asar/app/channel.js:29:5)
    at safeGetVersion (/usr/share/brave/resources/app.asar/app/sessionStore.js:363:30)
    at versionFields.forEach (/usr/share/brave/resources/app.asar/app/sessionStore.js:392:29)
    at Array.forEach (native)
    at setVersionInformation (/usr/share/brave/resources/app.asar/app/sessionStore.js:391:17) code: 'MODULE_NOT_FOUND' }
Crash reporting enabled
Failed to get crash dump id.Report Id: OK
Segmentation fault (core dumped)

```

**Comment by luixxiul** [comment]
For now I'm going to close this issue as stale.


If you are still around here, would you please join https://community.brave.com? :smile: There is also a lot of discussions on the community, and you would be able to find solutions for other issues you might experience :+1: Thanks!
