### ISSUE TITLE
Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

### ISSUE THREAD

**Issue by pritamkmahajan** [brave/browser-laptop#7292]
I am trying to install git hub desktop on windows 10 OS. And I am facing following exception. Please help.. Tried with turning off firewall settings. But it didn't help.

====================================================================

PLATFORM VERSION INFO
	Windows 			: 10.0.14393.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1586.0 built by: NETFXREL2
	clr.dll 			: 4.6.1586.0 built by: NETFXREL2
	dfdll.dll 			: 4.6.1586.0 built by: NETFXREL2
	dfshim.dll 			: 10.0.14393.0 (rs1_release.160715-1616)

SOURCES
	Deployment url			: file:///C:/Users/Shree/Downloads/GitHub.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\Shree\Downloads\GitHub.application resulted in exception. Following failure messages were detected:
		+ Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [2/16/2017 11:18:37 PM] : Activation of C:\Users\Shree\Downloads\GitHub.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [2/16/2017 11:18:37 PM] System.UnauthorizedAccessException
		- Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Internal.Isolation.IsolationInterop.GetUserStore(UInt32 Flags, IntPtr hToken, Guid& riid)
			at System.Deployment.Internal.Isolation.IsolationInterop.GetUserStore()
			at System.Deployment.Application.ComponentStore..ctor(ComponentStoreType storeType, SubscriptionStore subStore)
			at System.Deployment.Application.SubscriptionStore..ctor(String deployPath, String tempPath, ComponentStoreType storeType)
			at System.Deployment.Application.SubscriptionStore.get_CurrentUser()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by luixxiul** [comment]
Hi, the issue should be reported to GitHub Support team, not us.

Please open https://github.com/contact and follow the instruction. Thanks
