### ISSUE TITLE
check for updates does not work behind authenticating proxy

### ISSUE THREAD

**Issue by jorgheymans** [brave/browser-laptop#7303]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
check for updates does not work when behind authenticating proxy
- Platform (Win7, 8, 10? macOS? Linux distro?):
win7
- Brave Version (revision SHA):
25b1199

- Can this issue be consistently reproduced?
yes
```
2017-02-17t07:05:57.830z - error: command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.

   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)

   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)

   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by jorgheymans** [comment]
... seems to work after manually installing 0.13.4 so closing for now
