### ISSUE TITLE
Brave wont start

### ISSUE THREAD

**Issue by posix4e** [brave/browser-laptop#7328]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
```
An uncaught exception occurred in the main process Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.c4FndO)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:600:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:182:18)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/brave/resources/app.asar/node_modules/keytar/lib/keytar.js:4:12)
    at Object.<anonymous> (/usr/share/brave/resources/app.asar/node_modules/keytar/lib/keytar.js:58:4)
Waiting 60 seconds for process to load
Process failed to load within 60 seconds
````
- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux
- Brave Version (revision SHA):
Any
- Steps to reproduce:
    1. Start brave and watch it crash
    
- Actual result:
Brave crashes
- Expected result:
Brave loads
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
I cannot run the packaged build on macOS with the latest published Muon, which may be related with the issue I assume. Sorry if I'm mistaken

**Comment by bsclifton** [comment]
@luixxiul no, that is a different issue; for that, you'll need to cherry pick in https://github.com/brave/browser-laptop/pull/7302 to your browser-laptop
