### ISSUE TITLE
Refactor paymentTab

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#7501]
- split in separate components
- move scripts from `js` folder to `app` folder
- all components in `paymentTab` should be using aphrodite

This needs to be done, before I can start working on #7348.

**Comment by alexwykoff** [comment]
Trying to save wallet info caused Brave to crash hard on Linux Mint.

Here is the console output:

[2014:2033:0316/002359.241999:ERROR:storage_block-inl.h(144)] Failed data store.
TypeError: Insufficient number of arguments.
    at Tabs.create (/home/test/Development/browser-laptop/app/ledger.js:326:23)
    at extensions.createTab (/home/test/Development/browser-laptop/app/browser/tabs.js:224:13)
    at Function.webContents.createTab (/home/test/Development/browser-laptop/node_modules/electron-prebuilt/dist/resources/electron.asar/browser/api/extensions.js:243:11)
    at Object.createTab (/home/test/Development/browser-laptop/node_modules/electron-prebuilt/dist/resources/electron.asar/browser/api/web-contents.js:212:26)
    at Object.createTab (/home/test/Development/browser-laptop/node_modules/electron-prebuilt/dist/resources/electron.asar/browser/api/extensions.js:237:17)
    at Object.create (/home/test/Development/browser-laptop/app/browser/tabs.js:223:16)
    at fs.writeFile (/home/test/Development/browser-laptop/app/ledger.js:322:12)
    at /home/test/Development/browser-laptop/node_modules/git-rev-sync/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:112:15)
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'downloadURL' of null
    at Tabs.create (/home/test/Development/browser-laptop/app/ledger.js:326:22)
    at extensions.createTab (/home/test/Development/browser-laptop/app/browser/tabs.js:224:13)
    at Object.createTab (/home/test/Development/browser-laptop/node_modules/electron-prebuilt/dist/resources/electron.asar/browser/api/extensions.js:251:5)
    at Object.create (/home/test/Development/browser-laptop/app/browser/tabs.js:223:16)
    at fs.writeFile (/home/test/Development/browser-laptop/app/ledger.js:322:12)
    at /home/test/Development/browser-laptop/node_modules/git-rev-sync/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:112:15)
/home/test/Development/browser-laptop/node_modules/node-anonize2-relic-emscripten/anonize2.js:18
if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WOR

TypeError: Cannot read property 'downloadURL' of null
    at Tabs.create (/home/test/Development/browser-laptop/app/ledger.js:326:22)
    at extensions.createTab (/home/test/Development/browser-laptop/app/browser/tabs.js:224:13)
    at Object.createTab (/home/test/Development/browser-laptop/node_modules/electron-prebuilt/dist/resources/electron.asar/browser/api/extensions.js:251:5)
    at Object.create (/home/test/Development/browser-laptop/app/browser/tabs.js:223:16)
    at fs.writeFile (/home/test/Development/browser-laptop/app/ledger.js:322:12)
    at /home/test/Development/browser-laptop/node_modules/git-rev-sync/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:112:15)
process exited with code 7

**Comment by NejcZdovc** [comment]
@alexwykoff this will be fixed here https://github.com/brave/browser-laptop/pull/7023
