### ISSUE TITLE
Linux Arm: postinstall script uses hardcoded --arch parameters

### ISSUE THREAD

**Issue by fczuardi** [brave/browser-laptop#772]
### Steps to reproduce:
1. patch abp-filter-parser-cpp (see #771 )
2. `npm install --save path/to/patched-abp-filter-parser-cpp`
3. `npm install`
### Expected results:

The npm dependencies are installed and the postinstall script runs sucessfully.
### Actual results:

After a the installation, the postinstall script fails with this error message:

```
> brave@0.7.14 postinstall /home/fcz/github/browser-laptop
> node ./tools/rebuildNativeModules.js&&webpack

Patching sqlite3 binding.gyp...
Installing native modules, please wait...
cd ./node_modules/abp-filter-parser-cpp&&"../../node_modules/.bin/node-gyp" rebuild --target=0.36.7 --arch=x64 --dist-url=https://atom.io/download/atom-shell&&cd ../../&&cd ./node_modules/tracking-protection&&"../../node_modules/.bin/node-gyp" rebuild --target=0.36.7 --arch=x64 --dist-url=https://atom.io/download/atom-shell&&cd ../../&&cd ./node_modules/sqlite3&&"../../node_modules/.bin/node-gyp" rebuild --target=0.36.7 --arch=x64 --dist-url=https://atom.io/download/atom-shell&&cd ../../
make: Entering directory '/home/fcz/github/browser-laptop/node_modules/abp-filter-parser-cpp/build'
  CXX(target) Release/obj.target/abp-filter-parser-cpp/addon.o
g++: error: unrecognized command line option '-m64'
abp-filter-parser-cpp.target.mk:102: recipe for target 'Release/obj.target/abp-filter-parser-cpp/addon.o' failed
make: *** [Release/obj.target/abp-filter-parser-cpp/addon.o] Error 1
make: Leaving directory '/home/fcz/github/browser-laptop/node_modules/abp-filter-parser-cpp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/fcz/github/browser-laptop/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.8.11-3-ARCH
gyp ERR! command "/home/fcz/.nvm/versions/node/v5.6.0/bin/node" "/home/fcz/github/browser-laptop/node_modules/.bin/node-gyp" "rebuild" "--target=0.36.7" "--arch=x64" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd /home/fcz/github/browser-laptop/node_modules/abp-filter-parser-cpp
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
done
```
### Workaround:

Open https://github.com/brave/browser-laptop/blob/master/tools/rebuildNativeModules.js#L32 and manually replace `--arch=x64` with `--arch=arm` and run `npm run postinstall`

The machine I am testing on is a Samsung Chromebook with Arch Linux http://archlinuxarm.org/platforms/armv7/samsung/samsung-chromebook

**Comment by luixxiul** [comment]
How about is it following the latest instruction on README?

**Comment by fczuardi** [comment]
I havent tried it yet
