### ISSUE TITLE
Automated test failure of ledgerTable

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#7803]
**Describe the issue you encountered:**

https://travis-ci.org/brave/browser-laptop/jobs/213319341#L1988

````
  1) LedgerTable component only non pinned tabs:
     Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
      at invariant (node_modules/fbjs/lib/invariant.js:44:15)
      at Object.addComponentAsRefTo (node_modules/react-dom/lib/ReactOwner.js:68:68)
      at attachRef (node_modules/react-dom/lib/ReactRef.js:23:16)
      at Object.ReactRef.attachRefs (node_modules/react-dom/lib/ReactRef.js:42:5)
      at ReactDOMComponent.attachRefs (node_modules/react-dom/lib/ReactReconciler.js:23:12)
      at CallbackQueue.notifyAll (node_modules/react-dom/lib/CallbackQueue.js:76:22)
      at ReactReconcileTransaction.close (node_modules/react-dom/lib/ReactReconcileTransaction.js:80:26)
      at ReactReconcileTransaction.closeAll (node_modules/react-dom/lib/Transaction.js:206:25)
      at ReactReconcileTransaction.perform (node_modules/react-dom/lib/Transaction.js:153:16)
      at batchedMountComponentIntoNode (node_modules/react-dom/lib/ReactMount.js:126:15)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-dom/lib/Transaction.js:140:20)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:97:27)
      at Object._renderNewRootComponent (node_modules/react-dom/lib/ReactMount.js:320:18)
      at Object._renderSubtreeIntoContainer (node_modules/react-dom/lib/ReactMount.js:401:32)
      at Object.render (node_modules/react-dom/lib/ReactMount.js:422:23)
      at Object.renderIntoDocument (node_modules/react-dom/lib/ReactTestUtils.js:79:21)
      at renderWithOptions (node_modules/enzyme/build/react-compat.js:187:26)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:94:59)
      at mount (node_modules/enzyme/build/mount.js:19:10)
      at Context.<anonymous> (test/unit/app/renderer/components/ledgerTableTest.js:72:21)
````

- Any related issues:

**Comment by NejcZdovc** [comment]
This is from a PR that is not yet completed https://github.com/brave/browser-laptop/pull/7642

**Comment by luixxiul** [comment]
Ah yes, sorry about reopening!
