### ISSUE TITLE
`Digest method not supported` when making contribution

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#7875]
Reported by @mrose17

When running 0.14.0 Preview 5 from the command line, we're seeing the following when trying to make a contribution:
```
callback: Error: Digest method not supported
Error: Digest method not supported
    at new Hash (crypto.js:56:18)
    at Hash (crypto.js:55:12)
    at ripemd160 (/Applications/Brave.app/Contents/Resources/app.asar/node_modules/bitcoinjs-lib/src/crypto.js:12:10)
    at Object.hash160 (/Applications/Brave.app/Contents/Resources/app.asar/node_modules/bitcoinjs-lib/src/crypto.js:4:10)
    at HDNode.getIdentifier (/Applications/Brave.app/Contents/Resources/app.asar/node_modules/bitcoinjs-lib/src/hdnode.js:132:18)
    at HDNode.getFingerprint (/Applications/Brave.app/Contents/Resources/app.asar/node_modules/bitcoinjs-lib/src/hdnode.js:136:15)
    at HDNode.derive (/Applications/Brave.app/Contents/Resources/app.asar/node_modules/bitcoinjs-lib/src/hdnode.js:274:31)
    at deriveFast (/Applications/Brave.app/Contents/Resources/app.asar/node_modules/bitgo/src/bitcoin.js:54:19)
    at derive (/Applications/Brave.app/Contents/Resources/app.asar/node_modules/bitgo/src/bitcoin.js:159:17)
    at derive (/Applications/Brave.app/Contents/Resources/app.asar/node_modules/bitgo/src/bitcoin.js:147:21)
```

**Comment by bsclifton** [comment]
Assigning @bridiver as this may be related to the openssl => boringssl switchover

**Comment by bridiver** [comment]
I should be able to patch boringssl for this, but can you check the bitcoin library to see if it uses any other crypto methods?

**Comment by bridiver** [comment]
fixed https://github.com/brave/muon/commit/1500a27e18c0d1df2e4daa17c6d14581fe235242
