### ISSUE TITLE
Brave crashed when visiting Brave Twitter page

### ISSUE THREAD

**Issue by aerique** [brave/browser-laptop#8004]
The Brave browser consistently crashes when going to the Brave Twitter page: https://twitter.com/brave

Other Twitter pages I checked do work.

I have all shields on except "Block Scripts" for that site.

This is on Windows 10 Pro and Brave browser:
 
    Brave: 0.14.0 
    rev: c23efa3eedf3b56058d991492e30c24cd186d138 
    Muon: 2.57.7 
    libchromiumcontent: 57.0.2987.110 
    V8: 5.7.492.65 
    Node.js: 7.4.0 
    Update Channel: dev 
    os.platform: win32 
    os.release: 10.0.14393 
    os.arch: x64

I think this happens because of a redirect from https://twitter.com/brave to https://twitter.com/Brave. If I go directly to the last one there's no problem.

**Comment by stites** [comment]
+1 to this. My situation is similar to that of #8212 
Here's my info

```
Brave	0.14.1
rev	3de60d5
Muon	2.57.8
libchromiumcontent	57.0.2987.133
V8	5.7.492.71
Node.js	7.4.0
Update Channel	dev
os.platform	linux
os.release	4.8.0-46-generic
os.arch	x64
```

Here's the stack trace I'm getting.

```
Warning: Can't create site data: [object Object]
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'name' of undefined
    at sendSyncRecords (/usr/share/brave/resources/app.asar/app/sync.js:58:40)
    at doAction (/usr/share/brave/resources/app.asar/app/sync.js:121:7)
    at callbacks.forEach (/usr/share/brave/resources/app.asar/js/dispatcher/appDispatcher.js:84:7)
    at Array.forEach (native)
    at AppDispatcher.dispatchInternal (/usr/share/brave/resources/app.asar/js/dispatcher/appDispatcher.js:83:20)
    at async.cargo (/usr/share/brave/resources/app.asar/js/dispatcher/appDispatcher.js:116:19)
    at process (/usr/share/brave/resources/app.asar/node_modules/async/dist/async.js:2306:17)
    at Immediate.<anonymous> (/usr/share/brave/resources/app.asar/node_modules/async/dist/async.js:2112:16)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
/usr/share/brave/resources/app.asar/node_modules/node-anonize2-relic-emscripten/anonize2-jumbo.js:67
      throw ex
      ^

TypeError: Cannot read property 'name' of undefined
    at sendSyncRecords (/usr/share/brave/resources/app.asar/app/sync.js:58:40)
    at doAction (/usr/share/brave/resources/app.asar/app/sync.js:121:7)
    at callbacks.forEach (/usr/share/brave/resources/app.asar/js/dispatcher/appDispatcher.js:84:7)
    at Array.forEach (native)
    at AppDispatcher.dispatchInternal (/usr/share/brave/resources/app.asar/js/dispatcher/appDispatcher.js:83:20)
    at async.cargo (/usr/share/brave/resources/app.asar/js/dispatcher/appDispatcher.js:116:19)
    at process (/usr/share/brave/resources/app.asar/node_modules/async/dist/async.js:2306:17)
    at Immediate.<anonymous> (/usr/share/brave/resources/app.asar/node_modules/async/dist/async.js:2112:16)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
```

**Comment by NejcZdovc** [comment]
cc @diracdeltas @ayumi

**Comment by ayumi** [comment]
Thanks! I believe we fixed this yesterday with https://github.com/brave/browser-laptop/pull/8242

**Comment by bsclifton** [comment]
Closing issue as our next release will have this.  If you'd like an immediate fix, you can try downloading our release candidate here: https://github.com/brave/browser-laptop/releases/tag/v0.14.2dev-RC2
