### ISSUE TITLE
About pages cannot be synced because data is too big (favicon is encoded in Base64 format)

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8023]
## Test plan

https://github.com/brave/browser-laptop/pull/8053#issue-218978569

----

**Describe the issue you encountered:**
````
(BLESSED_EXTENSION context for cjnmeadmgmiihncdidmfiabhenbggfjm) chrome-extension://cjnmeadmgmiihncdidmfiabhenbggfjm/content/scripts/sync.js:3: Uncaught Error: Data is too big; part limit is 64.{Error: Data is too big; part limit is 64.
    at Object.module.exports.encodeDataToS3KeyArray (chrome-extension://cjnmeadmgmiihncdidmfiabhenbggfjm/content/scripts/sync.js:3:28981)
    at RequestUtil.put (chrome-extension://cjnmeadmgmiihncdidmfiabhenbggfjm/content/scripts/sync.js:1:13433)
    at records.forEach.record (chrome-extension://cjnmeadmgmiihncdidmfiabhenbggfjm/content/scripts/sync.js:2:2197)
    at Array.forEach (native)
    at EventEmitter2.ipc.on (chrome-extension://cjnmeadmgmiihncdidmfiabhenbggfjm/content/scripts/sync.js:2:1873)
    at EventEmitter2.emit (extensions::event_emitter:43:17)
    at EventEmitter2.ipcRenderer.emit (extensions::ipc_utils:31:22)}
````

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.14.1 RC1

- Steps to reproduce:
    1. Set up sync
    2. Open about:about and bookmark it
    3. Open chrome-extension://cjnmeadmgmiihncdidmfiabhenbggfjm/_generated_background_page.html and wait
    
- Actual result: the error above is returned

- Expected result: either favicon is replaced with a link or data limit is increased to sync the about pages

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
  ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/24575655/6726c6a6-16e7-11e7-847d-b4985e2eef28.jpg)

- Any related issues:

**Comment by diracdeltas** [comment]
I think we shouldn't sync `data:` favicons. Maybe just strip out the favicon for now if it is a `data:` url.

**Comment by ayumi** [comment]
the max record size should be ~50 KiB.
however i agree we don't need to sync data URIs.
