### ISSUE TITLE
Ubuntu 14.04 Brave fails to load

### ISSUE THREAD

**Issue by danindiana** [brave/browser-laptop#8031]
Possibly related to issue #6930 and #6909

- Platform Linux Ubuntu 14.04 
3.13.0-113-generic #160-Ubuntu SMP Thu Mar 9 09:27:29 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Linux version 3.13.0-113-generic (buildd@lcy01-35) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) ) #160-Ubuntu SMP Thu Mar 9 09:27:29 UTC 2017

Installed via : https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md

This is what I get when I try to run it: 

speed@speed-desktop:~$ sudo brave
[sudo] password for speed: 
[0401/125526.646362:ERROR:nss_util.cc(94)] Failed to create /home/speed/.pki/nssdb directory.
[31636:31636:0401/125526.920728:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
An uncaught exception occurred in the main process Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.i0gKCm: failed to map segment from shared object: Operation not permitted
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:182:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /usr/share/brave/resources/app.asar/app/adBlock.js:8:25
    at Object.<anonymous> (/usr/share/brave/resources/app.asar/app/adBlock.js:120:2)
Waiting 60 seconds for process to load
stro?):

**Comment by bsclifton** [comment]
@danindiana if you're willing to give this a try again, I believe I can help you try Brave out 😄 

Grab our latest version (which I believe is 0.15.314).  If you still experience the above, I'd like to ask if you can try [launching it with some extra arguments](https://github.com/brave/browser-laptop/wiki/Troubleshooting#window-is-solid-black-or-solid-white-looks-like-a-blank-page):
```sh
# try this first
/path/to/brave --ignore-gpu-blacklist
# if that doesn't work, try this:
/path/to/brave --disable-gpu
```

I'm going to close the issue and mark as `info-needed` (waiting for your response). I'd love to help you out if you're willing to try again (sorry that none of us had gotten back to you earlier)
