### ISSUE TITLE
npm start crashes

### ISSUE THREAD

**Issue by weems** [brave/browser-laptop#820]
``` npm start```
```brave@0.7.14 start /Users/weems/code/brave/browser-laptop
node ./tools/start.js --debug=5858 -enable-logging --v=0 --enable-dcheck```
```electron "/Users/weems/code/brave/browser-laptop" --debug=5858
fs.js:584```
 ```return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);```
```Error: ENOENT: no such file or directory, open '/Users/weems/code/brave/browser-laptop/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/Users/weems/code/brave/browser-laptop/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)```

**Comment by bbondy** [comment]
> Error: ENOENT: no such file or directory, open '/Users/weems/code/brave/browser-laptop/node_modules/electron-prebuilt/path.txt'

This file should contain:
dist/Brave.app/Contents/MacOS/Brave

But what's worse is that this indicates your environment ins't setup properly. 
I suspect you somehow have the wrong version of electron-prebuilt installed.
Maybe you have manually npm installed electron-prebuilt which is an npm module that is published and not ours in the package.json. 

if you do a clean npm install and have no errors then you will have this file.

**Comment by bbondy** [comment]
I think this issue and some others before it are because of the improperly configured env.  I think as you get past with work around you'll keep running into things like this.  

Basically a clean npm install should work and if it doesn't then that is the core issue that needs to be solved by an environment change.

**Comment by weems** [comment]
Yeah. I think I shall have to also npm link again for abp-filter-parser-cpp to function. I need to write a bash script or something to automate these workarounds.

**Comment by weems** [comment]
Reran npm install and getting the same error:
```Error: ENOENT: no such file or directory, open '/Users/weems/code/brave/browser-laptop/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/Users/weems/code/brave/browser-laptop/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)```

I guess we need some documentation elaborating on a proper environment setup beyond the basic dependencies.

**Comment by luixxiul** [comment]
Was this fixed already?

**Comment by luixxiul** [comment]
Closing for a moment.
