### ISSUE TITLE
CRASH: ledger+sync

### ISSUE THREAD

**Issue by mrose17** [brave/browser-laptop#8217]
- Did you search for similar issues before submitting this one? yes

- Describe the issue you encountered: run either the current RC or master with both the ledger and sync turned on. make sure that the exclusion list is running. go to brave.com. sadly, BOOM!

- Platform (Win7, 8, 10? macOS? Linux distro?): mac

- Brave Version (revision SHA): https://github.com/brave/browser-laptop/commit/10539c2316a1b9a8011aa5fab742957d8a0b509e

- Steps to reproduce:
    1. Turn on the ledger
    2. Wait for the exclusion list to update
    3. Turn on sync
    4. Go to brave.com
    5. Crash
    
- Actual result: crash

- Expected result: no crash

- Will the steps above reproduce in a fresh profile? If not what other info can be added? see step 2 above

- Is this an issue in the currently released version? yes

- Can this issue be consistently reproduced? yes

- Extra QA steps: none
 
- Screenshot if needed: 

sync 1491868319255: sending record: {"action":1,"deviceId":{"0":0},"objectId":{"0":181,"1":212,"2":42,"3":20,"4":53,"5":39,"6":2(        51,"7":135,"8":114,"9":235,"10":84,"11":202,"12":146,"13":143,"14":244,"15":203},"siteSetting":{"hostPattern":"https?://brave.com","ledgerPayments":false}}
        Warning: Can't create site data: [object Object]
        An uncaught exception occurred in the main process Uncaught Exception:
        TypeError: Cannot read property 'name' of undefined
            at sendSyncRecords (/Users/mrose/Documents/Projects/brave.com/browser-laptop/app/sync.js:59:40)
            at doAction (/Users/mrose/Documents/Projects/brave.com/browser-laptop/app/sync.js:122:7)
            at callbacks.forEach (/Users/mrose/Documents/Projects/brave.com/browser-laptop/js/dispatcher/appDispatcher.js:84:7)
            at Array.forEach (native)
            at AppDispatcher.dispatchToOwnRegisteredCallbacks (/Users/mrose/Documents/Projects/brave.com/browser-laptop/js/dispatcher/appDispatcher.js:83:20)
            at AppDispatcher.dispatchInternal (/Users/mrose/Documents/Projects/brave.com/browser-laptop/js/dispatcher/appDispatcher.js:109:10)
            at async.cargo (/Users/mrose/Documents/Projects/brave.com/browser-laptop/js/dispatcher/appDispatcher.js:133:19)
            at process (/Users/mrose/Documents/Projects/brave.com/browser-laptop/node_modules/async/dist/async.js:2332:17)
            at Immediate.<anonymous> (/Users/mrose/Documents/Projects/brave.com/browser-laptop/node_modules/async/dist/async.js:2136:16)
            at runCallback (timers.js:651:20)
        /Users/mrose/Documents/Projects/brave.com/browser-laptop/node_modules/node-anonize2-relic-emscripten/anonize2-jumbo.js:67
                    throw ex
                    ^
        
        TypeError: Cannot read property 'name' of undefined
            at sendSyncRecords (/Users/mrose/Documents/Projects/brave.com/browser-laptop/app/sync.js:59:40)
            at doAction (/Users/mrose/Documents/Projects/brave.com/browser-laptop/app/sync.js:122:7)
            at callbacks.forEach (/Users/mrose/Documents/Projects/brave.com/browser-laptop/js/dispatcher/appDispatcher.js:84:7)
            at Array.forEach (native)
            at AppDispatcher.dispatchToOwnRegisteredCallbacks (/Users/mrose/Documents/Projects/brave.com/browser-laptop/js/dispatcher/appDispatcher.js:83:20)
            at AppDispatcher.dispatchInternal (/Users/mrose/Documents/Projects/brave.com/browser-laptop/js/dispatcher/appDispatcher.js:109:10)
            at async.cargo (/Users/mrose/Documents/Projects/brave.com/browser-laptop/js/dispatcher/appDispatcher.js:133:19)
            at process (/Users/mrose/Documents/Projects/brave.com/browser-laptop/node_modules/async/dist/async.js:2332:17)
            at Immediate.<anonymous> (/Users/mrose/Documents/Projects/brave.com/browser-laptop/node_modules/async/dist/async.js:2136:16)
            at runCallback (timers.js:651:20)
        process exited with code 7

- Any related issues: none

**Comment by jonathansampson** [comment]
I was able to repro having only Sync enabled on a fresh profile in https://github.com/brave/browser-laptop/commit/e217d0ec8e03a16fe6c93af69a820b2cad0cc780.

```
Warning: Can't create site data: [object Object]
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'name' of undefined
    at sendSyncRecords (C:\Users\jjdsa\Documents\GitHub\browser-laptop\app\sync.js:59:40)
    at doAction (C:\Users\jjdsa\Documents\GitHub\browser-laptop\app\sync.js:122:7)
    at callbacks.forEach (C:\Users\jjdsa\Documents\GitHub\browser-laptop\js\dispatcher\appDispatcher.js:84:7)
    at Array.forEach (native)
    at AppDispatcher.dispatchToOwnRegisteredCallbacks (C:\Users\jjdsa\Documents\GitHub\browser-laptop\js\dispatcher\appDispatcher.js:83:20)
    at AppDispatcher.dispatchInternal (C:\Users\jjdsa\Documents\GitHub\browser-laptop\js\dispatcher\appDispatcher.js:109:10)
    at async.cargo (C:\Users\jjdsa\Documents\GitHub\browser-laptop\js\dispatcher\appDispatcher.js:133:19)
    at process (C:\Users\jjdsa\Documents\GitHub\browser-laptop\node_modules\async\dist\async.js:2332:17)
    at Immediate.<anonymous> (C:\Users\jjdsa\Documents\GitHub\browser-laptop\node_modules\async\dist\async.js:2136:16)
    at runCallback (timers.js:651:20)
```
