### ISSUE TITLE
syncing site settings exception

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#8241]
syncing to serg's profile on the production sync server throws this error:
```
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property '1' of undefined
    at applySiteSettingRecord (/Users/yan/repos/browser-laptop/js/state/syncUtil.js:156:48)
    at applySyncRecord (/Users/yan/repos/browser-laptop/js/state/syncUtil.js:201:7)
    at Immediate.setImmediate (/Users/yan/repos/browser-laptop/js/state/syncUtil.js:180:5)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

**Comment by cezaraugusto** [comment]
@diracdeltas is there a member-only area where I could get this profile?

**Comment by alexwykoff** [comment]
While trying this test I found that about:preferences#security per site settings (like fullscreen for youtube) would not sync, but about:preferences#shields would sync.

So while there is no exception, it's unclear if the issue is fully resolved.

**Comment by diracdeltas** [comment]
it's just for shields
