### ISSUE TITLE
Give a better error message from installer when running 64bit on 32bit

### ISSUE THREAD

**Issue by unsystemizer** [brave/browser-laptop#842]
I don't know if I have a supported configuration, but install starts and then stops.
Maybe this could be handled in a better way.

```
2016-02-20 19:47:24> Program: Starting Squirrel Updater: --install .
2016-02-20 19:47:24> Program: Starting install, writing to C:\Users\user\AppData\Local\SquirrelTemp
2016-02-20 19:47:24> Program: About to install to: C:\Users\user\AppData\Local\Brave
2016-02-20 19:47:24> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user\AppData\Local\Brave\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2016-02-20 19:47:24> CheckForUpdateImpl: Reading RELEASES file from C:\Users\user\AppData\Local\SquirrelTemp
2016-02-20 19:47:24> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-02-20 19:47:27> ApplyReleasesImpl: Writing files to app directory: C:\Users\user\AppData\Local\Brave\app-0.7.15
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\Brave.exe to C:\Users\user\AppData\Local\Brave\app-0.7.15\Brave.exe
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\content_resources_200_percent.pak to C:\Users\user\AppData\Local\Brave\app-0.7.15\content_resources_200_percent.pak
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\d3dcompiler_47.dll to C:\Users\user\AppData\Local\Brave\app-0.7.15\d3dcompiler_47.dll
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\content_shell.pak to C:\Users\user\AppData\Local\Brave\app-0.7.15\content_shell.pak
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\ffmpeg.dll to C:\Users\user\AppData\Local\Brave\app-0.7.15\ffmpeg.dll
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\icudtl.dat to C:\Users\user\AppData\Local\Brave\app-0.7.15\icudtl.dat
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\libEGL.dll to C:\Users\user\AppData\Local\Brave\app-0.7.15\libEGL.dll
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\libGLESv2.dll to C:\Users\user\AppData\Local\Brave\app-0.7.15\libGLESv2.dll
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\LICENSE to C:\Users\user\AppData\Local\Brave\app-0.7.15\LICENSE
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\msvcr120.dll to C:\Users\user\AppData\Local\Brave\app-0.7.15\msvcr120.dll
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\node.dll to C:\Users\user\AppData\Local\Brave\app-0.7.15\node.dll
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\msvcp120.dll to C:\Users\user\AppData\Local\Brave\app-0.7.15\msvcp120.dll
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\pdf.dll to C:\Users\user\AppData\Local\Brave\app-0.7.15\pdf.dll
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\natives_blob.bin to C:\Users\user\AppData\Local\Brave\app-0.7.15\natives_blob.bin
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\squirrel.exe to C:\Users\user\AppData\Local\Brave\app-0.7.15\squirrel.exe
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\snapshot_blob.bin to C:\Users\user\AppData\Local\Brave\app-0.7.15\snapshot_blob.bin
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\vccorlib120.dll to C:\Users\user\AppData\Local\Brave\app-0.7.15\vccorlib120.dll
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\ui_resources_200_percent.pak to C:\Users\user\AppData\Local\Brave\app-0.7.15\ui_resources_200_percent.pak
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\xinput1_3.dll to C:\Users\user\AppData\Local\Brave\app-0.7.15\xinput1_3.dll
2016-02-20 19:48:29> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\user\AppData\Local\Brave\app-0.7.15\Brave.exe]
2016-02-20 19:48:29> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\user\AppData\Local\Brave\app-0.7.15\Brave.exe: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<<invokePostInstall>b__0>d.MoveNext()
2016-02-20 19:48:29> IEnableLogger: Failed to invoke post-install: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c.<invokePostInstall>b__10_6(ProcessStartInfo info)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()
2016-02-20 19:48:29> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c.<invokePostInstall>b__10_6(ProcessStartInfo info)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c.<invokePostInstall>b__10_6(ProcessStartInfo info)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

2016-02-20 19:47:24> Program: Starting Squirrel Updater: --install .
2016-02-20 19:47:24> Program: Starting install, writing to C:\Users\user\AppData\Local\SquirrelTemp
2016-02-20 19:47:24> Program: About to install to: C:\Users\user\AppData\Local\Brave
2016-02-20 19:47:24> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\user\AppData\Local\Brave\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2016-02-20 19:47:24> CheckForUpdateImpl: Reading RELEASES file from C:\Users\user\AppData\Local\SquirrelTemp
2016-02-20 19:47:24> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2016-02-20 19:47:27> ApplyReleasesImpl: Writing files to app directory: C:\Users\user\AppData\Local\Brave\app-0.7.15
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\Brave.exe to C:\Users\user\AppData\Local\Brave\app-0.7.15\Brave.exe
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\content_resources_200_percent.pak to C:\Users\user\AppData\Local\Brave\app-0.7.15\content_resources_200_percent.pak
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\d3dcompiler_47.dll to C:\Users\user\AppData\Local\Brave\app-0.7.15\d3dcompiler_47.dll
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\content_shell.pak to C:\Users\user\AppData\Local\Brave\app-0.7.15\content_shell.pak
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\ffmpeg.dll to C:\Users\user\AppData\Local\Brave\app-0.7.15\ffmpeg.dll
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\icudtl.dat to C:\Users\user\AppData\Local\Brave\app-0.7.15\icudtl.dat
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\libEGL.dll to C:\Users\user\AppData\Local\Brave\app-0.7.15\libEGL.dll
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\libGLESv2.dll to C:\Users\user\AppData\Local\Brave\app-0.7.15\libGLESv2.dll
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\LICENSE to C:\Users\user\AppData\Local\Brave\app-0.7.15\LICENSE
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\msvcr120.dll to C:\Users\user\AppData\Local\Brave\app-0.7.15\msvcr120.dll
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\node.dll to C:\Users\user\AppData\Local\Brave\app-0.7.15\node.dll
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\msvcp120.dll to C:\Users\user\AppData\Local\Brave\app-0.7.15\msvcp120.dll
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\pdf.dll to C:\Users\user\AppData\Local\Brave\app-0.7.15\pdf.dll
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\natives_blob.bin to C:\Users\user\AppData\Local\Brave\app-0.7.15\natives_blob.bin
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\squirrel.exe to C:\Users\user\AppData\Local\Brave\app-0.7.15\squirrel.exe
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\snapshot_blob.bin to C:\Users\user\AppData\Local\Brave\app-0.7.15\snapshot_blob.bin
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\vccorlib120.dll to C:\Users\user\AppData\Local\Brave\app-0.7.15\vccorlib120.dll
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\ui_resources_200_percent.pak to C:\Users\user\AppData\Local\Brave\app-0.7.15\ui_resources_200_percent.pak
2016-02-20 19:48:24> ApplyReleasesImpl: Moving file C:\Users\user\AppData\Local\Brave\app-0.7.15\lib\net45\xinput1_3.dll to C:\Users\user\AppData\Local\Brave\app-0.7.15\xinput1_3.dll
2016-02-20 19:48:29> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\user\AppData\Local\Brave\app-0.7.15\Brave.exe]
2016-02-20 19:48:29> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\user\AppData\Local\Brave\app-0.7.15\Brave.exe: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<<invokePostInstall>b__0>d.MoveNext()
2016-02-20 19:48:29> IEnableLogger: Failed to invoke post-install: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c.<invokePostInstall>b__10_6(ProcessStartInfo info)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()
2016-02-20 19:48:29> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c.<invokePostInstall>b__10_6(ProcessStartInfo info)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c.<invokePostInstall>b__10_6(ProcessStartInfo info)
   at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<invokePostInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---


```

**Comment by bbondy** [comment]
> The specified executable is not a valid application for this OS platform.

I think you may be using a 32-bit operating system and we only have 64-bit build support for now.  Closing for now, thanks.

**Comment by unsystemizer** [comment]
Okay I suspected that, but the browser could throw the right error (or the docs updated, if the first approach is too much work). 
Right now there's nothing on 64-bit in https://github.com/brave/browser-laptop/blob/master/docs/prerequisites.md

**Comment by bbondy** [comment]
Agreed, I re-opened and modified the title. I thought we had another posted already for the better error message but I can't find an exact match.

**Comment by bsclifton** [comment]
Possibly fixed with [Brave Core](https://github.com/brave/brave-browser/)

Closing as `wontfix` since that is likely addressed and also because there haven't been any additional reports
