### ISSUE TITLE
api.getWebContents is not a function

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8458]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Attempting to navigate back one page outputs the following:
```
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: api.getWebContents is not a function
    at Object.goBack (C:\browser-laptop-bootstrap\src\browser-laptop\app\browser\tabs.js:630:21)
    at tabsReducer (C:\browser-laptop-bootstrap\src\browser-laptop\app\browser\reducers\tabsReducer.js:86:20)
    at reducers.reduce (C:\browser-laptop-bootstrap\src\browser-laptop\js\stores\appStore.js:357:24)
    at Array.reduce (native)
    at applyReducers (C:\browser-laptop-bootstrap\src\browser-laptop\js\stores\appStore.js:355:51)
    at handleAppAction (C:\browser-laptop-bootstrap\src\browser-laptop\js\stores\appStore.js:392:14)
    at callbacks.forEach (C:\browser-laptop-bootstrap\src\browser-laptop\js\dispatcher\appDispatcher.js:84:7)
    at Array.forEach (native)
    at AppDispatcher.dispatchToOwnRegisteredCallbacks (C:\browser-laptop-bootstrap\src\browser-laptop\js\dispatcher\appDispatcher.js:83:20)
    at AppDispatcher.dispatchInternal (C:\browser-laptop-bootstrap\src\browser-laptop\js\dispatcher\appDispatcher.js:109:10)
```

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
0.15.0

- Steps to reproduce:
    1. Navigate to macys.com from a new tab
    2. Attempt to navigate back one page
    
- Actual result:
Exception is thrown

- Expected result:
Navigation occurs

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:

![Repro steps](https://cloud.githubusercontent.com/assets/815158/25319904/b5a80c72-2867-11e7-9e97-df004051c97d.gif)

- Any related issues:

**Comment by Liunkae** [comment]
Probably the same underlying problem as #8313. I'm also seeing this problem but only on master.

**Comment by NejcZdovc** [comment]
@Liunkae this should fix this error https://github.com/brave/browser-laptop/commit/c14021dceea244527c557ee7392440953fc1cab7 it's already in the master
