### ISSUE TITLE
Download file doesn't show as completed nor the progress indicator stops even after successfully downloading the file

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8548]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Download file doesn't show as completed nor the progress indicator stops even after successfully downloading the file
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7 ia32
- Brave Version (revision SHA):
Brave	0.15.1
rev	0598ddf
- Steps to reproduce:
    1. Clean install 0.15.1 preview 1
    2. Download a file
    3. Download progress is retained as the download completed message is not shown even if the download is completed
    4. Open about:download, right click and select clear completed download, doesn't clear since it shows as downloading
    
- Actual result:
Download complete notification doesn't show and the progress indicator is still shown
- Expected result:
Should show download completed message and progress indicator should not be shown
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
No
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
![download](https://cloud.githubusercontent.com/assets/17010094/25527387/7f447bb4-2c10-11e7-8e44-414dab36b398.gif)

**Comment by srirambv** [comment]
Console shows error when browser crashes. This could be a possible cause for the progress indicator to be still show as downloading
```
$ An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'downloadFinished' of undefined
    at module.exports.updateElectronDownloadItem (C:\Users\Sriram BV\AppData\Local\brave\app-0.15.2\resources\app.asar\app\browser\electronDownloadItem.js:17:15)
    at updateDownloadState (C:\Users\Sriram BV\AppData\Local\brave\app-0.15.2\resources\app.asar\app\filtering.js:467:3)
    at DownloadItem.<anonymous> (C:\Users\Sriram BV\AppData\Local\brave\app-0.15.2\resources\app.asar\app\filtering.js:525:7)
    at emitTwo (events.js:106:13)
    at DownloadItem.emit (events.js:194:7)
```
