### ISSUE TITLE
Crash on startup (possibly related to recovering tabs)

### ISSUE THREAD

**Issue by DivineOmega** [brave/browser-laptop#8552]
- Did you search for similar issues before submitting this one? Yes.

- Describe the issue you encountered: Upon launching the browser, it appears briefly, attemtping to re-load previously tabs and then immediately closes.

If ran through the terminal, I receive the following error.

```
jordan@azurite:~$ brave
Crash reporting enabled
ledger balance warning: {
  "message": "Blockonomics: undefined"
}
[8923:8923:0428/154813.756756:ERROR:CONSOLE(18783)] "(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit.", source: chrome://brave/usr/share/brave/resources/app.asar/app/extensions/brave/gen/app.entry.js (18783)
Warning: Can't create site data: {"order":1207,"count":15,"partitionNumber":0,"location":"https://parsecpizzadelivery.com/","title":"Parsec Pizza Delivery trailer - A pixelated deliver 'em up","tags":[],"objectId":[0,63,197,156,48,17,112,109,247,175,79,57,151,123,29,198],"themeColor":"rgb(5, 5, 5)"}
An uncaught exception occurred in the main process Uncaught Exception:
Error: Can't create JS from existingObject! [object Object]
    at Object.module.exports.getExistingObject (/usr/share/brave/resources/app.asar/js/state/syncUtil.js:259:11)
    at records.map (/usr/share/brave/resources/app.asar/app/sync.js:379:39)
    at Array.map (native)
    at EventEmitter.ipcMain.on (/usr/share/brave/resources/app.asar/app/sync.js:375:47)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/usr/share/brave/resources/electron.asar/browser/api/web-contents.js:182:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
/usr/share/brave/resources/app.asar/node_modules/node-anonize2-relic-emscripten/anonize2-jumbo.js:67
            throw ex
            ^

Error: Can't create JS from existingObject! [object Object]
    at Object.module.exports.getExistingObject (/usr/share/brave/resources/app.asar/js/state/syncUtil.js:259:11)
    at records.map (/usr/share/brave/resources/app.asar/app/sync.js:379:39)
    at Array.map (native)
    at EventEmitter.ipcMain.on (/usr/share/brave/resources/app.asar/app/sync.js:375:47)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/usr/share/brave/resources/electron.asar/browser/api/web-contents.js:182:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
```

- Platform (Win7, 8, 10? macOS? Linux distro?): Linux - Ubuntu 16.04

- Brave Version (revision SHA): v0.15.0 (71fb730)

- Steps to reproduce: Unfortunately, I'm not certain on what precisely causes the browser to get into the state required to trigger this issue.
    
- Actual result: Browser crashes almost immediately after startup.

- Expected result: Browser does not crash and correctly recovers previously used tabs.

- Will the steps above reproduce in a fresh profile? If not what other info can be added? 

No. Renaming the `/home/username/.config/brave/session-store-1` file and starting the browser works fine, excluding the loss of your previous tabs & some browser settings.

- Is this an issue in the currently released version? Yes.

- Can this issue be consistently reproduced? No. As mentioned, I am uncertain what precisely causes the browser to get into the state required to trigger this issue. It is not related to a particular website unfortunately.

- Any related issues: This appears to occur shortly after a seemingly random crash of the browser, but I can not confirm if this is always the case.

**Comment by Liunkae** [comment]
Do you have Brave Payments enabled? Wild guess: this is related to #8545.

**Comment by NejcZdovc** [comment]
@ayumi @diracdeltas error point into `syncUtil.js`. Could be this related to the sync?

**Comment by DivineOmega** [comment]
@Liunkae I did have Brave Payments enabled prior to renaming my `session-store-1` file. It is now disabled. When it was enabled, it was in the past due state due to insufficient funds.

**Comment by Liunkae** [comment]
@DivineOmega Nevermind, it looks like it was an issue with Brave Sync.
