### ISSUE TITLE
Browser crashes when trying to save image

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8665]
## Test plan

1. Go to https://imgur.com/gallery/rQIb4Vw
2. Click "..." at bottom-right of image
3. Select Download post

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Browser crashes when trying to save image

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.2
rev	71f7dfd

- Steps to reproduce:
    1. Go to https://imgur.com/gallery/rQIb4Vw
    2. Click "..." at bottom-right of image
    3. Select Download post
    4. Wait for it...wait for it...wait for it...CRASH
    
- Actual result:
Browsers crashes

- Expected result:
Should not crash 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
 #8548

**Comment by alexwykoff** [comment]
DNR https://i.imgur.com/vSnKYaF.gifv

**Comment by srirambv** [comment]
Still an issue on Preview 3 of 0.15.3
``` An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'downloadFinished' of undefined
    at module.exports.updateElectronDownloadItem (C:\Users\Sriram BV\AppData\Local\brave\app-0.15.3\resources\app.asar\app\browser\electronDownloadItem.js:17:15)
    at updateDownloadState (C:\Users\Sriram BV\AppData\Local\brave\app-0.15.3\resources\app.asar\app\filtering.js:467:3)
    at DownloadItem.<anonymous> (C:\Users\Sriram BV\AppData\Local\brave\app-0.15.3\resources\app.asar\app\filtering.js:525:7)
    at emitTwo (events.js:106:13)
    at DownloadItem.emit (events.js:194:7)
C:\Users\Sriram BV\AppData\Local\brave\app-0.15.3\resources\app.asar\node_modules\node-anonize2-relic-emscripten\anonize2-jumbo.js:67
            throw ex
            ^

TypeError: Cannot read property 'downloadFinished' of undefined
    at module.exports.updateElectronDownloadItem (C:\Users\Sriram BV\AppData\Local\brave\app-0.15.3\resources\app.asar\app\browser\electronDownloadItem.js:17:15)
    at updateDownloadState (C:\Users\Sriram BV\AppData\Local\brave\app-0.15.3\resources\app.asar\app\filtering.js:467:3)
    at DownloadItem.<anonymous> (C:\Users\Sriram BV\AppData\Local\brave\app-0.15.3\resources\app.asar\app\filtering.js:525:7)
    at emitTwo (events.js:106:13)
    at DownloadItem.emit (events.js:194:7)
```

**Comment by NejcZdovc** [comment]
I think that this commit will close this one as well d3ff9d9c82150069ed220596a3ef8ddb448f18d8

cc @bbondy

**Comment by bsclifton** [comment]
confirmed this worked for me on Windows 10, x64 😄  Please retest when you get a chance, @srirambv 😄

**Comment by srirambv** [comment]
Works fine on Windows 10 x64. with 0.15.300 build 👍 . Closing the issue
