### ISSUE TITLE
PDF renders as blank

### ISSUE THREAD

**Issue by stshank** [brave/browser-laptop#8774]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
PDF at https://npgallery.nps.gov/pdfhost/docs/NHLS/Text/70000736.pdf shows as blank.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS 10.12.5 beta

- Brave Version (revision SHA):

Name	Version
Brave	0.15.2
rev	af7ef42
Muon	2.58.9
libchromiumcontent	58.0.3029.96
V8	5.8.283.37
Node.js	7.9.0
Update Channel	dev
os.platform	darwin
os.release	16.6.0
os.arch	x64

- Steps to reproduce:
    1. load https://npgallery.nps.gov/pdfhost/docs/NHLS/Text/70000736.pdf
    
- Actual result:
5 blank pages

- Expected result:
Document appears. Renders correctly in Chrome.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Failed also in private tab.

- Is this an issue in the currently released version?
yes

**Comment by diracdeltas** [comment]
seems like an issue with upstream pdfjs. console shows this error:

```
viewer.js:1565 PDF 53af59999c55fbf1c4dd4a006cff2b64 [1.4 JRAPublish 3.000 / -] (PDF.js: 1.7.428)
pdf.worker.js:339 Error: JBIG2 error: huffman is not supported
chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:339 Error: JBIG2 error: huffman is not supported
pdf.worker.js:340     at error (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:340:17)
    at SimpleSegmentVisitor_onSymbolDictionary [as onSymbolDictionary] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31120:9)
    at processSegment (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31013:29)
    at processSegments (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31018:7)
    at parseJbig2Chunks (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31042:7)
    at Jbig2Image_parseChunks [as parseChunks] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31153:14)
    at Jbig2Stream_ensureBuffer [as ensureBuffer] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:2246:27)
    at Jbig2Stream.DecodeStream_getBytes [as getBytes] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:1588:14)
    at PDFImage_getImageBytes [as getImageBytes] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:30103:25)
pdf.worker.js:331 Warning: Unable to decode image: Error: JBIG2 error: huffman is not supported
chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:340     at error (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:340:17)
    at SimpleSegmentVisitor_onSymbolDictionary [as onSymbolDictionary] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31120:9)
    at processSegment (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31013:29)
    at processSegments (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31018:7)
    at parseJbig2Chunks (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31042:7)
    at Jbig2Image_parseChunks [as parseChunks] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31153:14)
    at Jbig2Stream_ensureBuffer [as ensureBuffer] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:2246:27)
    at Jbig2Stream.DecodeStream_getBytes [as getBytes] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:1588:14)
    at PDFImage_getImageBytes [as getImageBytes] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:30103:25)
chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:331 Warning: Unable to decode image: Error: JBIG2 error: huffman is not supported
pdf.js:331 Warning: Dependent image isn't ready yet
pdf.worker.js:339 Error: JBIG2 error: huffman is not supported
pdf.worker.js:340     at error (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:340:17)
    at SimpleSegmentVisitor_onSymbolDictionary [as onSymbolDictionary] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31120:9)
    at processSegment (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31013:29)
    at processSegments (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31018:7)
    at parseJbig2Chunks (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31042:7)
    at Jbig2Image_parseChunks [as parseChunks] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31153:14)
    at Jbig2Stream_ensureBuffer [as ensureBuffer] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:2246:27)
    at Jbig2Stream.DecodeStream_getBytes [as getBytes] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:1588:14)
    at PDFImage_getImageBytes [as getImageBytes] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:30103:25)
pdf.worker.js:331 Warning: Unable to decode image: Error: JBIG2 error: huffman is not supported
chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:339 Error: JBIG2 error: huffman is not supported
chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:340     at error (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:340:17)
    at SimpleSegmentVisitor_onSymbolDictionary [as onSymbolDictionary] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31120:9)
    at processSegment (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31013:29)
    at processSegments (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31018:7)
    at parseJbig2Chunks (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31042:7)
    at Jbig2Image_parseChunks [as parseChunks] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31153:14)
    at Jbig2Stream_ensureBuffer [as ensureBuffer] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:2246:27)
    at Jbig2Stream.DecodeStream_getBytes [as getBytes] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:1588:14)
    at PDFImage_getImageBytes [as getImageBytes] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:30103:25)
chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:331 Warning: Unable to decode image: Error: JBIG2 error: huffman is not supported
pdf.js:331 Warning: Dependent image isn't ready yet
pdf.worker.js:339 Error: JBIG2 error: huffman is not supported
pdf.worker.js:340     at error (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:340:17)
    at SimpleSegmentVisitor_onSymbolDictionary [as onSymbolDictionary] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31120:9)
    at processSegment (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31013:29)
    at processSegments (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31018:7)
    at parseJbig2Chunks (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31042:7)
    at Jbig2Image_parseChunks [as parseChunks] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31153:14)
    at Jbig2Stream_ensureBuffer [as ensureBuffer] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:2246:27)
    at Jbig2Stream.DecodeStream_getBytes [as getBytes] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:1588:14)
    at PDFImage_getImageBytes [as getImageBytes] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:30103:25)
pdf.worker.js:331 Warning: Unable to decode image: Error: JBIG2 error: huffman is not supported
chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:339 Error: JBIG2 error: huffman is not supported
chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:340     at error (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:340:17)
    at SimpleSegmentVisitor_onSymbolDictionary [as onSymbolDictionary] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31120:9)
    at processSegment (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31013:29)
    at processSegments (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31018:7)
    at parseJbig2Chunks (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31042:7)
    at Jbig2Image_parseChunks [as parseChunks] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:31153:14)
    at Jbig2Stream_ensureBuffer [as ensureBuffer] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:2246:27)
    at Jbig2Stream.DecodeStream_getBytes [as getBytes] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:1588:14)
    at PDFImage_getImageBytes [as getImageBytes] (chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:30103:25)
chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb/content/build/pdf.worker.js:331 Warning: Unable to decode image: Error: JBIG2 error: huffman is not supported
pdf.js:331 Warning: Dependent image isn't ready yet
```

**Comment by diracdeltas** [comment]
confirmed this is an issue in the pdfjs extension upstream so i opened https://github.com/mozilla/pdf.js/issues/8395

**Comment by diracdeltas** [comment]
this is a 5-year issue in PDF.JS :/

https://github.com/mozilla/pdf.js/issues/2073

**Comment by khepra23** [comment]
Having a similar issue where clicking a PDF generates a file not found error.
PDFs were working fine last week and PDFs still open correctly in other browsers on the same system..

**Comment by diracdeltas** [comment]
@khepra23 are you able to share the URL? is it a local file?

**Comment by humphd** [comment]
The upstream bug got fixed recently in https://github.com/mozilla/pdf.js/pull/8991, so this should get fixed the next time the pdfjs extension is updated.
