### ISSUE TITLE
Problem starting it: No usable sandbox. Update your kernel..

### ISSUE THREAD

**Issue by tunnckoCore** [brave/browser-laptop#8960]
- Did you search for similar issues before submitting this one?
Yes, didn't notice something similar
- Describe the issue you encountered:
Just can't start it, all dependencies and things are done without problems
- Platform (Win7, 8, 10? macOS? Linux distro?):
  + ArchLinux, with latest LTS kernel (4.9)
  + npm v4.6.1
  + node v6.10 (tried with latest v7.10, still not work)
  + node-gyp v3.6.1

- Brave Version (revision SHA):
v0.15.305dev (latest release, because seems that it fixes the "hide menu" problem)
- Steps to reproduce:
    1. Clone / Download that latest release
    2. npm install
    3. `npm run watch`, then `npm start` in another terminal tab 
    
- Actual result:
```txt
% > npm start     

> brave@0.15.305 start /home/charlike/github/browser-laptop-0.15.305dev
> node ./tools/start.js --user-data-dir=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck

[568:568:0519/195559.634212:FATAL:zygote_host_impl_linux.cc(107)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
process exited with code 0
```

- Expected result:
Start without problems

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

I also tried with `--v=1` flag. The output seems a bit different and saying that NODE MODULE VERSION is 55, but it (ad-block.node) requires 53.

```txt
~/github/browser-laptop-0.15.305dev  
% > node ./tools/start.js --user-data-dir=brave-development --enable-logging --v=1 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck
[5439:0519/200243.137526:VERBOSE1:zygote_main_linux.cc(619)] ZygoteMain: initializing 0 fork delegates
[5439:0519/200243.186317:INFO:systeminfo.cc(82)] Available number of cores: 4
App threw an error during load
Error: The module '/home/charlike/github/browser-laptop-0.15.305dev/node_modules/ad-block/build/Release/ad-block.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 55. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/charlike/github/browser-laptop-0.15.305dev/app/adBlock.js:8:49)
    at Object.<anonymous> (/home/charlike/github/browser-laptop-0.15.305dev/app/adBlock.js:120:3)
An uncaught exception occurred in the main process Uncaught Exception:
Error: The module '/home/charlike/github/browser-laptop-0.15.305dev/node_modules/ad-block/build/Release/ad-block.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 55. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/charlike/github/browser-laptop-0.15.305dev/app/adBlock.js:8:49)
    at Object.<anonymous> (/home/charlike/github/browser-laptop-0.15.305dev/app/adBlock.js:120:3)
Waiting 60 seconds for process to load
[5427:0519/200246.423271:ERROR:browser_main_loop.cc(250)] GTK theme error: Unable to locate theme engine in module_path: "adwaita",
[5427:0519/200246.423679:ERROR:browser_main_loop.cc(250)] GTK theme error: Unable to locate theme engine in module_path: "adwaita",
[5427:0519/200247.227635:VERBOSE1:gpu_info_collector_x11.cc(25)] NVCtrl extension does not exist.
[5427:0519/200247.710095:VERBOSE1:audio_manager_pulse.cc(269)] Failed to connect to the context.  Error: Connection refused
[5427:0519/200247.710154:WARNING:audio_manager.cc(317)] Multiple instances of AudioManager detected
[5427:0519/200247.710162:WARNING:audio_manager.cc(278)] Multiple instances of AudioManager detected
[5427:0519/200247.803434:VERBOSE1:bluez_dbus_manager.cc(172)] Bluetooth not supported.
Process failed to load within 60 seconds
[5427:0519/200346.297055:VERBOSE1:bluez_dbus_manager.cc(241)] BluezDBusManager Shutdown completed
[5427:0519/200346.297201:VERBOSE1:bus.cc(715)] Requested to remove an unknown filter function: 1 with associated data: 0x38835bb901e0
[5427:0519/200346.297778:VERBOSE1:dbus_thread_manager_linux.cc(62)] LinuxDBusManager Shutdown completed
[5427:0519/200346.298640:VERBOSE1:sandbox_ipc_linux.cc(117)] SandboxIPCHandler stopping.
[5427:0519/200346.304735:VERBOSE1:statistics_recorder.cc(541)] Collections of all histograms
Histogram: AsyncDNS.ConfigChange recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: AsyncDNS.ConfigParseDuration recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: AsyncDNS.ConfigParsePosix recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: AsyncDNS.ConfigParseResult recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: AsyncDNS.HostParseResult recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: AsyncDNS.HostsChange recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: AsyncDNS.HostsParseDuration recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: AsyncDNS.HostsSize recorded 1 samples, mean = 205.0 (flags = 0x1)
0    ... 
196  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
258  ... 

Histogram: AsyncDNS.WatchStatus recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: DBus.AsyncMethodCallSuccess recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: GPU.BlacklistFeatureTestResults.Accelerated2dCanvas recorded 2 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (2 = 100.0%)
1  ... 

Histogram: GPU.BlacklistFeatureTestResults.GpuCompositing recorded 2 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (2 = 100.0%)
1  ... 

Histogram: GPU.BlacklistFeatureTestResults.GpuRasterization recorded 2 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (2 = 100.0%)
1  ... 

Histogram: GPU.BlacklistFeatureTestResults.Webgl recorded 2 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (2 = 100.0%)
1  ... 

Histogram: GPU.BlacklistFeatureTestResults.Webgl2 recorded 2 samples, mean = 2.0 (flags = 0x1)
0  ... 
2  ------------------------------------------------------------------------O (2 = 100.0%) {0.0%}
3  O                                                                         (0 = 0.0%) {100.0%}

Histogram: GPU.BlacklistTestResultsPerEntry recorded 4 samples, mean = 24.0 (flags = 0x1)
0   ------------------------------------------------------------------------O (2 = 50.0%)
1   ... 
48  ------------------------------------------------------------------------O (2 = 50.0%) {50.0%}
49  ... 

Histogram: GPU.GPUProcessInitialized recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  O                                                                         (0 = 0.0%) {100.0%}

Histogram: GPU.GPUProcessLaunchTime recorded 1 samples, mean = 140.0 (flags = 0x1)
0    ... 
135  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
160  ... 

Histogram: GPU.GPUProcessLifetimeEvents recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: GPU.GPUProcessSoftwareRendering recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: GPU.GPUProcessTerminationStatus recorded 1 samples, mean = 4.0 (flags = 0x1)
0  ... 
4  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
5  ... 

Histogram: Linux.SandboxStatus recorded 1 samples (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)

Histogram: MPArch.ChildProcessLaunchFirst recorded 1 samples, mean = 22.0 (flags = 0x1)
0   ... 
20  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
24  ... 

Histogram: Media.LinuxAudioIO recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  ... 

Histogram: Media.Midi.ResultOnShutdown recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: Media.Midi.Usage recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: Memory.ShmemDir.AmountOfFreeSpace recorded 1 samples, mean = 1926.0 (flags = 0x1)
0     ... 
1903  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2218  ... 

Histogram: Mojo.System.Node.ConnectedPeers recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  ... 

Histogram: Mojo.System.Node.PendingChildren recorded 1 samples, mean = 1.0 (flags = 0x1)
0  O                                                                         (0 = 0.0%)
1  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
2  ... 

Histogram: Plugin.FlashUsage recorded 1 samples, mean = 2.0 (flags = 0x1)
0  ... 
2  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
3  O                                                                         (0 = 0.0%) {100.0%}

Histogram: Startup.BrowserMainRunnerImplInitializeLongTime recorded 1 samples, mean = 5045.0 (flags = 0x1)
0     ... 
4904  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
5660  ... 

Histogram: Startup.BrowserMainRunnerImplInitializeStep1Time recorded 1 samples, mean = 4355.0 (flags = 0x1)
0     ... 
4222  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
5017  ... 

Histogram: Startup.BrowserMainRunnerImplInitializeStep2Time recorded 1 samples, mean = 690.0 (flags = 0x1)
0    ... 
633  ------------------------------------------------------------------------O (1 = 100.0%) {0.0%}
752  ... 

Histogram: UMA.Histograms.Activity recorded 106 samples, mean = 4.1 (flags = 0x1)
0  --O                                                                       (1 = 0.9%)
1  ------------------------------------------------------------------------O (33 = 31.1%) {0.9%}
2  -------------O                                                            (6 = 5.7%) {32.1%}
3  ------------------------O                                                 (11 = 10.4%) {37.7%}
4  ---------------------------------O                                        (15 = 14.2%) {48.1%}
5  -------------O                                                            (6 = 5.7%) {62.3%}
6  O                                                                         (0 = 0.0%) {67.9%}
7  --O                                                                       (1 = 0.9%) {67.9%}
8  ------------------------------------------------------------------------O (33 = 31.1%) {68.9%}
9  ... 

Histogram: V8.Initializer.LoadV8Snapshot.Result recorded 1 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (1 = 100.0%)
1  ... 

Histogram: V8.Initializer.OpenV8File.Result recorded 2 samples, mean = 0.0 (flags = 0x1)
0  ------------------------------------------------------------------------O (2 = 100.0%)
1  ... 


process exited with code 1
```

it suggests to run `npm rebuild`, but it seems to not fix the issue. So the stacktrace is the same.

One more versions thing.

```
% > node -p 'process.versions'
{ http_parser: '2.7.0',
  node: '7.10.0',
  v8: '5.5.372.43',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j' }

```

***

I just need to compile it manually and not use the AUR packages, because I want to set 2-3 Chrome (Octolinker and Refined GIthub, just cant live without the first one ;d) extensions. If there's some other easier way, share your thoughts. :)

**Comment by aironou** [comment]
Reading ArchWiki, I found this:

> Note: The user namespace configuration item CONFIG_USER_NS is not set in the stock Arch kernel and may prevent certain sandboxing features from being made available to applications. The linux-hardened packages enables it but disables unprivileged usage by default unless the kernel.unprivileged_userns_clone sysctl is set to 1, since it greatly increases the attack surface for local privilege escalation.

[Source](https://wiki.archlinux.org/index.php/Security#Sandboxing_applications)

Reading [Brave Linux install instructions](https://github.com/brave/browser-laptop/blob/master/docs/linuxInstall.md) there is a note about this:

> NOTE: If Brave does not start and shows an error about sandboxing, you may need to enable userns in your kernel. Running with the --no-sandbox flag is NOT recommended!

I use Arch Linux and I run with `--no-sandbox` flag, maybe works for you.

**Comment by diracdeltas** [comment]
I don't recommend running with `--no-sandbox`, it greatly decreases the security of the browser. The recommended solution is to enable user namespaces in your kernel.

**Comment by diracdeltas** [comment]
duplicate of https://github.com/brave/browser-laptop/issues/6902

**Comment by tunnckoCore** [comment]
> I don't recommend running

yep, don't want that too.  But I don't want modified kernels too, so.

> duplicate of #6902

oops
