### ISSUE TITLE
Browser won't start if /tmp is mounted as noexec on Linux

### ISSUE THREAD

**Issue by fmarier** [brave/browser-laptop#900]
Given the `/tmp` setup on my laptop:

```
$ cat /etc/fstab | grep /tmp
tmpfs       /tmp        tmpfs       size=1024M,noexec,nosuid,nodev  0   0
$ mount | grep /tmp
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,noexec,relatime,size=1048576k)
```

The Brave browser won't start:

```
~/devel/Brave-linux-x64$ ./Brave 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.NftuiR: failed to map segment from shared object: Operation not permitted
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:170:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/francois/devel/Brave-linux-x64/resources/app.asar/app/trackingProtection.js:8:28)
    at Module._compile (module.js:425:26)
```

The work-around of course is to temporarily re-mount `/tmp` as executable while using Brave:

```
sudo mount -o remount,exec /tmp
```

**Comment by IcePee** [comment]
Yes, I ran into this issue as well. I hear that putting exec on /tmp is not very secure.

**Comment by luixxiul** [comment]
Will be fixed or not, @bbondy?

**Comment by bbondy** [comment]
sure but probably not soon unless a contributor grabs it.
