### ISSUE TITLE
clicking bookmark button throws error

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#92]
```
Uncaught Exception:
TypeError: frameProps.get is not a function
    at Object.exports.getSiteUrlIndex.exports.addSite (/Users/yan/repos/browser-electron/js/state/siteUtil.js:49:57)
    at handleAppAction (/Users/yan/repos/browser-electron/js/stores/appStore.js:79:49)
    at EventEmitter.<anonymous> (/Users/yan/repos/browser-electron/js/stores/appStore.js:91:52)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (/Users/yan/repos/browser-electron/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:91:27)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

**Comment by serv** [comment]
I tried clicking the star button beside the url bar but I can't repro this.

**Comment by diracdeltas** [comment]
i can't either; it probably got fixed at some point. will reopen if it happens again.

**Comment by bbondy** [comment]
yep I fixed this before and forgot to resolve, thanks.
