### ISSUE TITLE
MacOS 10.10.5: Error when starting brave

### ISSUE THREAD

**Issue by SpikeShape** [brave/browser-laptop#921]
I am getting the following error message right after pulling and building the current version:

```javascript
Uncaught Exception:
Error: Cannot find module 'immutablediff'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/rodger/Projects/browser-laptop/Brave-darwin-x64/Brave.app/Contents/Resources/app.asar/js/stores/appStore.js:25:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

I just pulled and ran 'npm run build-package' as I do every morning.

**Comment by bbondy** [comment]
You need to npm install the new dependencies.

**Comment by SpikeShape** [comment]
So in the future I better have a look at the package.json to realiye  that myself. Sorry about that.
