### ISSUE TITLE
Dynamic link library initialization routine failed

### ISSUE THREAD

**Issue by s-horn** [brave/browser-laptop#9215]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When I run `npm start` (while running `npm run watch` in a separate window), I get the following output:
```

> brave@0.15.312 start C:\Users\Stephen\Documents\git\browser-laptop
> node ./tools/start.js --user-data-dir=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck


App threw an error during load
Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\Stephen\Documents\git\browser-laptop\node_modules\ad-block\build\Release\ad-block.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Stephen\Documents\git\browser-laptop\app\adBlock.js:8:49)
    at Object.<anonymous> (C:\Users\Stephen\Documents\git\browser-laptop\app\adBlock.js:124:3)
An uncaught exception occurred in the main process Uncaught Exception:
Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\Stephen\Documents\git\browser-laptop\node_modules\ad-block\build\Release\ad-block.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Stephen\Documents\git\browser-laptop\app\adBlock.js:8:49)
    at Object.<anonymous> (C:\Users\Stephen\Documents\git\browser-laptop\app\adBlock.js:124:3)
Waiting 60 seconds for process to load
Process failed to load within 60 seconds
process exited with code 3221225477
npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! brave@0.15.312 start: `node ./tools/start.js --user-data-dir=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the brave@0.15.312 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Stephen\AppData\Roaming\npm-cache\_logs\2017-06-02T19_59_02_056Z-debug.log
/c/Program Files/nodejs/npm: line 34: 237368 Segmentation fault      "$NODE_EXE" "$NPM_CLI_JS" "$@"

```

This is the log file:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.0.0
3 info using node@v8.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle brave@0.15.312~prestart: brave@0.15.312
6 silly lifecycle brave@0.15.312~prestart: no script for prestart, continuing
7 info lifecycle brave@0.15.312~start: brave@0.15.312
8 verbose lifecycle brave@0.15.312~start: unsafe-perm in lifecycle true
9 verbose lifecycle brave@0.15.312~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Stephen\Documents\git\browser-laptop\node_modules\.bin;C:\Users\Stephen\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Stephen\bin;C:\oraclexe\app\oracle\product\12.1.0\client_1;C:\oraclexe\app\oracle\product\12.1.0\client_1\bin;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\app\client\oracle\product\12.1.0\client_1;C:\app\client\oracle\product\12.1.0\client_1\bin;C:\app\Stephen\product\12.1.0\dbhome_2\bin;C:\app\Stephen\product\12.1.0\dbhome_1\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Java\jdk1.8.0_60\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Hewlett-Packard\SimplePass;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\MinGW\bin;C:\Program Files (x86)\Symantec\VIP Access Client;C:\Program Files\nodejs;C:\Users\Stephen\AppData\Local\Programs\Python\Python35-32;C:\Users\Stephen\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
10 verbose lifecycle brave@0.15.312~start: CWD: C:\Users\Stephen\Documents\git\browser-laptop
11 silly lifecycle brave@0.15.312~start: Args: [ '/d /s /c',
11 silly lifecycle   'node ./tools/start.js --user-data-dir=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck' ]
12 silly lifecycle brave@0.15.312~start: Returned: code: 3221225477  signal: null
13 info lifecycle brave@0.15.312~start: Failed to exec start script
14 verbose stack Error: brave@0.15.312 start: `node ./tools/start.js --user-data-dir=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck`
14 verbose stack Exit status 3221225477
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:887:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid brave@0.15.312
16 verbose cwd C:\Users\Stephen\Documents\git\browser-laptop
17 verbose Windows_NT 10.0.14393
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 verbose node v8.0.0
20 verbose npm  v5.0.0
21 error code ELIFECYCLE
22 error errno 3221225477
23 error brave@0.15.312 start: `node ./tools/start.js --user-data-dir=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck`
23 error Exit status 3221225477
24 error Failed at the brave@0.15.312 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 3221225477, true ]
```

It seems like a dll might be missing, but I'm not sure where to look for this. Am I missing something obvious pointing me to where the error is?

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 Enterprise Edition

- Brave Version (revision SHA):
v0.16.0dev-24-g37ad4e8

- Steps to reproduce:
I was trying to follow the steps on [this page](https://github.com/brave/browser-laptop/wiki/(setup)-Windows-build-guide), but I had to do quite a few steps of troubleshooting before I could get to this point. I didn't write them all down, but I can try wiping it and reinstalling it if that would help.

**Comment by bridiver** [comment]
did `npm install` complete successfully? npm is really good at hiding error messages and making it look like everything is fine when it really failed. Windows also has issues with long path names so I would put browser-laptop at `C:\browser-laptop`, delete `node_modules` and run `npm install` again

**Comment by bsclifton** [comment]
Closing as there hasn't been a response

@s-horn please re-open (and include more info) if you're still experiencing this 😄
