### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9225]
**Describe the issue you encountered:** npm install fails.

````bash
> leveldown@1.5.0 install /Users/Suguru/browser-laptop/node_modules/leveldown
> prebuild --install

gyp WARN install got an error, rolling back install
prebuild ERR! configure error 
prebuild ERR! stack Error: iojs-v3.0.202-headers.tar.gz local checksum 9a50961e0167bcd665947ca79424d2778f966fb3ed9820f18d931c9afd360dc8 not match remote 02215cf8d8ab36d3a50084a20144cc00d0d6fb48de0e7dc26dd5a0a2cc0c04a8
prebuild ERR! stack     at deref (/Users/Suguru/browser-laptop/node_modules/node-gyp/lib/install.js:266:20)
prebuild ERR! stack     at IncomingMessage.<anonymous> (/Users/Suguru/browser-laptop/node_modules/node-gyp/lib/install.js:309:13)
prebuild ERR! stack     at emitNone (events.js:91:20)
prebuild ERR! stack     at IncomingMessage.emit (events.js:185:7)
prebuild ERR! stack     at endReadableNT (_stream_readable.js:974:12)
prebuild ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
prebuild ERR! stack     at process._tickCallback (internal/process/next_tick.js:98:9)
prebuild ERR! not ok 
prebuild ERR! build Error: iojs-v3.0.202-headers.tar.gz local checksum 9a50961e0167bcd665947ca79424d2778f966fb3ed9820f18d931c9afd360dc8 not match remote 02215cf8d8ab36d3a50084a20144cc00d0d6fb48de0e7dc26dd5a0a2cc0c04a8
prebuild ERR! build     at deref (/Users/Suguru/browser-laptop/node_modules/node-gyp/lib/install.js:266:20)
prebuild ERR! build     at IncomingMessage.<anonymous> (/Users/Suguru/browser-laptop/node_modules/node-gyp/lib/install.js:309:13)
prebuild ERR! build     at emitNone (events.js:91:20)
prebuild ERR! build     at IncomingMessage.emit (events.js:185:7)
prebuild ERR! build     at endReadableNT (_stream_readable.js:974:12)
prebuild ERR! build     at _combinedTickCallback (internal/process/next_tick.js:74:11)
prebuild ERR! build     at process._tickCallback (internal/process/next_tick.js:98:9)
````

By running `npm-check-updates` the installation finishes successfully while this error occurs this time:

````bash
Brave-MacBook-Pro:browser-laptop Suguru$ npm start

> brave@0.15.312 start /Users/Suguru/browser-laptop
> node ./tools/start.js --user-data-dir=brave-development --enable-logging --v=0 --enable-extension-activity-logging --enable-sandbox-logging --enable-dcheck

App threw an error during load
ReferenceError: document is not defined
    at /Users/Suguru/browser-laptop/node_modules/l20n/dist/web/l20n.js:5101:24
    at /Users/Suguru/browser-laptop/node_modules/l20n/dist/web/l20n.js:5113:2
    at Object.<anonymous> (/Users/Suguru/browser-laptop/node_modules/l20n/dist/web/l20n.js:5115:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
An uncaught exception occurred in the main process Uncaught Exception:
ReferenceError: document is not defined
    at /Users/Suguru/browser-laptop/node_modules/l20n/dist/web/l20n.js:5101:24
    at /Users/Suguru/browser-laptop/node_modules/l20n/dist/web/l20n.js:5113:2
    at Object.<anonymous> (/Users/Suguru/browser-laptop/node_modules/l20n/dist/web/l20n.js:5115:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
Waiting 60 seconds for process to load
```` 

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

````
Brave-MacBook-Pro:browser-laptop Suguru$ npm -v
4.1.0
Brave-MacBook-Pro:browser-laptop Suguru$ node -v
v7.3.0
````

- Brave Version (revision SHA): d4f169aadc528624b58c1bc0b150de135fcc55d7

- Steps to reproduce:
    1. `rm -rf node_modules && rm -rf ~/.electron && npm i`
    
- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by luixxiul** [comment]
On travis you get the same error: https://travis-ci.org/brave/browser-laptop/jobs/239027189#L412

**Comment by luixxiul** [comment]
the issue seems to have been fixed.
