### ISSUE TITLE
Can not open /var/lib/snapd/seccomp/profiles//snap.brave.brave (Permission denied)

### ISSUE THREAD

**Issue by demaniak** [brave/browser-laptop#9393]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
After installing the snap package, the application is unable to launch, giving the following error:
```
Can not open /var/lib/snapd/seccomp/profiles//snap.brave.brave (Permission denied)
aborting: Permission denied
```

- Platform (Win7, 8, 10? macOS? Linux distro?):
Ubuntu 16.04.2 LTS

- Brave Version (revision SHA):
```
➤ snap info brave
name:      brave
summary:   "Browse faster and safer with Brave."
publisher: flexiondotorg
description: |
  The new Brave browser automatically blocks ads and trackers, making it
  faster and safer than your current browser. Start supporting publishers
  today with our new Brave Payments system.
  
commands:
  - brave
tracking:      beta
installed:     0.15.1 (2) 149MB -
refreshed:     2017-04-28 19:45:13 +0200 SAST
channels:                 
  latest/beta: 0.15.1 (2) 149MB -
  latest/edge: 0.15.1 (2) 149MB -
```

- Steps to reproduce:
    1. install snap package as instructed: `sudo snap install brave --beta`. Note that `sudo` was required.
    2. attempt to run `brave` by any means
      - `brave`
      - `snap run brave`
      - `sudo brave`
      - `sudo snap run brave`
      - installed desktop application menu option
    
    
- Actual result:
Running from installed menu item results in nothing happening.

Running from command line with any method mentioned above results in:
```
Can not open /var/lib/snapd/seccomp/profiles//snap.brave.brave (Permission denied)
aborting: Permission denied
```

- Expected result:
Running application.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
I have no idea, since I could not launch the app to start with.

- Is this an issue in the currently released version?
In whatever version resulted in being installed by following instructions.

- Can this issue be consistently reproduced?
Application consistently fails to open, so...yes.

- Snap version
```
snap    2.25
snapd   2.25
series  16
ubuntu  16.04
kernel  4.4.0-79-generic
```

**Comment by bsclifton** [comment]
cc: @flexiondotorg

**Comment by Shaunakde** [comment]
I can't get brave to launch either. I get different error messages though. Doing `snap run brave' leads to:
'''
shaunak@DEEPSPACE:~$ snap run brave
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "canberra-gtk-module"
[13111:13111:0613/122411.612034:ERROR:gconf_listener.cc(116)] Error with gconf key '/apps/metacity/general': Configuration server couldn't be contacted: D-BUS error: An AppArmor policy prevents this sender from sending this message to this recipient, 0 matched rules; type="method_call", sender=":1.206" (uid=1000 pid=13111 comm="/snap/brave/2/usr/share/brave/brave --no-sandbox") interface="org.gnome.GConf.Server" member="GetDefaultDatabase" error name="(unset)" requested_reply="0" destination="org.gnome.GConf" (uid=1000 pid=2993 comm="/usr/lib/x86_64-linux-gnu/gconf/gconfd-2 ")
An uncaught exception occurred in the main process Uncaught Exception:
Error: /run/user/1000/snap.brave/.org.chromium.Chromium.Reltxa: failed to map segment from shared object
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:182:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /snap/brave/2/usr/share/brave/resources/app.asar/app/adBlock.js:8:49
    at Object.<anonymous> (/snap/brave/2/usr/share/brave/resources/app.asar/app/adBlock.js:120:2)
Waiting 60 seconds for process to load
Process failed to load within 60 seconds
'''

**Comment by pingram3541** [comment]
Yep, same here except result it always "command not found" for all types of command variations.

**Comment by hugobuddel** [comment]
Perhaps this is related to AppArmor, as the message from @Shaunakde suggests. I've got problem #11440 using Ubuntu 16.04.3.

And some other things that might also be due to AppArmor, like Brave not being able to set itself as default browser:

> LaunchProcess: failed to execvp:
> xdg-settings

A chrome example: https://ubuntuforums.org/showthread.php?t=2319869&page=2&p=13473617#post13473617

I've got no experience with AppArmor, so I don't know how to proceed yet.

**Comment by fpoumian** [comment]
I'm experiencing the same issue as @Shaunakde when trying to launch Brave after installing it on Ubuntu 16.04 using Snapcraft:
```
/snap/brave/6/bin/desktop-launch: line 178: cannot create temp file for here-document: Permission denied
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
[20925:20925:1012/160943.375454:ERROR:gconf_listener.cc(116)] Error with gconf key '/apps/metacity/general': Configuration server couldn't be contacted: D-BUS error: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.285" (uid=1000 pid=20925 comm="/snap/brave/6/usr/lib/brave/brave --no-sandbox --n") interface="org.gnome.GConf.Server" member="GetDefaultDatabase" error name="(unset)" requested_reply="0" destination="org.gnome.GConf" (uid=1000 pid=3437 comm="/usr/lib/x86_64-linux-gnu/gconf/gconfd-2 ")
MESA-LOADER: failed to retrieve device information
Error: unrecognized flag --icu_case_mapping
Try --help for options
An uncaught exception occurred in the main process Uncaught Exception:
Error: ENOENT, node_modules/ad-block/build/Release/ad-block.node not found in /snap/brave/6/usr/lib/brave/resources/app.asar
    at notFoundError (ELECTRON_ASAR.js:110:19)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:178:9)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /snap/brave/6/usr/lib/brave/resources/app.asar/app/adBlock.js:8:49
    at Object.<anonymous> (/snap/brave/6/usr/lib/brave/resources/app.asar/app/adBlock.js:124:2)
    at Module._compile (module.js:571:32)
Waiting 60 seconds for process to load
[20925:20925:1012/160944.244010:ERROR:proxy_config_service_linux.cc(274)] Error requesting gconf directory: Configuration server couldn't be contacted: D-BUS error: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.285" (uid=1000 pid=20925 comm="/snap/brave/6/usr/lib/brave/brave --no-sandbox --n") interface="org.gnome.GConf.Server" member="GetDefaultDatabase" error name="(unset)" requested_reply="0" destination="org.gnome.GConf" (uid=1000 pid=3437 comm="/usr/lib/x86_64-linux-gnu/gconf/gconfd-2 ")
Process failed to load within 60 seconds

```
