### ISSUE TITLE
'Sync could not create siteKey' error

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#9430]
i get this error occasionally on master:

```
Error: Sync could not create siteKey
    at Object.module.exports.createSiteData (/Users/yan/repos/browser-laptop/js/state/syncUtil.js:484:11)
    at diffs.forEach (/Users/yan/repos/browser-laptop/app/sync.js:134:29)
    at Array.forEach (<anonymous>)
    at AppStore.appStoreChangeCallback (/Users/yan/repos/browser-laptop/app/sync.js:61:9)
    at emitOne (events.js:101:20)
    at AppStore.emit (events.js:191:7)
    at AppStore.emitChanges (/Users/yan/repos/browser-laptop/js/stores/appStore.js:276:14)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by diracdeltas** [comment]
I can repro this by starting the browser with `https://www.google.com/#q=test` as a single open tab. It appears that `{"favicon":"https://www.google.com/images/branding/product/ico/googleg_lodp.ico"}` is the site object which is passed to createSiteData

**Comment by diracdeltas** [comment]
it appears that sometimes the sync appStoreChangeListener is called before the synced object has all of its fields populated
