### ISSUE TITLE
TypeError: parsedUrl.query.split is not a function

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#9504]
observed on master when going to bing.com:

```
TypeError: parsedUrl.query.split is not a function
    at SearchIndex.tokenizeInput (/Users/yan/repos/browser-laptop/app/common/lib/siteSuggestions.js:95:44)
    at /Users/yan/repos/browser-laptop/node_modules/bloodhound-js/lib/search_index.js:36:37
    at Array.forEach (<anonymous>)
    at Object.each (/Users/yan/repos/browser-laptop/node_modules/bloodhound-js/lib/utils.js:52:16)
    at SearchIndex.add (/Users/yan/repos/browser-laptop/node_modules/bloodhound-js/lib/search_index.js:32:7)
    at Bloodhound.add (/Users/yan/repos/browser-laptop/node_modules/bloodhound-js/lib/bloodhound.js:110:16)
    at add (/Users/yan/repos/browser-laptop/app/common/lib/siteSuggestions.js:113:12)
    at urlBarSuggestionsReducer (/Users/yan/repos/browser-laptop/app/browser/reducers/urlBarSuggestionsReducer.js:22:9)
    at reducers.reduce (/Users/yan/repos/browser-laptop/js/stores/appStore.js:380:24)
    at Array.reduce (<anonymous>)
```
may be due to 77873c3ba458f271928b2a24d1dbbfe8895007b6

**Comment by bsclifton** [comment]
this should be fixed with https://github.com/brave/browser-laptop/commit/d142b243150684da669d86c4d1e83cc5d20769a5 😄
