### ISSUE TITLE
Local failing tests

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#9638]
**Describe the issue you encountered:**
Tests that are failing locally (63ff18d)
```
1) Advanced payment panel tests can backup wallet to file:
     WaitUntilTimeoutError: Promise was rejected with the following reason: AssertionError: null == 'file:'
      at getValue("#urlInput") - ledgerPanelAdvancedPanelTest.js:161:21

  2) Advanced payment panel tests can recover wallet from file:
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.


  3) Advanced payment panel tests shows an error popover if one recovery key is missing:
     TypeError: path must be a string or Buffer
      at Object.fs.openSync (fs.js:584:18)
      at Object.fs.writeFileSync (fs.js:1316:33)
      at generateAndSaveRecoveryFile (test/about/ledgerPanelAdvancedPanelTest.js:130:6)
      at Context.<anonymous> (test/about/ledgerPanelAdvancedPanelTest.js:199:5)
      at Generator.next (<anonymous>)
      at onFulfilled (node_modules/co/index.js:65:19)
      at node_modules/co/index.js:54:5
      at Context.co (node_modules/co/index.js:50:10)
      at Context.createPromise (node_modules/co/index.js:30:15)
      at Test.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)
      at process._tickCallback (internal/process/next_tick.js:109:7)

  4) Advanced payment panel tests shows an error popover if a recovery key is not a UUID:
     TypeError: path must be a string or Buffer
      at Object.fs.openSync (fs.js:584:18)
      at Object.fs.writeFileSync (fs.js:1316:33)
      at generateAndSaveRecoveryFile (test/about/ledgerPanelAdvancedPanelTest.js:130:6)
      at Context.<anonymous> (test/about/ledgerPanelAdvancedPanelTest.js:206:5)
      at Generator.next (<anonymous>)
      at onFulfilled (node_modules/co/index.js:65:19)
      at node_modules/co/index.js:54:5
      at Context.co (node_modules/co/index.js:50:10)
      at Context.createPromise (node_modules/co/index.js:30:15)
      at Test.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)
      at process._tickCallback (internal/process/next_tick.js:109:7)

  5) Advanced payment panel tests shows an error popover if both recovery keys are missing:
     TypeError: path must be a string or Buffer
      at Object.fs.openSync (fs.js:584:18)
      at Object.fs.writeFileSync (fs.js:1316:33)
      at generateAndSaveRecoveryFile (test/about/ledgerPanelAdvancedPanelTest.js:130:6)
      at Context.<anonymous> (test/about/ledgerPanelAdvancedPanelTest.js:213:5)
      at Generator.next (<anonymous>)
      at onFulfilled (node_modules/co/index.js:65:19)
      at node_modules/co/index.js:54:5
      at Context.co (node_modules/co/index.js:50:10)
      at Context.createPromise (node_modules/co/index.js:30:15)
      at Test.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)
      at process._tickCallback (internal/process/next_tick.js:109:7)

  6) Advanced payment panel tests shows an error popover if the file is empty:
     TypeError: path must be a string or Buffer
      at Object.fs.openSync (fs.js:584:18)
      at Object.fs.writeFileSync (fs.js:1316:33)
      at generateAndSaveRecoveryFile (test/about/ledgerPanelAdvancedPanelTest.js:130:6)
      at Context.<anonymous> (test/about/ledgerPanelAdvancedPanelTest.js:220:5)
      at Generator.next (<anonymous>)
      at onFulfilled (node_modules/co/index.js:65:19)
      at node_modules/co/index.js:54:5
      at Context.co (node_modules/co/index.js:50:10)
      at Context.createPromise (node_modules/co/index.js:30:15)
      at Test.Runnable.run (node_modules/co-mocha/lib/co-mocha.js:43:16)
      at process._tickCallback (internal/process/next_tick.js:109:7)

  7) Regular payment panel tests can setup payments "before each" hook for "shows welcome page":
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at getUrl() - brave.js:282:40

  8) Ledger table 2 publishers pin excluded publisher:
     WaitUntilTimeoutError: element ([data-tbody-index="1"] [data-row-index="1"] [data-switch-status="false"]) still not visible after 10000ms
      at isVisible("[data-tbody-index="1"] [data-row-index="1"] [data-switch-status="false"]") - waitForVisible.js:37:22

  9) Ledger table 2 publishers check pinned sites amount, when you have 0 eligible unpinned sites:
     Promise was rejected with the following reason: timeout
  Error

  10) MessageBox component tests alert when opening a new tab (while alert is showing) "before each" hook for "lets you use the back button":
     element (#thelink[href="page2.html"]) still not visible after 5000ms
  Error

  11) Clear Browsing Panel with saved state values saves the history switch state:
     Promise was rejected with the following reason: timeout
  Error

  12) Clear Browsing Panel with history clears the browsing history:
     Promise was rejected with the following reason: timeout
  Error

  13) Clear Browsing Panel with closedFrames clears closedFrames:
     Promise was rejected with the following reason: timeout
  Error

  14) noscript can allow scripts when the url host is an ipv6 address:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at getText(".blockedOriginsList") - noScriptTest.js:151:23

  15) Sync Panel sync post-setup "before each" hook for "sync can be toggled":
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at windowHandles() - brave.js:278:32

  16) Syncing and clearing data prevents it from syncing history:
     Promise was rejected with the following reason: timeout
  Error

  17) Syncing and clearing data prevents it from syncing site settings:
     Promise was rejected with the following reason: timeout
  Error

  18) urlBar tests keeps url text separate from suffix text changes only the selection:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at getValue("#urlInput") - brave.js:549:23

  19) tab tests webview in fullscreen mode keep favicon and title after exiting fullscreen mode:
     WaitUntilTimeoutError: element ([data-test-active-tab] [data-test-id="tabTitle"]) still not visible after 10000ms
      at isVisible("[data-test-active-tab] [data-test-id="tabTitle"]") - waitForVisible.js:37:22

  20) tab tests tab transfer can detach into new windows:
     Promise was rejected with the following reason: timeout
  Error
 21) ContextMenu navigation check if enter is prevented:
     WaitUntilTimeoutError: element (.contextMenu div.selectedByKeyboard[data-index="0"]) still not existing after 10000ms
      at isExisting(".contextMenu div.selectedByKeyboard[data-index="0"]") - waitForExist.js:37:22
  22) ContextMenu navigation click on item:
     WaitUntilTimeoutError: element (.contextMenu) still not visible after 10000ms
      at isVisible(".contextMenu") - waitForVisible.js:37:22
  23) ContextMenu navigation select item via click and keys:
     WaitUntilTimeoutError: element (.contextMenu) still not visible after 10000ms
      at isVisible(".contextMenu") - waitForVisible.js:37:22
  24) ContextMenu navigation select item via keys only:
     WaitUntilTimeoutError: element (.contextMenu) still not visible after 10000ms
      at isVisible(".contextMenu") - waitForVisible.js:37:22
  25) ContextMenu navigation check left/right on non sub menu item:
     WaitUntilTimeoutError: element (.contextMenu) still not visible after 10000ms
      at isVisible(".contextMenu") - waitForVisible.js:37:22
```

**Comment by NejcZdovc** [comment]
PR #9639 fixes test fails that were introduces with redux refactoring. For other errors I opened some issues.

1-6 #9677
7 - unknown
8 - #9639
9 - #9641 
10 - intermittent
11-13 #9639 
14 - unknown
15-17  #9639 
18-19 unknown
20 cc @bbondy 
21-25 #9639
