### ISSUE TITLE
Error while closing tab pages: `Could not find tab for <id>`

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#9722]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:
When closing multiple tab pages by right clicking and picking `Close tab page`, the UI stops responding and the following error is written to stdout:
```
An uncaught exception occurred in the main process Uncaught Exception:
AssertionError: Could not find tab for 87
    at Object.getTabPropertyByTabId (/Users/clifton/Documents/browser-laptop/app/common/state/tabState.js:464:12)
    at Object.getWindowId (/Users/clifton/Documents/browser-laptop/app/common/state/tabState.js:470:21)
    at tabsReducer (/Users/clifton/Documents/browser-laptop/app/browser/reducers/tabsReducer.js:140:39)
    at reducers.reduce (/Users/clifton/Documents/browser-laptop/js/stores/appStore.js:380:24)
    at Array.reduce (<anonymous>)
    at applyReducers (/Users/clifton/Documents/browser-laptop/js/stores/appStore.js:378:68)
    at handleAppAction (/Users/clifton/Documents/browser-laptop/js/stores/appStore.js:420:14)
    at callbacks.forEach (/Users/clifton/Documents/browser-laptop/js/dispatcher/appDispatcher.js:85:7)
    at Array.forEach (<anonymous>)
    at AppDispatcher.dispatchToOwnRegisteredCallbacks (/Users/clifton/Documents/browser-laptop/js/dispatcher/appDispatcher.js:84:20)
```

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.17.9

- Steps to reproduce:
    1. Set your tab page size to 20
    2. Open about:newtab
    3. Use middle click or cmd/ctrl + click to open about 5 or 6 tab pages worth of tabs. Open them as fast as you can.
    4. Start closing each tab page by right clicking the tab page and picking `Close tab page`
    
- Actual result:
Occasionally (but not every time), I'll see the gigantic error logged above (`could not find tab for 99` (or whatever the ID is)).  Tab page doesn't close and UI seems to not respond anymore

- Expected result:
Tab page should be closed.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by luixxiul** [comment]
Another STR:

1. Clear the browser's profile
2. Start the browser 
3. Open `about:preferences` in a new tab next to `Welcome` tab
4. Detach the preference tab
5. Re-attach the preference tab
6. Click the close button on the tab
