### ISSUE TITLE
Browser updates to preview build with Update to preview releases switched off

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9943]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Browser updates to preview build with Update to preview releases switched off

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64 

- Brave Version (revision SHA):

Name | Version
-- | --
Brave | 0.17.13
rev | f7242c7
Muon | 4.1.7

- Steps to reproduce:
    1. Set env variable to `BRAVE_UPDATE_VERSION=0.8.3`
    2. Clean install 0.17.13 build and launch **_(Do not change any preference options)_**
    3. Wait for the browser to check for update and prompt update to install
    4. Click on details, ensure it shows update version to 0.17.13(stable release build)
    5. Open `about:brave` and check the browser version shows 0.17.13
    6. Click on **_Later_** in the notification bar
    7. Close the browser and wait for it to relaunch itself (#9169)
    8. Check `about:brave`, shows 0.17.14 
    
- Actual result:
Browser updates to preview build with Update to preview releases switched off

- Expected result:
Should remain on 0.17.13 instead of upgrading to 0.17.14

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
cc: @bsclifton

**Comment by aekeus** [comment]
Confirmed on Windows. The updater code never queries our metadata server for info.

```
2017-07-10 15:39:10> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2017-07-10 15:39:10> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-07-10 15:41:51> Program: Starting Squirrel Updater: --download https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64?accept_preview=false
2017-07-10 15:41:51> Program: Fetching update information, downloading from https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64?accept_preview=false
2017-07-10 15:41:51> CheckForUpdateImpl: Generated new staging user ID: 29e193ca-74d9-5097-a821-814bcb32612e
2017-07-10 15:41:51> CheckForUpdateImpl: Downloading RELEASES file from https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64?accept_preview=false
2017-07-10 15:41:51> FileDownloader: Downloading url: https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64/RELEASES?accept_preview=false&id=brave&localVersion=0.17.13&arch=amd64
2017-07-10 15:41:51> FileDownloader: Downloading file: https://brave-download.global.ssl.fastly.net/multi-channel/releases/dev/winx64/brave-0.17.14-full.nupkg
2017-07-10 15:42:42> UpdateInfo: Couldn't get release notes for:brave-0.17.14-full.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\Aubrey\AppData\Local\brave\packages\brave-0.17.14-full.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
```

**Comment by LaurenWags** [comment]
Could not reproduce on OSX using 0.17.13.

**Comment by bsclifton** [comment]
This has been an issue for a while- @aekeus has dug in and made some good discoveries. I removed blocker status and milestone for now

**Comment by aekeus** [comment]
I believe the BRAVE_UPDATE_VERSION env var was globally set. That would mean that the first call to the update server would have returned metadata indicating that an update was requested (to 0.17.13). The updater code would then retrieve the RELEASES file that indicates that 0.17.14 is the latest version. The updater would download the 0.17.14 binary and apply the upgrade.

To test this, I downloaded the 0.17.13 binary, deleted the Roaming folder and launched the browser from the icon (indicating that BRAVE_UPDATE_VERSION was not set). The request for update saw no available update as expected.

This raises a limitation on the Windows updater (Squirrel). It is not possible to indicate a specific version to upgrade to on Windows. The contents of the RELEASES file always dictates which binary is applied.

Summary: We should not create a preview too soon after a release on a channel, as any successful update request on Windows will received the latest version irrespective of whether it is a preview or release.

We could change where the RELEASES file is stored but its contents would also need to be correct by version.

This would be a fairly substantial change, but ultimately the best course of action.

Changes would be required in the browser (to retrieve the RELEASES file from the correct folder) and the uploader (to place the RELEASES file in correct S3 folder). My understanding is that the .nupkg file needs to reside in the same directory as the RELEASES file as well.

Ultimately each version would get its own RELEASES file stored with the related .nupkg. The directory name, for the request for RELEASES, would be constructed from the metadata retrieved on the first call to our server.
